### ISSUE TITLE
增加快捷键

### ISSUE THREAD

**Issue by hayeen** [ivarptr/yu-writer.site#1]
希望能够支持文本编辑时使用快捷键。

**Comment by wao1201** [comment]
还有一些必要的窗口快捷键，比如：CMD+W 关闭程序窗口

**Comment by hemashushu** [comment]
@hayeen 因为编辑快捷键跟正在开发当中的一些自动化处理相关联（比如 Alt ＋ Enter 用于将当前行变成同级别的 heading 之类的），而后者还在努力开发中，所以可能要等到 0.4.0 版才会完成。

**Comment by hemashushu** [comment]
@wao1201 现在的默认设定是 shift+cmd+w 关闭当前窗口（假设有多个窗口的话），cmd+w关闭当前标签页，或者关闭当前窗口（当所有标签页都关闭后），另外 ctrl+tab 用于多个标签页之间切换。

**Comment by scric** [comment]
是否会加入使字体加粗等等的快捷键？

**Comment by hemashushu** [comment]
@hayeen @wao1201 @scric 0.5 版已经加上，欢迎下载试用。这个 issue 我先关闭了哦
