### ISSUE TITLE
中文菜单

### ISSUE THREAD

**Issue by shuncon** [ivarptr/yu-writer.site#104]
希望gay主能够增加中文菜单
同时感谢gay主的开源

**Comment by hemashushu** [comment]
@shunconf 哈哈哈，多语言模块大概在 0.6 或 0.7 版加入，谢谢你的建议！

**Comment by shuncon** [comment]
gay主，导出md文件 能否把图片集成到md中。或者重新新建个图片存放的文件夹

**Comment by hemashushu** [comment]
@shunconf 好的，以后导出就这么办 😄

**Comment by PlutoNameless** [comment]
@ivarptr 那对于中文的支持大概能在多久执行呢？

**Comment by hemashushu** [comment]
@Thiece 大约半年左右 😅

**Comment by hemashushu** [comment]
@shunconf @Thiece 新版本 0.5.3 已释出，已经加入了中文界面，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
