### ISSUE TITLE
有时插入图像时，插入点会上移

### ISSUE THREAD

**Issue by pcdelphi** [ivarptr/yu-writer.site#105]
当内容比较长的时候，在最后一行插入图片，实际的插入点会跑到上两行中去
例如：  
`* 框选出的几个选项，是在查询结果中进行筛选条件；而其他的则是查询条件，包括第二行的线路名称等。
应该将第二行的查询条件放到第一行，筛选条件放到第二行，并在前面标明是筛选    

P  
`   

`P`表示光标的位置，插入图片后变成这样：  

`* 框选出的几个选项，是在查询结果中进行筛选条件；而其他的则是查询条件，包括第二行的线路名称等。
![计调-线路管理03](%E8%AE%A1%E8%B0%83-%E7%BA%BF%E8%B7%AF%E7%AE%A1%E7%90%8603.png)
P
应该将第二行的查询条件放到第一行，筛选条件放到第二行，并在前面标明是筛选

`

**Comment by abigtreenj** [comment]
我也遇到这个问题了.

**Comment by hemashushu** [comment]
@pcdelphi @abigtreenj  0.5版（尚未发布）已修复此 BUG，谢谢你的反馈！

**Comment by hemashushu** [comment]
@pcdelphi @abigtreenj 新版本 0.5.3 已释出，已经解决了这个问题，欢迎下载试用看看问题是否依旧，如有问题欢迎随时问，这个 issue 我先关闭哈。
