### ISSUE TITLE
请问可以在语句中插入一些html代码以控制图片大小吗?

### ISSUE THREAD

**Issue by abigtreenj** [ivarptr/yu-writer.site#106]
比如
`<div align=center><img src="https://latex.artofproblemsolving.com/d/6/c/d6c903419860d4d2d6fb832a27d73e8e7acd40ae.png" height="150px" /></div>`
这样的语句插入在markdown文档中, 可以被接受吗? 或者有这样的计划吗?
我用版本(0.4.4 beta), 这样的语句不显示图片.
请教了.

**Comment by hemashushu** [comment]
@abigtreenj 是的，现在的文档不能解析 html 标签，大概到 0.7 版文档库会有一个选项让用户选择是否渲染 html 标签，谢谢你的建议！

**Comment by hemashushu** [comment]
@abigtreenj 至于图片大小的控制，可能以后某个版本会稍微扩充一下 markdown 语法，但具体方案还没想好，准备先多参考其他编辑器/解析器的做法，最后采用较多人使用的方案。

**Comment by jzlzl** [comment]
希望可以快点出控制图片大小的功能

**Comment by hemashushu** [comment]
@abigtreenj @JZL-GL 新版本 0.5.3 已释出，已经加入了解析 HTML 标签的支持，默认该特性为关闭的，可以在设置里打开，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
