### ISSUE TITLE
不应该显示 HTML 注释？

### ISSUE THREAD

**Issue by ElfSundae** [ivarptr/yu-writer.site#107]
刚刚安装的这个软件，正在试，感觉很棒 👍  谢谢！

发现个问题， 阅读模式或导出时，Markdown 中的 HTML 注释没过滤。

```html
<!-- 注释 -->
```

**Comment by hemashushu** [comment]
@ElfSundae 是的。现在的文档是完全不解析 html 标签的，以后某个版本会在文档库加上选项让用户选择是否解析 html 标签，谢谢你的鼓励和反馈！

**Comment by ElfSundae** [comment]
好的 👌

**Comment by hemashushu** [comment]
@ElfSundae 0.5 版已加上。
