### ISSUE TITLE
是否有计划加入中文版

### ISSUE THREAD

**Issue by Spacebody** [ivarptr/yu-writer.site#11]
目前都是英文版，虽然对我个人没啥影响，但是从满足用户需求的角度来说后期有没有计划加入中文支持？

**Comment by hemashushu** [comment]
@Spacebody 有，可能到正式版时会完成多语言（i18n）模块，现在是因为在 beta 阶段每次更新的变化都挺大的，如果现在加上 i18n 则每次更新同时还要翻译变化的部分，这样怕精力有点顾不上，所以就等到接近正式版或者到正式版，变化没那么大时再加上。

**Comment by sikenali** [comment]
![qq 20170821093255](https://user-images.githubusercontent.com/26103116/29500532-07d9effc-8654-11e7-9f1c-127805f9b133.png)
非常赞 期待中文包  也非常期待linux版本，到时候我们会上架深度商店，我是deepin党。

**Comment by xkonglong** [comment]
初期提供语言文件就行了,不用翻译. 有需要的人会自己翻译的.

**Comment by hemashushu** [comment]
@jingle0927 嗯嗯，下一个版本会把界面再仔细调整一下，然后理顺各个功能的操作流程，就可以出 Linux 版啦，到时我通知你，在此先感谢啦～

**Comment by hemashushu** [comment]
@xkonglong 好的
