### ISSUE TITLE
中文图片名称会变成编码

### ISSUE THREAD

**Issue by pcdelphi** [ivarptr/yu-writer.site#110]
使用系统的插入图片功能，中文文件名会变成如下编码形式，手工将编码改成正确的中文名称，图片可以正常显示
`![计调-产品发布-用餐](%E8%AE%A1%E8%B0%83-%E4%BA%A7%E5%93%81%E5%8F%91%E5%B8%83-%E7%94%A8%E9%A4%90.png)`

**Comment by hemashushu** [comment]
@pcdelphi 是的，因为语法上括号内的是URL，所以中文还有特殊符号会被编码成 %FF 这样的形式。

**Comment by hemashushu** [comment]
@pcdelphi 新版本 0.5.3 已释出，虽然插入中文名图片依然会被编码（因为 html 标准），但原先存在一个：使用 “插入图片” 按钮来编辑已有的图片代码，如果是中文名时会出现bug的问题，所以欢迎下载新版本试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
