### ISSUE TITLE
關於Markdown格式問題[x] 

### ISSUE THREAD

**Issue by diabolo94** [ivarptr/yu-writer.site#115]
希望接下來你的0.5版本的Markdown格式可以做到那種打勾的效果
例如這樣的
- [ ] @mentions, #refs, [links](), **formatting**, and <del>tags</del> supported
- [ ] list syntax required (any unordered or ordered list supported)
- [x] this is a complete item
- [ ] this is an incomplete item

**Comment by hemashushu** [comment]
@diabolo94 已加上，敬请期待 😀

**Comment by hemashushu** [comment]
@diabolo94 新版本 0.5.3 已释出，已经加入复选框/任务列表的支持，在编辑框里使用 Ctrl或Command键+鼠标点击可改变状态，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
