### ISSUE TITLE
文件夹里有大文件打开时会卡顿

### ISSUE THREAD

**Issue by whzecomjm** [ivarptr/yu-writer.site#116]
library里的文件夹内如果存在大文件（100KB左右）时，点击文件夹进入会出现卡顿。

**Comment by hemashushu** [comment]
@whzecomjm 已知悉，谢谢反馈！

**Comment by hemashushu** [comment]
@whzecomjm 新版本 0.5.3 已释出，应该已经解决了这个问题，欢迎下载试用看看问题是否依旧，如有问题欢迎随时问，这个 issue 我先关闭哈。
