### ISSUE TITLE
ReadMode下，html的table标签无法正常显示的疑问

### ISSUE THREAD

**Issue by zhoubhin** [ivarptr/yu-writer.site#117]
html表格源内容如下图一所示：
![image](https://user-images.githubusercontent.com/14870175/33111276-215f85e0-cf88-11e7-9ea6-acb1fd08dd75.png)
预览模式下，表格未能正常展现，如下图二所示：
![image](https://user-images.githubusercontent.com/14870175/33111357-96835900-cf88-11e7-804a-92840fad42f9.png)
是代码缩进的问题还是其他问题？

**Comment by hemashushu** [comment]
@zhoubhin 不好意思回复晚了。现在文档渲染还不支持HTML标签，所以只能使用纯 markdown 语法来生成表格
比如

```markdown
|  | Scope | Reassignable | Mutable | [Temppral Dead Zone](#tdz_sample) |
|---|---|---|---|---|
| const | Block | No | [Yes](#const_mutable_sample) | Yes |
| A2 | B2 | C2 | D2 | E2 |
| A3 | B3 | C3 | D3 | E3 |
```

未来的版本会加入选项让用户选择是否支持解析HTML标签，谢谢你的反馈

**Comment by hemashushu** [comment]
@zhoubhin 新版本 0.5.3 已释出，已经加入解析 HTML 标签的支持，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
