### ISSUE TITLE
mac版本不能export为图片

### ISSUE THREAD

**Issue by wilsli** [ivarptr/yu-writer.site#119]
MBA 11-inch 2013
macOS 10.13.1
Yu Writer 0.4.4beta

选完导出格式之后点“export”无任何反应。

**Comment by hemashushu** [comment]
@wilsli 版本 0.4.4 还没完成，到 0.5 版会加上，谢谢反馈！

**Comment by hemashushu** [comment]
@wilsli 新版本 0.5.3 已释出，已经加上导出图片功能（但也还没完全完成），欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
