### ISSUE TITLE
首页跳动的图片大图显示不正常

### ISSUE THREAD

**Issue by no1xsyzy** [ivarptr/yu-writer.site#120]
我是指<https://ivarptr.github.io/yu-writer.site/>的“简洁、可定制的界面”一节

在图片跳动的时候情况下点开大图会反复在小图和大图之间跳

**Comment by hemashushu** [comment]
@no1xsyzy 哈哈哈，谢谢反馈，我检查一下

**Comment by hemashushu** [comment]
@no1xsyzy 新版本 0.5.3 已释出，原先的主页的截图因为跟新版本出入很大所以就改版了，所以这个问题算 “解决” 了，哈哈哈。ps 欢迎下载新版本试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
