### ISSUE TITLE
点击Link按钮报错

### ISSUE THREAD

**Issue by wangwenx190** [ivarptr/yu-writer.site#122]
每次点击Link按钮必报错，但关掉提示框之后也不影响正常使用。    
操作系统 Win10 1709 x64 专业版     
![default](https://user-images.githubusercontent.com/17877450/33644659-22af2758-da81-11e7-8573-a47ca9fe1100.PNG)

**Comment by hemashushu** [comment]
@wangwenx190 谢谢反馈！我稍后检查一下。

**Comment by hemashushu** [comment]
@wangwenx190 新版本 0.5.3 已释出，这个问题应该是解决了，因为新版本改动较大，所以不清楚新版本是否还有这个问题，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
