### ISSUE TITLE
建议~~

### ISSUE THREAD

**Issue by newamber** [ivarptr/yu-writer.site#123]
首先赞一个，作者开发的软件太良心了，试用了一两天感觉很棒

由于我之前用的Typora，它的特点是所见即所得，这一点感觉比较好，但是文字内容太多之后软件极易卡慢，而我用您的软件一点卡顿都没~~太好了

建议：
1. 再多加点样式主题，或者用户可以自定义添加主题
2. 导出pdf的感觉还要调一下字体大小和间距，当然这是我个人感觉...
3. 我不知道typora的那种所见即所得的功能难度有多大，如果作者把该做的都做了，可以考虑下这个功能嘛？ 手动比心

最后谢谢作者的辛勤付出

**Comment by hemashushu** [comment]
@Newamber 首先感谢你的鼓励和支持！
第1，2点会在0.5版之后逐渐扩充完善。而即见即所得这种编辑模式难度和工作量其实还是蛮大的，另外跟现有的编辑风格也有些许出入，我比较偏好完全控制型，即直接编辑文档的原始源码这种，所以未来应该不会加入“即见即所得”。
但在 0.5 版及以后版本我加入了较多的辅助编辑功能，比如表格的编辑会弹出单独的表格录入窗口，虽然比即见即所得稍微麻烦一步，但在这个窗口内除了常规的录入行列之外，还能调整行列顺序位置、排序、删除/插入行列，选择文字对其方式等（完成表格编辑功能可能要到 0.6 版才完成）。

**Comment by ernsky** [comment]
导出的PDF格式太丑了。

**Comment by qw4096** [comment]
第2点+1，导出pdf的字体大了些，写简历如果要打印就不太好看了，而且废纸
总之还是感谢作者

**Comment by newamber** [comment]
谢谢解答，补充一点建议，就是导出的pdf文档在用pdf阅读软件打开的时候没有outline，就是目录这一类的东西，如果有的话，能给自己的阅读带来很大便利，谢谢！
