### ISSUE TITLE
Code Block里的#会被索引到Outline里面，导致Outline不能正确定位

### ISSUE THREAD

**Issue by HowardZit** [ivarptr/yu-writer.site#124]
Code Block 示例:
```
#this is a comment
```
‘#’后面的语句并不会出现在outline，但是双击其他标题outline跳转时会跳到这个语句。

系统版本：Windows Home 1709
Yu Writer 版本: 0.4.4beta

**Comment by HowardZit** [comment]
刚刚测试了一下，缩进‘#’后就可以正常使用

```
# this does not work
 # this works
```

**Comment by hemashushu** [comment]
@HowardZit 是的，这是一个bug，在 0.5 版会修复，谢谢反馈

**Comment by hemashushu** [comment]
@HowardZit 新版本 0.5.3 已释出，已经解决了这个问题，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
