### ISSUE TITLE
请问如何在文档左侧显示文档行数

### ISSUE THREAD

**Issue by PansonPanson** [ivarptr/yu-writer.site#128]

**Comment by hemashushu** [comment]
@PansonPanson 需要在下一个版本 （0.5）才支持此功能，下个版本大概两个月内发布

**Comment by hemashushu** [comment]
@PansonPanson 新版本 0.5.3 已释出，已经加入了显示行数功能，方法可参阅软件附带的文档，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
