### ISSUE TITLE
Read Mode 异常

### ISSUE THREAD

**Issue by whzecomjm** [ivarptr/yu-writer.site#129]
有时候打开Read Mode不会显示当前文档的预览，可能是之前文档，也可能是空白。前者需要点击一下下方的 document style可能会自动刷新，后者只能重启 YU writer。

ps. YU writer的启动能优化一下吗，感觉要等个好几秒。

谢谢~

**Comment by hemashushu** [comment]
@whzecomjm 谢谢反馈！我稍后检查一下这模块

**Comment by hemashushu** [comment]
@whzecomjm 新版本 0.5.3 已释出，因为新版本改动很多地方改动也很大，欢迎下载试用看看问题是否依旧，如有问题欢迎随时问，这个 issue 我先关闭哈。
