### ISSUE TITLE
建议：增加自动补全、填充格式

### ISSUE THREAD

**Issue by ferocknew** [ivarptr/yu-writer.site#130]
例如：
编写列表的时候
```
- aaaa
- bbbb
- cccc
```

直接回车就会补全 - 符号，或者

```
1. aaaa
2. bbbb
3. cccc
```
自动补全 2.  3.

**Comment by hemashushu** [comment]
@ferocknew 下一个版本 （0.5）会支持此功能，下个版本大概两个月内发布，谢谢你的建议！

**Comment by hemashushu** [comment]
@ferocknew 新版本 0.5.3 已释出，已经增加了自动完成功能，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
