### ISSUE TITLE
建议，编辑模式下内容超过一屏时，光标的位置可以保持在屏幕中间

### ISSUE THREAD

**Issue by wangerblog** [ivarptr/yu-writer.site#131]
编辑模式下，内容超过半屏时，保持光标默认位置在屏幕的中间，文字内容自动向上滚动。

文字超过一屏时，光标只能保持在屏幕的最下方，感觉好别扭。只能敲好多空行，然后把光标移上来。

我是强迫症么？？？

**Comment by hemashushu** [comment]
@wangerblog 进入设置里，选择其他焦点模式（focus type）

**Comment by hemashushu** [comment]
@wangerblog 新版本 0.5.3 已释出，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
