### ISSUE TITLE
实时预览好像不支持latex，比如矩阵

### ISSUE THREAD

**Issue by zhizunbao84** [ivarptr/yu-writer.site#136]
但是read mode 是没问题的。
instant view 和read mode 有什么区别啊

**Comment by hemashushu** [comment]
@zhizunbao84 即时预览主要是用于瞥一眼语法有无错误以及用于（滚动）定位，因为现在的即时预览对数学公式渲染有些性能的 BUG 所以默认没有启用，如果需要启动的话可以到 settings 里勾选它。ps 下一个版本（0.5）已经修正这个 BUG，所以又默认启用数学公式渲染了哈哈

**Comment by hemashushu** [comment]
@zhizunbao84 新版本 0.5.3 已释出，已经改进公式的渲染速度问题，现在是默认打开了公式渲染，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
