### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by JustYummy** [ivarptr/yu-writer.site#137]
建议加个单击打开Libraries及文档的按钮。双击的话，过程太繁琐。

**Comment by hemashushu** [comment]
@JustYummy 谢谢建议，下个版本会改进

**Comment by hemashushu** [comment]
@JustYummy 新版本 0.5.3 已释出，已经增加树型列表以及单击打开，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
