### ISSUE TITLE
不支持在表格里换行？

### ISSUE THREAD

**Issue by alvinlyb** [ivarptr/yu-writer.site#138]
不支持在表格里换行？使用<br>没有起作用。表达式数学公式等和网易的有道笔记也不一样。

**Comment by hemashushu** [comment]
@alvinlyb 你好，根据GFM格式要求如果需要在表格（单元格）里换行需要使用 HTML 的 <BR> <P>等标签，但由于目前版本还没支持渲染 HTML 标签所以暂时没法实现换行，到后面的版本将会加入渲染 HTML
 标签的支持选项，谢谢反馈

**Comment by hemashushu** [comment]
@alvinlyb 新版本 0.5.3 已释出，已经加上解析 html 标签的选项，所以可以在表格里使用 <br> 来换行了，另外数学公式使用了更为通用的 Mathjax，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
