### ISSUE TITLE
作者不打算出付费？觉得这个 app 还不错

### ISSUE THREAD

**Issue by yuanyuanyuan** [ivarptr/yu-writer.site#140]
付费可以更加专注开发，也可以保持app 的生命周期

**Comment by xingyi1015** [comment]
价格合理的订阅，会支持的

**Comment by hemashushu** [comment]
@yuanyuanyuan @xingyi1015 在下先感谢两位的鼓励和支持 😁 ！是有打算在完成正式版后推出个收费的版本，只是……现在的版本离正式版还有很远的路，很多模块还没实现，就是个半成品所以不好意思收费啊，哈哈哈。春节左右会发布个更新非常大的版本 —— 0.5 版，大概就是完成了我目标的 50% 样子，噗

**Comment by xingyi1015** [comment]
加油，期待3个平台同步

**Comment by exuan** [comment]
质量非常，值得付费。

**Comment by zhyt0520** [comment]
@ivarptr 非常期待下一个版本 :thumbsup: 加油

**Comment by hemashushu** [comment]
@exuan @zhyt0520 谢谢鼓励哈 😄！

**Comment by httpsgithu** [comment]
It seems your project is apache but not.
If you want it to be closed-source. Don't published it at github-free go to make your ownsite vps.
This time you are abuse.
You are not allowed by the tos.

**Comment by ddkk3000** [comment]
大赞，比我的收费的markeditor好使，相见恨晚啊，先赞个30，好软件！

**Comment by hemashushu** [comment]
@ddkk3000 非常感谢你的鼓励！😘

**Comment by qw4096** [comment]
同期待0.5

**Comment by hemashushu** [comment]
@yuanyuanyuan @xingyi1015 @exuan @zhyt0520 @qw4096 新版本 0.5.3 已释出，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
