### ISSUE TITLE
希望外部链接的文件夹能支持重命名

### ISSUE THREAD

**Issue by catouse** [ivarptr/yu-writer.site#142]
我想使用一个外部文件夹（例如 `doc`）作为我的库，但是我不想这个库就叫 `doc`，希望能起一个更有意义的名字。希望外部链接的文件夹能否支持重命名。

**Comment by hemashushu** [comment]
@catouse 目前的版本已支持这样的功能，重命名外部文件夹类型的库的名字不会改变原始文件夹的名字，但库的名字已经是新名字。

比如在文档库里建立了一个链接到外部文件夹 `/User/hello/doc` 的库，yu writer 默认会把库的名字命名为 `doc` （原理上是创建了一个符号链接（对于 Linux 和 Mac 平台）或者一个链接描述文本文件（对于
 Windows 平台）），现在你把库的名字更改为 `2018 Documents`，则库的名字已改，但原始文件夹 `/User/hello/doc` 仍然保持原来的名字。

**Comment by catouse** [comment]
好的，那我关闭了。
