### ISSUE TITLE
创建无序列表时，上一条列表字体会变大

### ISSUE THREAD

**Issue by linvaux** [ivarptr/yu-writer.site#143]
![image](https://user-images.githubusercontent.com/33976489/34592573-15326efa-f200-11e7-9c77-db1c584d3a9a.png)

**Comment by hemashushu** [comment]
@linvaux 因为使用 `-` 符号时程序误以为上一行是二级标题了 😅，后续的版本会修正这个 bug，谢谢反馈！

**Comment by hemashushu** [comment]
@linvaux 新版本 0.5.3 已释出，已经修复了这个问题，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。

**Comment by linvaux** [comment]
收到，谢谢

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Hippo Spark <notifications@github.com>
发送时间: Saturday, September 1, 2018 4:31:03 AM
收件人: ivarptr/yu-writer.site
抄送: linvaux; Mention
主题: Re: [ivarptr/yu-writer.site] 创建无序列表时，上一条列表字体会变大 (#143)


@linvaux<https://github.com/linvaux> 新版本 0.5.3 已释出，已经修复了这个问题，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。

―
