### ISSUE TITLE
希望增加gitbook的css样式

### ISSUE THREAD

**Issue by newamber** [ivarptr/yu-writer.site#146]
gitbook的版面和代码配色很舒服，希望作者大大加入这个主题啦~~⭐

**Comment by hemashushu** [comment]
@Newamber 谢谢你的建议！“book” 类型的库的相关功能正在开发中。

**Comment by vyan13** [comment]
主要是给点自定义权限，可以自己做喜欢的主题。

**Comment by hemashushu** [comment]
@vuyzan 明白！自定义UI主题、文档样式、文档模版等大概在 0.6 或者 0.7 版完成
