### ISSUE TITLE
Mac下最新版本安装后不可打开

### ISSUE THREAD

**Issue by cherry-yang-workspace** [ivarptr/yu-writer.site#149]
Cannot read property 'themeItems' of undefined......****..... at mainprocess.js:4990

**Comment by hemashushu** [comment]
@godchao 试试清空一下缓存，即手动删除下面两个文件夹：
1. ~/Library/Caches/Yu Writer
2. ~/Library/Application Support/Yu Writer

**Comment by hemashushu** [comment]
@godchao 新版本 0.5.3 已释出，理论上已经解决了这个bug，欢迎下载试用看看问题是否依旧，如有问题欢迎随时问，这个 issue 我先关闭哈。
