### ISSUE TITLE
Mac版本，添加的Library内有些文件没有显示

### ISSUE THREAD

**Issue by erafat** [ivarptr/yu-writer.site#150]
RT，在Library内没有显示，但是搜索可以搜索到该MD文件

**Comment by hemashushu** [comment]
@erafat 请问是添加了类似 hexo 博客的项目文件夹吗？

**Comment by Lin-Ss** [comment]
@ivarptr 
我的windows版本也是，是加载了Hexo之后_post文件夹下面只有一个Hello,World.md，其他新建的md文件不显示。
我的md文件有使用中文字符，希望得到帮助。
另外，你的Yu Writer真的很棒。

**Comment by hemashushu** [comment]
@Lin-Ss 你好，这个是 0.4.4 的一个已知bug，原因是有某个md的 Front Matter （YAML）的内容有无无法解析导致文件列举不全，0.5版已修复，谢谢反馈

**Comment by hemashushu** [comment]
@erafat @Lin-Ss 新版本 0.5.3 已释出，已经修复了这个问题，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
