### ISSUE TITLE
阅读模式下切换 document style 的交互问题

### ISSUE THREAD

**Issue by BiKibb** [ivarptr/yu-writer.site#152]
阅读模式下，要切换不同的 document style，常见的交互方式是点击最下方的 style 即可完成切换，然后在 Windows 0.4.4 beta 版本中切换的行为是先点击想要 style，没有反应，退出阅读模式后重新进入才完成了切换动作，这个交互令我很不解，希望可以看看。
![](http://telegra.ph/file/3e35e24c69018e1503134.gif)

**Comment by serialq7ic4** [comment]
我在windows中是随点随切换的诶，不需要关闭重新打开

**Comment by hemashushu** [comment]
@chenq7an 这个是附带的几个文档的bug，自己建的文档应该可以顺利切换 style。谢谢你的反馈！

**Comment by hemashushu** [comment]
@BiKibb @chenq7an 新版本 0.5.3 已释出，已经修复了这个bug，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
