### ISSUE TITLE
Read mode 下点击不同样式没有响应

### ISSUE THREAD

**Issue by txd159** [ivarptr/yu-writer.site#154]
环境: window 10 x64
yu writer : v0.4.4 beta

点开read mode,点击不同的样式没有响应,渲染也没变化.  但是关闭read mode 后再打开read mode,发现更改的样式已经成功切换并且渲染.

**Comment by hemashushu** [comment]
@txd159 你好 ，这个是自带的说明文档的bug，谢谢反馈

**Comment by txd159** [comment]
ghh

**Comment by hemashushu** [comment]
@txd159 新版本 0.5.3 已释出，已经修复了这个bug，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
