### ISSUE TITLE
关于Tab制表格式符

### ISSUE THREAD

**Issue by hyprocritor** [ivarptr/yu-writer.site#155]
使用Tab做类似空格的制表符功能是，预览界面和阅读模式界面不一样。生成的阅读界面会将制表符就是tab的那个长空格删除掉。

**Comment by hemashushu** [comment]
@czk1997 谢谢反馈

**Comment by hemashushu** [comment]
@czk1997 新版本 0.5.3 已释出，已经统一了 tab 和两个空格（默认情况下，在 yu writer 里按下 tab 键实际上输入的是两个空格符号，可在应用程序配置文件里修改），欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
