### ISSUE TITLE
You Writter没有开源吗

### ISSUE THREAD

**Issue by sheacoding** [ivarptr/yu-writer.site#156]
开源代码利用开源社区的力量帮助You Writter成长啊😄

**Comment by httpsgithu** [comment]
+1

**Comment by httpsgithu** [comment]
If you want it to be closed-source. Don't published it at github-free go to make your ownsite vps.
This time you are abuse.
You are not allowed by the tos.

**Comment by hemashushu** [comment]
@sheacoding 现在还没有开源的计划，因为这个项目的代码量还是挺大的，精力有限可能没时间维护，等以后大致完成或定型之后可能会有部分开源的计划。

**Comment by hemashushu** [comment]
@PowerOlive 不，当前项目是 “yu-writer.site“，它并不是项目 "yu-writer"，在 README 已经明确说明了。"yu-writer.site" 这个项目本身是开源的，基于 Apache 开源协议，任何人都可以查看及 Fork 这个项目的源码（包括 scss， js 等）。如果有违反 github tos，请以 github 的账号发 email 告知我，谢谢反馈！
