### ISSUE TITLE
如何在表格中换行？

### ISSUE THREAD

**Issue by jluliuchao** [ivarptr/yu-writer.site#157]
从网上查是通过加br来实现，在为知笔记中的确能实现换行，但yu writer不行，不知在yu writer中是如何换行的？
![image](https://user-images.githubusercontent.com/35259060/35549408-61e7e33c-05c0-11e8-9158-418a27884e6c.png)

**Comment by lucian7l** [comment]
试过了网上搜到的 <br> html标签方法和 两个空格加回车的方法，在Yu Writer里都不奏效，热切盼望作者早日加入表格内换行功能

**Comment by hemashushu** [comment]
@jluliuchao @lucian7l 是的，现在还不支持解析 html 标签，往后版本会添加上，谢谢反馈

**Comment by hemashushu** [comment]
@jluliuchao @lucian7l 新版本 0.5.3 已释出，已经加上解析 html 标签的选项，因此可以在 表格里使用 `<br>` 符号来换行，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。

**Comment by keqinyang** [comment]
@ivarptr 你好，我今天刚刚下载了Yu Writer，很棒的软件，我也在关注“表格内换行”这个功能，今天刚下载使用的0.5.3版本，不知道哪里的问题，使用<br>没有实现表格内换行，求赐教。

**Comment by hemashushu** [comment]
@keqinyang 表格内换行只能通过插入 `<br>` 这个 HTML 标签实现，可以在设置里启用 HTML 标签解析功能，或者在文档的头部加入 `enable html: true` 选项：

```
---
enable html: true
---
以下是文档的正文开始
```

不过目前的 HTML 标签解析功能有 bug，可能要等到 0.6 版才正常，谢谢反馈。
