### ISSUE TITLE
Cannot delete Default folder

### ISSUE THREAD

**Issue by sunnyyoung** [ivarptr/yu-writer.site#158]
## Description

Cannot delete Default folder, every time after deleted the Default folder and relaunch application the Default folder will be created again.

## Screenshot

![image](https://user-images.githubusercontent.com/5926284/35556252-b5ba4e20-05dc-11e8-834c-19113f7ce36d.png)

**Comment by hemashushu** [comment]
@Sunnyyoung Yes, because it's the 'Default' library :D , but it will be removed or rename in the next version (0.5.x).

**Comment by hemashushu** [comment]
@Sunnyyoung 新版本 0.5.3 已释出，已经 “修复” 了这个问题，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭。
