### ISSUE TITLE
一个建议，左侧文章信息中那个“a minute ago”“2 days ago”

### ISSUE THREAD

**Issue by vyan13** [ivarptr/yu-writer.site#161]
会不会弄成具体的某年某月某日何时更好一些，像说什么……ago 在内心中想的时候，还是要换算到某个具体的时间坐标。

**Comment by hemashushu** [comment]
@vuyzan 当前的版本是用鼠标指针停留在时间上会显示一个正常的日期格式，下一个版本将会改成“月日”显示，谢谢你的建议！
