### ISSUE TITLE
download the newest on website ,cant open

### ISSUE THREAD

**Issue by qbmiller** [ivarptr/yu-writer.site#165]
![image](https://user-images.githubusercontent.com/7335567/35915546-43382482-0c42-11e8-8aa1-2c8090b607fc.png)

**Comment by hemashushu** [comment]
@qbmiller 新版本 0.5.3 已释出，理论上已经修复这个bug，欢迎下载试用看看问题是否依旧，如有问题欢迎随时问，这个 issue 我先关闭哈。
