### ISSUE TITLE
新版本请务必加上实时字数统计！！！

### ISSUE THREAD

**Issue by vyan13** [ivarptr/yu-writer.site#168]
拜托了，实在是太有必要了！！！可以的话，段落统计不知能否也加上。
个人倒是觉得中文界面不必太着急，以现在人的英文水瓶，对付个软件还是不成问题的。现在加了中文界面，后期有改动还是要增加重复工作，不合算。
大佬加油，出正式版后付费支持。

**Comment by hemashushu** [comment]
@vuyzan 是的，多语言模块在软件开发初期工作量还是蛮大的，所以需要在各个功能模块比较稳定时才加上。字数统计在下一版本就会加上。谢谢你的建议！
