### ISSUE TITLE
第一次启动错误

### ISSUE THREAD

**Issue by dalchemist** [ivarptr/yu-writer.site#169]
![image](https://user-images.githubusercontent.com/19801695/36070220-7627dd1e-0f31-11e8-8082-3a2895ffaf5d.png)
![image](https://user-images.githubusercontent.com/19801695/36070222-7e6354e0-0f31-11e8-8124-d14559b9f41e.png)

**Comment by dalchemist** [comment]
已测试：0.4.3bane版本可以正常启动。0.4.4版本启动错误。

**Comment by hemashushu** [comment]
@dalchemist 谢谢你的报告！
这个错误是因为诸如“我的图片”，“我的文档”，“下载"， “桌面” 等文件夹被删除（注册表里没有指定）所导致的，暂时的解决方法是在注册表当中加入这些文件夹的路径。

**Comment by hemashushu** [comment]
@dalchemist 新版本 0.5.3 已释出，已经修复了这个问题，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
