### ISSUE TITLE
Support custom HTML tags

### ISSUE THREAD

**Issue by syhily** [ivarptr/yu-writer.site#17]
希望在預覽裡面支持一些 HTML 的標籤，如 `iframe`，`<!-- commets -->`  之類的。

**Comment by hemashushu** [comment]
@syhily 是指在编辑框右侧的“即时预览”里显示 iframe 之类的标签吗？谢谢你的意见！

**Comment by syhily** [comment]
不光即時預覽，還有閱讀模式裡面。因為你支持 Hexo，所以遇到了這個問題，Hexo 的截斷就是 `<!-- more -->`，所以在閱讀模式裡面就很醜。

**Comment by hemashushu** [comment]
@syhily 明白！谢谢你的意见！

**Comment by syhily** [comment]
換言之，希望在閱讀模式裡面對於 HTML 那些標籤不要顯示為純文本，最好能被渲染。本身 Markdown 是允許HTML 標籤的，能被渲染的話會比較方便。

**Comment by hemashushu** [comment]
@syhily 是的，我打算这样你看合适可否，对于非 blog 类型的 library 仍然是不解析 HTML 标签。对于 blog 类型的 library 在编辑框会语法高亮 HTML 标签，在即时预览里解析部分诸如 <div> <span>  等有限的标签（因为没有加载样式表，一般解析的结果就是不显示），在阅读模式里再解析 <iframe> 以及其他以后再详细考虑的标签，然后增加一个完全解析（包括加载样式表）的预览模式，一个独立的窗口（之前有人提过这个意见）。这样应该对 blog 类型项目会更好一些。

**Comment by syhily** [comment]
這樣子的話，自然是極好的。但是沒有想明白為何限制必須是博客類型。

**Comment by hemashushu** [comment]
@syhily 因为还有很多人是用来记事、记笔记或者写电子书，这种情况下一般不会再在 markdown 里面插入 HTML 标签，这时解析 HTML 标签的话反而会带来不便

**Comment by syhily** [comment]
那麼，最好的方式是，Make it configurable ?

**Comment by hemashushu** [comment]
@syhily 也许是，在默认的基础上在让用户勾选是否解析HTML

**Comment by hemashushu** [comment]
@syhily 0.5.3 已加上 html 解析选项，欢迎下载试用，如果有问题欢迎随时反馈，这个 issue 我先关闭咯。
