### ISSUE TITLE
建议，关于文件夹与文档

### ISSUE THREAD

**Issue by vyan13** [ivarptr/yu-writer.site#171]
如果点一下，文件夹展开，其内文档出现
这样的方式会不会比双击进入文件夹要好，可以方便调用不同文件夹下的不同文档工作。
虽然说上栏能够展示出很多文档，但由于工作时很可能会同时打开NNNN多个文档，所以不太够用。
坏处也有，若如此，似乎与上栏功能重复。而且美观似乎也是个问题？
当然，这只是我根据我自己的使用过程提出的个人建议。

**Comment by vyan13** [comment]
打个比方，比方说你想做一个私人wiki，当其下有三个文件夹、文件夹下总共有十个八个文档时，现在的设计是可以应付过来的。
但当你有十个文件夹，每个文件夹下有十个八个文档时，恐怕就会手忙脚乱了。
所以，感觉现在的这个样子，只能够应付轻量的写作需求，还不够强大。

**Comment by hemashushu** [comment]
@vuyzan 所以一下版我加入了目录树以及在单独一列显示文档，试试这样会不会更好。谢谢你的建议哦！
