### ISSUE TITLE
下载失败，能不能给个百度云链接或者QQ群之类的？

### ISSUE THREAD

**Issue by wjingyuan** [ivarptr/yu-writer.site#173]
不知道GitHub什么原因，现在浏览速度都很慢，下载直接失败。下载了几个小时，最后还是失败了，能否给一个安装包？

**Comment by Ancientwood** [comment]
[下载](https://jp.archboy.org/yu-writer/yu-writer-beta-0.4.4-windows.zip)地址

作者README里有说[网站](https://ivarptr.github.io/yu-writer.site)

**Comment by zhyt0520** [comment]
win版本的
https://pan.baidu.com/s/1sm8k0MT
npft

ps.你需要一个稳定访问GitHub的方案

**Comment by hemashushu** [comment]
@wjingyuan 新版本 0.5.3 已释出，在主页里下方有两个下载镜像，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
