### ISSUE TITLE
请问编辑界面的字体怎么搞大一点，现在竟然是有极放大，还是太小了

### ISSUE THREAD

**Issue by ddkk3000** [ivarptr/yu-writer.site#174]
我眼瞎，看的不舒服

能不能无极放大啊，竟然只能放3次，那做成快捷键干嘛

**Comment by hemashushu** [comment]
@ddkk3000 你好，请问放很大时的使用场景是？是准备把文档作为投影演示时使用吗？如果是的话，下一版会有一个功能估计你会很喜欢，在此我先卖一个关子，到发布时我再通知你哈，哈哈哈

**Comment by ddkk3000** [comment]
我可以单纯就因为眼瞎吗？??

我没有要演示。我只是想字大点儿。

好的，谢谢，我等下一版。


于 2018年2月25日 17:45，Hippo Spark <notifications@github.com>写道：


@ddkk3000<https://github.com/ddkk3000> 你好，请问放很大时的使用场景是？是准备把文档作为投影演示时使用吗？如果是的话，下一版会有一个功能估计你会很喜欢，在此我先卖一个关子，到发布时我再通知你哈，哈哈哈

―

**Comment by hemashushu** [comment]
@ddkk3000 0.5.3 版的字体大小能否满足？如果可以的话这个 issue 我先关闭了哈。如有问题欢迎随时 reopen
