### ISSUE TITLE
Mac上的文章列表向左划动显示Delete按钮，点击无反应。

### ISSUE THREAD

**Issue by AlanLang** [ivarptr/yu-writer.site#181]
如图：
![](http://oqdzx28cd.bkt.clouddn.com/18-3-2/61395138.jpg)
红色的delete按钮点击无反应。

**Comment by hemashushu** [comment]
@AlanLang 这里是有个 bug，谢谢反馈！

**Comment by hemashushu** [comment]
@AlanLang 新版本 0.5.3 已释出，因为新版本把这个模块完全改版了，所以这个问题也一道 “被修复” 了 😄 ，欢迎下载新版本试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
