### ISSUE TITLE
程序运行报错：A JavaScript error occurred in the main process 

### ISSUE THREAD

**Issue by sambodhi-cn** [ivarptr/yu-writer.site#183]
不知道怎么回事，以前用得好好的，最近报错：
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
SyntaxError: Unexpected token 

[OK]

重新下了新版的也是如此

**Comment by hemashushu** [comment]
@sambodhi-cn 单从这个报错信息我也无法确认是什么原因，或者试试把程序的缓存清理一下再运行：

程序配置和缓存的位置：

Windows 版：
C:\Users\YOURNAME\AppData\Roaming\Yu Writer
C:\Users\YOURNAME\AppData\Local\Yu Writer

mac 版：
/Users/YOURNAME/Library/Application Support/Yu Writer
/Users/YOURNAME/Library/Caches/Yu Writer

**Comment by sambodhi-cn** [comment]
照你的步骤去做之后，问题解决了！谢谢大神，大神就是大·礻申！
