### ISSUE TITLE
插入链接会先报一个错误

### ISSUE THREAD

**Issue by biqiu-ssw** [ivarptr/yu-writer.site#186]
A JavaScrip error occurred in tha main process
Uncaught Exception:
Error:ENOENT;no such file or directory,stat ‘D:\C:\users\xxxxxxx’

应该是路径处理的问题吧，出现了D盘，D盘是软件所在的盘，C盘是md文件所在的盘，把文件放D盘报错是这样的‘D:\D:\xxxxxxx’

**Comment by hemashushu** [comment]
@biqiu-ssw 收到，谢谢你的反馈！

**Comment by hemashushu** [comment]
@biqiu-ssw 新版本 0.5.3 已释出，因为新版本改动很大，这个问题我在测试机里似乎被修复了，欢迎下载试用看看问题是否仍然存在，如有问题欢迎随时问，这个 issue 我先关闭哈。
