### ISSUE TITLE
下一版本什么时候更新

### ISSUE THREAD

**Issue by kuangdazzidd** [ivarptr/yu-writer.site#187]
请问下一版本什么时候更新啊

**Comment by whzecomjm** [comment]
同期待, 很多打星号的(将要实现的)功能看起来都很实用.

**Comment by hemashushu** [comment]
@kuangdazzidd 这个问题问得我两行泪水啊，哈哈哈。今年特别忙，平时空闲时间不是很多，只能说尽量快了 😂

**Comment by kuangdazzidd** [comment]
哈哈，辛苦了辛苦了，只是和大家一样都很期待你的大作！

**Comment by weichen-ink** [comment]
真的是同期待哈哈，经常过来刷一刷有什么新动态

**Comment by cuigh** [comment]
建议小步快走，加快更新速度，这都离上个版本快一年了~

**Comment by hemashushu** [comment]
@cuigh 是的，之前没经验，这次版本后打算分多一条支线：开发版，用于快速发布一些不太稳定但跟得上最新开发进度的小版本。

**Comment by ChaoVer** [comment]
希望下个版本有checkbox功能. 这样就可以做todolist了.

**Comment by hemashushu** [comment]
@ChaoVer 好的，这个功能在下个版本已经加上

**Comment by hemashushu** [comment]
@kuangdazzidd @whzecomjm @jzoy @cuigh @ChaoVer 新版本 0.5.3 已释出，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
