### ISSUE TITLE
问题：是否支持同目录下的文件之间的跳转链接

### ISSUE THREAD

**Issue by serialq7ic4** [ivarptr/yu-writer.site#190]
假设目录结构为：
D1
|_F1
|_F2

F1中是否有链接可以跳向F2中的某一个标题，望解答，谢谢。

**Comment by batkiz** [comment]
可以，读读这个
https://github.com/guodongxiaren/README#%E9%93%BE%E6%8E%A5

**Comment by batkiz** [comment]
比如你在 F2 里有个标题 `## title2`，你在 F1 中可以这么写：
```
[a link](F2## title2)
```
来进行跳转

**Comment by hemashushu** [comment]
@chenq7an 可以的，格式正如 @batkiz 所提到的。不过稍微有点不同的是标题需要进行slugfy处理，如果不知道这个是什么的话，可以简单地点击工具栏的 Link 按钮，然后从中分别选择目标文档和标题。详细的方法在软件的使用手册里也有说明。

**Comment by chenq7an** [comment]
@batkiz @ivarptr 多谢二位，本目录下带锚点的不同文件跳转试出来了，但是如果要写绝对路径的话，还是不行，不知道是不是我写的有问题。library下面目录层级是这样的 A/B/C/a.md和b.md ，我在b.md中链接[xxx](./a#yy)可以跳转过去，但是如果[xxx](/A/B/C/a#yy)这么写就会报错，请问绝对路径该怎么写？
![image](https://user-images.githubusercontent.com/21356580/37692864-7d8c7d34-2cf6-11e8-9b40-ecf8f20cba64.png)

**Comment by serialq7ic4** [comment]
@batkiz @ivarptr 多谢二位指点，已经可以了。

**Comment by hemashushu** [comment]
@chenq7an 新版本 0.5.3 已释出，原先 "插入链接" 有些bug，新版本已修复，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
