### ISSUE TITLE
不支持插入html段落

### ISSUE THREAD

**Issue by heartnn** [ivarptr/yu-writer.site#192]
本身有些时候用markdown是不完美的，所以必须插入html，比如合并单元格的table

**Comment by hemashushu** [comment]
@heartnn 对 HTML 标签的支持会在往后的版本加上。谢谢反馈

**Comment by hemashushu** [comment]
@heartnn 新版本 0.5.3 已释出，html 已经支持（默认关闭，在设置里可打开），欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
