### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by baka-gourd** [ivarptr/yu-writer.site#193]
邮件已发，请查收233

**Comment by baka-gourd** [comment]
虽然可能未来收费后就不用了吧233
现在还是开发版，值得期待

**Comment by baka-gourd** [comment]
经过一番折腾，把C:\Users\usernames\Documents\Yu Writer Libraries里的报错文件路径删掉就好了
希望修复

**Comment by hemashushu** [comment]
@baka-gourd 我回过头来发现已经忘记是什么问题了，新版本 0.5.3 已释出，欢迎下载试用看看问题是否仍然存在，如有问题欢迎随时问，这个 issue 我先关闭哈。
ps 有收费模块，但仍然可以免费使用
