### ISSUE TITLE
最新版本什么时候出？？

### ISSUE THREAD

**Issue by git-life-everywhere** [ivarptr/yu-writer.site#197]
最新版本什么时候出？？

**Comment by hemashushu** [comment]
@li-coolqi 0.5 版所有大模块已经完成了，现在正在整合各个模块，大概五月可以下载内测版

**Comment by lxj198786** [comment]
@ivarptr 期待~！！！现在感觉Yu Writer 在mac和win两个平台上都很舒服，既好看也好用。很期待新版本能增加一些好功能。

**Comment by hemashushu** [comment]
@li-coolqi @lxj198786 新版本 0.5.3 已释出，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
