### ISSUE TITLE
请问什么时候支持html代码呀？

### ISSUE THREAD

**Issue by wjf2016** [ivarptr/yu-writer.site#198]
很多时候需要使用html代码排版，可惜yu-writer不支持，要时能支持html代码就好了。

**Comment by wangmingquan** [comment]
同求支持html，表格里面换行加br都加不了，一大硬伤。

**Comment by hemashushu** [comment]
嗯嗯，大概会在 0.6.x 版加上，谢谢反馈

cc #195

**Comment by hemashushu** [comment]
@wjf2016 @wangmingquan 新版本 0.5.3 已释出，html 已经支持（默认关闭，在设置里可打开），欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
