### ISSUE TITLE
不能设置字体大小（字号），就是反人类

### ISSUE THREAD

**Issue by chillbest** [ivarptr/yu-writer.site#199]
想找一款适合写作的高度浸淫类的PC端软件，试了七八个，你们家是唯一不能设置字体大小的。
因为yu-writer有夜间模式所以入围了，又因为你们是全英文版，所以试了两下就放一边了。——本人英语还可以，当时希望能有一个低学习成本的软件，特别是打着国人制作的，没有这个全英文使用的学习预期。

后面又用，是因为你们的Instand View确实很吊。

然后我在github上看到你们说下个版本有演示功能来回答要求放大字体的用户。我想来回答为什么这个功能很重要：
因为看得清楚和看得舒服，比你们做出一万个功能都重要。
每个人的视力情况都不清楚，比如我有认识的老年人都用顶号字写作，你们没想过吧。
每个人的电脑环境都不一样，我家台式机的显示器就离得比标准距离要远，因为显示器大；我用笔记本的时候就近很多。
有时候我工作累了，就会把字号调大点，因为视力疲劳了。

我再问下，你们就没想过别的文本编辑器100%都有设置字号的选项，就会觉得他们都错了吗？

——当你觉得所有车都在逆行时，可能逆行的总是你。

**Comment by hemashushu** [comment]
@chillbest 如果是编辑框整体文字字体大小设置是有的，菜单“view” -> "zoom in/out" 分别是放大和缩小。或者用快捷键 "ctrl + -/+"
