### ISSUE TITLE
希望有个中文版界面

### ISSUE THREAD

**Issue by chillbest** [ivarptr/yu-writer.site#200]
（理由前面的帖子也都说了，单开一帖是本着一个问题一个贴的思路。防止大帖中的小问题被忽视。）

因为国内宣传是国人做的软件，所以使用的时候会有种预期。
现在年轻人如果有需求下软件，都会下一堆然后选出最好的/最适合自己的，我希望你们不要输在第一眼。

**Comment by hemashushu** [comment]
@chillbest 到正式版会加上中文界面

**Comment by hemashushu** [comment]
@chillbest 新版本 0.5.3 已释出，已有中文界面，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。

ps 之前那个字体大小的 issue 我手快关闭了，这里补充一下，字体改变大小功能一直都是有的，只是名称叫做 zoom in/out，现在叫做 "放大字体"/"缩小字体"，这样应该会容易理解很多。
