### ISSUE TITLE
很长的代码如何限制代码框高度，使超出的部分滚动查看

### ISSUE THREAD

**Issue by serialq7ic4** [ivarptr/yu-writer.site#204]
Win10，v0.44版本，望大佬抽空指教

**Comment by hemashushu** [comment]
@chenq7an 这个功能应该属于“显示”范畴，编辑器因为主要负责文字录入和编辑，所以它不太适宜隐藏部分文字。

**Comment by hemashushu** [comment]
@chenq7an 新版本 0.5.3 已释出，新版本对超宽代码/超宽公式增加了横向滚动条，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
