### ISSUE TITLE
问题：菜单Format有快捷键提示，但是灰色，也不能用快捷键设置文本格式

### ISSUE THREAD

**Issue by lxj198786** [ivarptr/yu-writer.site#205]
你好，我很喜欢你的Yu Writer，既好看也好用。只是发现格式调整必须手动键入字符，而且菜单栏有快捷键提示，但是灰色禁用状态，不能使用。请问现在版本是否不能使用快捷键？？？有快捷键能方便好多。

祝愉快：）

**Comment by hemashushu** [comment]
@lxj198786 0.4.4版还没完成，所以是灰色的。下个版本已经完成这部分，希望到时继续支持，谢谢反馈

**Comment by hemashushu** [comment]
@lxj198786 新版本 0.5.3 已释出，格式菜单全部可用了，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
