### ISSUE TITLE
win10下程序闪退后无法打开了，显示错误

### ISSUE THREAD

**Issue by Boycottangent** [ivarptr/yu-writer.site#206]
# 问题
双击exe，程序无法打开，显示下图错误

![image](https://user-images.githubusercontent.com/23280916/38917339-13ce05ec-431d-11e8-92cf-74f919090c95.png)

# OS版本
win10 1709 Build 16299

**重装没有解决问题**

**Comment by hemashushu** [comment]
@Boycottangent 之前有用户反馈是因为系统安装了Node.js，不知道是不是这个原因。另外这是第一次运行就出现的错误？

**Comment by Boycottangent** [comment]
不是第一次运行的报错，是在程序运行过程中crash了，尝试重新打开时的报错，而且原本正在编辑的md文件内容都没有了（其他编辑器打开是乱码）
系统确实安装了Node，前不久装的，装完后，Yu Writer都还能用

我把AppData里的相关文件夹删了之后，能够运行，目前好像没有问题。但原本正在编辑的那个文件，内容都抹掉了，尝试回滚时也弹窗这个信息，其他文件和功能都没有收到影响

谢谢回复，好软件！
