### ISSUE TITLE
Yu Writer 0.5 版预览截图

### ISSUE THREAD

**Issue by hemashushu** [ivarptr/yu-writer.site#208]
Yu Writer 0.5 版的大模块都完成了，先放一个截图上来。接下来是把各个模块连通，迟些时候再放一个演示视频。

![](https://pbs.twimg.com/media/DbMGmBHUwAAIPUu.jpg:large)

Yu Writer 0.5 版其实是之前提到的 Pro 版，主要变化是：库、文档管理模块和编辑模块，前者采用传统的树形+列表的两列式，后者几乎重写，添加了很多自动辅助编辑功能，当然还完成了本土特有的功能：比如在统计里会显示中文的阅读时间，以及保留格式转换成微信公众号文章格式等等。

from: https://twitter.com/ivarptr/status/987140811778240513

**Comment by LeeGaning** [comment]
期待新版本，希望在Linux能用上

**Comment by hemashushu** [comment]
@LeeGaning 这次妥妥的能用上

**Comment by zt-boom** [comment]
激动……

**Comment by zhaohl1993** [comment]
我擦，这次感觉好完善的样子啊。

**Comment by hemashushu** [comment]
@zhaohl1993 因为之前主要是做技术方面的攻关和探索试验，这个版本开始考虑上实际使用场景

**Comment by MKDJOJO** [comment]
期待大佬的新版本

**Comment by MKDJOJO** [comment]
期待大佬的新版本

**Comment by Lin-Ya** [comment]
支持支持，现在用着除了图床需要自己处理以外其他用着都很舒服，希望未来能实现自定图床

**Comment by qw4096** [comment]
支持支持，希望新版本在输出PDF时能对字体大小这些进行调整

**Comment by tianyu94** [comment]
很期待，加油(ง •_•)ง

**Comment by hemashushu** [comment]
放一段 Yu Writer 0.5 新功能演示视频 －－ part 1/3，新的文档库包括了树型目录、单独的文档列表、智能文件夹（即预设条件快速搜索列表）、可为文档设置置顶、颜色标签、简介、截稿日期等属性；实时显示文档的todo list、包含的图片；快速打开/切换文档等等功能。


https://youtu.be/xRneUDq119A

**Comment by wangzzxx** [comment]
期待！
另外Windows版本对缩放支持有待加强，一些按钮会发虚变形。而且文本貌似没法被mactype渲染

**Comment by gordonpro** [comment]
希望能直接copy+paste图片上去

**Comment by hemashushu** [comment]
新功能演示视频第2段：包括大量自动完成、快捷键、表格编辑、行操作、字数统计、表格一秒变图表、幻灯片播放模式等等。

https://www.youtube.com/watch?v=SHk3x560WlY

**Comment by RonaldinhoL** [comment]
期待更新

**Comment by ArnoFrost** [comment]
期待中,潜心这么久 辛苦了大神

**Comment by yanweijia** [comment]
期待

**Comment by hemashushu** [comment]
4个主题也完成了，这是最后一个模块了。

ps 主题配色其实来自机械键盘外观，是不是很像？ :D

![1](https://user-images.githubusercontent.com/394223/40643592-3c247480-6353-11e8-9c86-85edae0e68a2.jpg)
Carbon

![4](https://user-images.githubusercontent.com/394223/40643593-3c8deffa-6353-11e8-97c2-592f50882cf2.jpg)
Default

![2](https://user-images.githubusercontent.com/394223/40643595-3cf53700-6353-11e8-8e1d-a6c9fee659a4.jpg)
Lime

![3](https://user-images.githubusercontent.com/394223/40643597-3d35a614-6353-11e8-9180-ded5dd843c9d.jpg)
Night

**Comment by LeeGaning** [comment]
最后一个模块，那不是快发布了？ @ivarptr

**Comment by hemashushu** [comment]
@leeganing 是的，大概在六一儿童节

**Comment by qw4096** [comment]
pro是要收费吗

**Comment by vyan13** [comment]
求不要太贵，不要突破两百吼不吼😅

**Comment by RonaldinhoL** [comment]
Windows的什么时候发？

**Comment by vyan13** [comment]
大佬，这个……windows版本什么时候更新？

**Comment by hemashushu** [comment]
大概月底前

**Comment by baka-gourd** [comment]
linux的会做成.deb包还是绿色版
>gayhub上都是人才
