### ISSUE TITLE
所见即所得 & 快捷键输入标题

### ISSUE THREAD

**Issue by Darleey** [ivarptr/yu-writer.site#209]
胃口被 Typora 养叼了~
可以加入类似于 所见即所得 及时渲染功能以及 快捷键快速输入标题 功能。
不一定要实时显现 markdown 源文件，可以在渲染结果中直接编辑，个人体验是这样可以在一定程度上增加输入效率<眼睛左右开工怪累人的>，想要直接就源文件修改再切换到 双栏模式。

**Comment by hemashushu** [comment]
即时渲染是指 Instant View 吗？
快捷键输入标题这个可以有，下版本已加上。

**Comment by Darleey** [comment]
是的，准确地说是直接在 Instant View 模式下编辑，和阅读合二为一(我描述的即时渲染指 在Instant View 模式下输入Markdown 语法标签后，按回车，Yu Writer 将对应文字渲染成相应格式)。如果后期有更改格式的需求，可以点击被语法块渲染的文字，此时语法块出现，用户编辑语法块。
PS.因为 Yu Writer 已经集成了很不错的文档管理模块(Library，非常吼的功能！)，在我的角度，Yu Writer 已经超越了编辑器的界限，开始了向阅读器一路狂奔的节奏。

**Comment by kelsen11** [comment]
支持“所见即所得”功能的开发，@ivarptr可以下载并使用一下typora，写内容的体验很好。

**Comment by kelsen11** [comment]
或者建议作者添加一个可以调用外部编辑器的功能，比如直接调用typora来编写Markdown，然后通过YuWriter来管理/发布。

**Comment by elkan1788** [comment]
Pro 版本的注册费用能否再优惠些呢？哈

另外发现一个问题，就是创建一个Lib导入本地的MD文档后，好像就不同步了，在YuWriter编辑好后并没有同步到源文件当中，难道是我设置的问题？

2018-06-02 10:11 GMT+08:00 kelsen11 <notifications@github.com>:

**Comment by hemashushu** [comment]
@Darleey @kelsen11 新版本 0.5.3 已释出，快捷键也加入了，欢迎下载试用。

至于所见即所得或者在Instant View 模式下编辑，因为实在太大工作量了，因为基本上是两套不同的编辑方式，所以暂时不会实现。

@elkan1788 两人以上可以团购，团购打 6 折，另外每位用户的第二份开始每份授权 ￥35。

这个 issue 我先关闭哈，如有问题欢迎随时问。
