### ISSUE TITLE
Hexo xxxx.resource 不太兼容

### ISSUE THREAD

**Issue by larrykoo711** [ivarptr/yu-writer.site#21]
1. 自动生成的 xxx.resource 文件夹，Hexo（3.2.0）不兼容，该文件夹下面有一个 commit.json 被 hexo 扫描成 post 了，结果每次 save 之后，多出一篇乱码post，效果如下：

![2017-08-22 09 42 22](https://user-images.githubusercontent.com/1057589/29545901-a5efd1a0-8723-11e7-9776-71bb660a9ef2.png)

正确的方式是，自动生成一个与 post 标题相同的文件夹，这也是 hexo 默认支持的方式；
具体体现在 hexo 本身的 yml 配置里面：`post_asset_folder: true`

2. Hexo 图片的插入方式不兼容；

> 由于 Hexo 主题众多，最好的图片插入方式不是使用 markdown 的标准，`![title](URL)`，会出现路径的问题(比如博客放在域名的二级目录下面：`http://github.io/blog/` 这样)；在 hexo-post 里面，最好的兼容方式是使用 `{% asset_img URL Title   %}` 标签来插入图片；或者作者能找到更好的兼容方式；像这样；
```
{% asset_img URL [Title]  %}
```

**Comment by hemashushu** [comment]
@gumutianqi 

1. 记得 xxx.resource 应该会被统一放在 hexo 项目根目录单独的文件夹 yulib.resource 之内的，试试把 hexo 项目根目录的 `yulib.config` 文件删除（假如有的话），然后再此在 yu writer 里选择 “new library" -> "link to Blog project..." 来把它加入到文档库。

2. 这个问题我也发现了，非常感谢你的意见！

**Comment by larrykoo711** [comment]
@ivarptr 

问题1，我在删掉 library 之后重新 link blog，问题解决了，xxx.resource 文件夹现在已经在根目录了，不会在_post目录了
