### ISSUE TITLE
引用本地文件.pptx, .docx, .xlsx, 点击链接时报错，但txt文档可以打开，如下图

### ISSUE THREAD

**Issue by chuanxiaxiao** [ivarptr/yu-writer.site#214]
报错内容和https://github.com/ivarptr/yu-writer.site/issues/206看起来一样
![image](https://user-images.githubusercontent.com/21364935/39227727-ce8fd6d4-488c-11e8-8a0b-610b5bd28768.png)

**Comment by hemashushu** [comment]
这个错误是因为 yu writer 想尝试自己打开目标文件，但因为不支持此类型文档所引起的，已记下这个bug，谢谢反馈

**Comment by hemashushu** [comment]
@chuanxiaxiao 新版本 0.5.3 已释出，当遇到自己不能打开的文件时已经会调用外部程序打开，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。

**Comment by chuanxiaxiao** [comment]
完美👍，我去新版本试一下。




| |
高扬扬
邮箱：chuanxiax@163.com
|

签名由 网易邮箱大师 定制

在2018年09月01日 05:31，Hippo Spark 写道：

@chuanxiaxiao 新版本 0.5.3 已释出，当遇到自己不能打开的文件时已经会调用外部程序打开，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
