### ISSUE TITLE
快捷键 标题、目录切换

### ISSUE THREAD

**Issue by Darleey** [ivarptr/yu-writer.site#215]
鼠标 + 键盘 操作很便利，但纯键盘操作有时候会更便利呀 ψ(｀∇´)ψ

1. Library 区目录切换的时候，可以设置右键进入下一级目录功能，左键返回上一级目录，Enter 键打开文件，Ctrl + Alt + F 目录搜索

2. 标题切换，如果打开了多个文件，就会产生标题间切换的需求，Ctrl + Tab 以及 Ctrl + Shift + Tab 这个时候就有很用了。

**Comment by hemashushu** [comment]
1. 因为 0.5 版已更改为树形，所以操作有些许不同，你的建议很好，我尽量设计让它可以接受纯键盘操作。
2. 标题切换是指 “标签页” 切换（已打开的多个文档间的切换）吗？这个切换是有快捷键的，在菜单 “Window" 下面有标识。
谢谢你的意见！

**Comment by Darleey** [comment]
@ivarptr    逮着一只八哥(。・∀・)ノ，Windows 系统下，`Ctrl + Tab` 只能实现插入空格 `	` 的功能

**Comment by hemashushu** [comment]
@Darleey 新版本 0.5.3 已释出，`Ctrl + Tab` 这个 bug 已经修复了，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
