### ISSUE TITLE
关于 Library 搜索

### ISSUE THREAD

**Issue by Darleey** [ivarptr/yu-writer.site#217]
Library 全文搜索功能太棒了，然而很多时候只有搜索目录的需求，而且这个时候界面就会很卡顿！(/_;)

方案一：可以加一个判断，默认选项为目录、标签 搜索，并在搜索结果尾部加入一行类似于 “对搜索结果不满意？试试全文搜索”的提示。用户选择相应选项后切换搜索方法，但缺乏灵活性(什么时候切换回来？)。

方案二：在用户聚焦到搜索框进行搜索的时候，搜索框UI切换到扩展状态(默认是收起状态)，在多出来的扩展部分中增加 目录(默认选中)、标签、全文 几个多选框。完了同样在目录、标签搜索的结果列表末尾显示 “对搜索结果不满意？试试全文搜索” 的提示。在全文搜索的头部增加"结果冗余，试试更简洁的目录搜索"的提示 ······

**Comment by hemashushu** [comment]
“搜索目录” 是指 “只搜索指定（当前）目录之内（包含子目录）的文档” 的意思吗？现在的全文搜索是可以 “全部库一起搜索” （当触发搜索时假如 library 面板返回到最上层）以及 “只搜索当前库” ，确实还没考虑到只搜索当前目录的情况。

**Comment by Darleey** [comment]
@ivarptr 不是，仅指搜索 目录(库)中文档的文档名 的意思，范围不限，全部库一起搜肯定是最吼的。

我想描述的是这样一种场景：
有时候仅仅是想找一个文档(能够记得局部或全部文件名的那种)，但全文搜索会把文档内部的内容也遍历一遍，会有不小的延滞。

**Comment by hemashushu** [comment]
@Darleey 0.5 版增加了快速打开功能，就是仅搜索文件名的，速度超快，欢迎下载试用。另外，0.5 版因为界面还没做好的原因，全文搜索功能暂时屏蔽了，等到 0.6 会再次打开。如有问题欢迎随时问，这个 issue 我先关闭哈。
