### ISSUE TITLE
关于程序的关闭

### ISSUE THREAD

**Issue by batkiz** [ivarptr/yu-writer.site#218]
当我需要关闭程序时，我比较喜欢直接将鼠标“甩”到屏幕右上角，然后关闭。
但 Yu writer 最右上似乎并不是关闭按键。如下图
![yuwriter.gif](https://i.loli.net/2018/04/26/5ae15e1ff0553.gif)
希望修复一下

**Comment by hemashushu** [comment]
@batkiz OK，谢谢你的反馈！
