### ISSUE TITLE
是用什么语言写的？开源吗？

### ISSUE THREAD

**Issue by a523** [ivarptr/yu-writer.site#219]
是用什么语言写的？开源吗？ 感觉很nice

**Comment by myd7349** [comment]
官网 [about](https://ivarptr.github.io/yu-writer.site/about.html) 有介绍：
>从 HTML5、ES6 开始学起，到 SASS 到 Node.js 到 NPM 再到 Electron， 边学边写，所以陆陆续续 Yu Writer 写了近一年多。
