### ISSUE TITLE
移动版的有计划推出不呢？

### ISSUE THREAD

**Issue by 471448446** [ivarptr/yu-writer.site#220]
后续会推出移动版么。
收费都可以
用起来很赞

**Comment by hemashushu** [comment]
@471448446 原本是有想过写完桌面版再写个 ipad 版，只是现在时间（本软件于空闲时间写）不太够用，所以都不知道什么时候才能开始写，哈哈哈

**Comment by 471448446** [comment]
@ivarptr  了解，

**Comment by ddkk3000** [comment]
我觉得作者应该不会写了，我还在翘首期盼win版呢。

移动端有个叫“易码”的软件不错，你可以看看。移动端你要那么多功能干嘛

**Comment by 471448446** [comment]
好的 @ddkk3000
