### ISSUE TITLE
文件夹选择onedrive同步文件夹报错

### ISSUE THREAD

**Issue by Ergouf** [ivarptr/yu-writer.site#221]
![default](https://user-images.githubusercontent.com/14170419/39478178-3b181116-4d94-11e8-9d39-677257a21219.PNG)

**Comment by troywmz** [comment]
我的也是，icloud就没问题，应该不是C盘权限的锅

**Comment by baka-gourd** [comment]
啦，我已经反馈过了

**Comment by OvO7000** [comment]
关闭 OneDrive 的 file on demand应该就可以了 # 95

**Comment by OvO7000** [comment]
关闭 OneDrive 的 file on demand应该就可以了 #95

**Comment by hemashushu** [comment]
@Ergouf @troywmz @baka-gourd @OvO7000 新版本 0.5.3 已释出，已经修复了这个bug，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
