### ISSUE TITLE
亟需字数统计功能~~

### ISSUE THREAD

**Issue by wsyzzz** [ivarptr/yu-writer.site#222]
像word一样在下面加个状态栏，可以显示字数统计和页数，感谢制作组~~

**Comment by hemashushu** [comment]
@wsyzzz 0.5 版已加入，谢谢反馈

**Comment by wsyzzz** [comment]
@ivarptr 谢谢回复~~请问0.5预计什么时候发布呢？我看官网现在还是0.4.4beta~

**Comment by hemashushu** [comment]
六一节时

Young Yang <notifications@github.com> 于 2018年5月7日周一 上午10:13写道：
