### ISSUE TITLE
小于3个字符的公式Markdown代码高亮错误

### ISSUE THREAD

**Issue by houruomu** [ivarptr/yu-writer.site#223]
例句：
Suppose $B$ is not open, then let $A = f^{-1}B$
这整句话从第一个\$开始到结尾都会在编辑器中被代码高亮。

**Comment by hemashushu** [comment]
@houruomu 谢谢报告bug！

**Comment by ghost** [comment]
@ivarptr 老哥，win 0.5.2 依然存在这个bug 
![default](https://user-images.githubusercontent.com/34027391/42629370-acc46216-8605-11e8-9c31-0c15e96d3f61.png) 修复下 🙄

**Comment by hemashushu** [comment]
@yurjane 晕倒，修复了忘记合并到这个版本了，哈哈哈。下次更新一定搞定

**Comment by 777Arch** [comment]
发现同样的问题，已经有人提交 BUG 了，好快。

**Comment by hemashushu** [comment]
@houruomu @yurjane @Mlearn 新版本 0.5.3 已释出，已经修复了这个bug，这个 bug 实际上是因为之前默认打开了单美元符号的数学公式的功能造成的，新版本默认不允许单美元符号，因为它误撞率太高了。欢迎下载新版本试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
