### ISSUE TITLE
读取Hexo的时候，识别不了_posts文件中的以数字开头的md文件

### ISSUE THREAD

**Issue by bazingagain** [ivarptr/yu-writer.site#227]
识别不了_post文件夹下，以数字开头的文件，例如“20180410-java.md”，使用yu-writter没有显示出来 @ivarptr

**Comment by hemashushu** [comment]
@bazingagain 可能是因为FrontMatter有不完整的字段引起的，0.5 版已修复，请再试试

**Comment by hemashushu** [comment]
@bazingagain 新版本 0.5.3 已释出，已经解决了这个问题（是由于文档的 front matter 存在空值字段引起的），欢迎下载试用看看问题是否依旧，如有问题欢迎随时问，这个 issue 我先关闭哈。
