### ISSUE TITLE
win10 64位系统 打开失败

### ISSUE THREAD

**Issue by woniuxia** [ivarptr/yu-writer.site#228]
开启后就一直最小化。
就是没法打开主窗口。
需要提供一些什么信息吗？

**Comment by hemashushu** [comment]
@woniuxia 抱歉回复晚了，估计是某次最小化时程序退出了，然后它就记住那次的窗口大小了，试试手动删除程序的配置文件
`C:\Users\YOUR_NAME\AppData\Roaming\Yu Writer\config`

整个文件夹删掉再重启软件。

**Comment by woniuxia** [comment]
十分感谢！已经解决。
