### ISSUE TITLE
希望加入中文语言支持

### ISSUE THREAD

**Issue by Jack-ban** [ivarptr/yu-writer.site#23]
不得不说，作者很用国际化眼光啊！一出来居然是原生英文版的。虽然我四级已过，平常读读英文文档不成问题，但看着英文终归有些别扭。希望作者能考虑加个中文语言。不过我不急，你可以看着正式版出了再说。
另外，这款软件粗略用下来是我windows平台上目前用过的最好的笔记管理软件（支持markdown）。实际使用不知道对markdown的支持怎么样？至少目前的功能也好，软件界面也好，要不是我现在没做程序员，我都要拜师了。
不知道作者有没有兴趣之后转成付费模式。我不是有钱人，也没必要犯贱非要付钱的样子。我是从软件生命周期的角度考虑。毕竟你的功能如此完善，后期维护升级会是一个大工程啊！我怕你免费久了没动力。付费的话我也能尽自己的一点绵薄之力。毕竟刚刚结束蚂蚁笔记的试用期，感觉它有些功能还是不够完善，反馈良久又不见回复或者更新，要我付费我还是蛮担心后续服务问题的。
就你能实现笔记搜索和笔记内容高亮定位搜索，这就比蚂蚁笔记更得我心。其实我在反馈中就写了，蚂蚁笔记要是能实现内容高亮搜索，我就会付费支持的。可是到现在毫无音讯。正如一个用户说的，笔记最重要的就是回顾查看，如果搜索无法定位到内容本身，那么就失去了搜索功能的意义。
所以，如果你有这个收费计划，和蚂蚁笔记一样的价位是我完全可以接受的。当然前提是你能保证至少把现有的功能完善到没有明显bug。
不知道你是什么打算，欢迎回复。

**Comment by hemashushu** [comment]
@Jack-ban 非常感谢你的鼓励和支持！

现在这个编辑器我是在闲时来开发的，因为不是专业从事软件开发，也有其他途径维生，后续的开发没太大问题，只是开发进度可能会慢一些。当然如果能从中获得些许收入那当然是锦上添花啦，哈哈。现在预想是在完成正式版后会有一个收费的 pro 版，算是体验一下软件开发的完整环节和乐趣吧。

至于界面的语言问题，完全是因为现阶段是 beta 版，[还没做到多语言模块](https://github.com/ivarptr/yu-writer.site/issues/11) 导致的，哈哈哈。

再次感谢你的鼓励！

**Comment by Jack-ban** [comment]
你这个人怎么这样，还说不是专门从事软件开发的。那还这么厉害，你让我这种曾经的“专业人员”怎么办？不要劝我，我要去哭一会儿。
我跟你讲，你最好给我把着项目坚持下去。不然，我就。。。。就把你的代码download下来自己维护。然后删除你所有署名痕迹，气死你。
我就问你怕不怕，哈哈哈。。。。（气有点不够用，自己脑补一下持续一分钟的笑声）@ivarptr

**Comment by hemashushu** [comment]
@Jack-ban 0.5.3 已经完成多语言模块，已经有中文界面了，欢迎下载试用，如果有问题欢迎随时反馈，这个 issue 我先关闭咯。
