### ISSUE TITLE
真心希望能早点用上 [TOC] 功能

### ISSUE THREAD

**Issue by Zhyolo** [ivarptr/yu-writer.site#231]
首先要感谢作者给我们带来了这样一款优秀的markdown编辑器
真心希望能早点用上 [TOC] 功能

还有问下新版大概什么时候能用上啊？

**Comment by Ancientwood** [comment]
_转达作者意思，_ 儿童节礼物🎁 _（伸手_  _跳票是不可能的_

**Comment by cliope** [comment]
其实目录功能是实现了的，不过语法不太一样，要写成 [[TOC]]

**Comment by Ancientwood** [comment]
不过之前版本目录在`READ MODE`可以点击，导出PDF就无有链接了

**Comment by Zhyolo** [comment]
嗯嗯 现在先用的其他编辑器导出PDF

**Comment by hemashushu** [comment]
哈哈，我先记下，0.4.4 的目录标签是 [[toc]]，到 0.5 版（六一后释出）会有清晰的菜单插入目录标签。

**Comment by tx5655** [comment]
0.4.4 版的[[toc]]语法貌似只能显示到 ### 号，再多就不显示了

**Comment by hemashushu** [comment]
嗯，下一版已加上自定义显示层级

**Comment by hemashushu** [comment]
@AlexYong305 @Ancientwood @aglaea 0.5.3 版已更新，使用较为统一的 `@toc` 标签来表示生成目录。
@tx5655 现在可以自定义显示的层级了，在文档的开头加上 front matter，下面是一个例子：

```
---
toc level: 2-4
---
# 演示文章标题1

以下是正文开始。。。
```

其中的 `2-4` 表示生成 2 到 4 级标题的目录。默认值是 `1-3`。

欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
