### ISSUE TITLE
[[TOC]]功能翻译和预览错误

### ISSUE THREAD

**Issue by zhang-wenjun** [ivarptr/yu-writer.site#232]
使用[[TOC]]时，在目录后多出一个"C]]"，以及编辑预览同步滚动时，不会跳过目录，导致后面同步错位

**Comment by hemashushu** [comment]
@zhang-wenjun Ok，已记下，谢谢反馈！

**Comment by hemashushu** [comment]
此问题请见 https://github.com/ivarptr/yu-writer.site/issues/231 
如有问题欢迎随时问，这个 issue 我先关闭哈。
