### ISSUE TITLE
关于复制粘贴的问题

### ISSUE THREAD

**Issue by vyan13** [ivarptr/yu-writer.site#236]
有时在外复制了文字，无法用ctrlv快捷键复制进来，必须鼠标或者触摸板操作，右键粘贴才可以，不知何故。

windows10

**Comment by hemashushu** [comment]
好像是有时编辑器没获取得焦点，就是说点窗口标题栏时，焦点跑掉了。（我还在找原因

**Comment by hemashushu** [comment]
0.5.3 已经解决了这个问题，看看问题是否依旧，这个 issue 我先关闭哈。

**Comment by xushaozhi** [comment]
0.5.3，Win7，截图后，不能通过Ctrl+V粘贴上，没反应，右键也没有粘贴的选项。
Typora不存在这个问题，能很好的识别截图，并能实时预览。
这个问题reopen吧，请解决，谢谢。

**Comment by xushaozhi** [comment]
另外，点击插入图片，选择“从剪贴板粘贴*”，没有反应。
是不是只支持插入本地的图片，这个功能没打开？
0.5.3，Win7。

**Comment by hemashushu** [comment]
@xushaozhi 是的，直接粘贴图片的功能还没完成，预计在 0.6.1 版会完成，PS 目前软件中标有星号（*）的地方都是属于尚未完成的功能
