### ISSUE TITLE
Preview 功能无法通过快捷键返回

### ISSUE THREAD

**Issue by ChangLiuXYZ** [ivarptr/yu-writer.site#239]
Yu writer 0.5 beta 版本，macOS 10.13.4
1. 使用 `command` + `Shift` + `R` 进入 preview 模式；
2. 此时无法通过 `command` + `Shift` + `R` 退出 preview 模式；
3. 鼠标单击 preview 区域后，此时可以通过 `command` + `Shift` + `R` 退出 preview 模式；

**Comment by hemashushu** [comment]
@ChangLiuXYZ 是诶！！很奇怪暂时没找到原因，其他本该能用的也都用不了，但 `ESC` 键还能用。

**Comment by hemashushu** [comment]
@ChangLiuXYZ 好了好了，0.5.1 版修好了（原来键盘的 keydown 事件被一段代码吞掉了）谢谢反馈！
