### ISSUE TITLE
崩溃bug

### ISSUE THREAD

**Issue by MeteorsHub** [ivarptr/yu-writer.site#24]
我承认用了cleanmymac做了一下系统清洁，然而软件崩溃循环跳错，类似这样的：
Uncaught Exception:
TypeError: Cannot read property 'webContents' of null
    at l.sendByWindow (/Applications/Yu Writer.app/Contents/Resources/app.asar/src/script/mainprocess.js:1:23390)
    at k.doOpenFile (/Applications/Yu Writer.app/Contents/Resources/app.asar/src/script/mainprocess.js:1:64380)

没有退出程序重建缓存之类的环节吗

**Comment by hemashushu** [comment]
@MeteorKepler 

看错误似乎是应用程序框架的部分缓存被清除而另外一部分没有清除导致，尝试手动删除自家目录里面的这两个文件夹：

1. /Users/XXX/Library/Caches/Yu Writer
2. /Users/XXX/Library/Application Support/Yu Writer

其中的 XXX 为你登录系统的用户名

**Comment by MeteorsHub** [comment]
之前已经重装了，提这个issue的话主要还是提个重建缓存的鲁棒性建议哈哈哈

**Comment by MeteorsHub** [comment]
另外催更催更

**Comment by hemashushu** [comment]
@MeteorKepler 0.5.3 版理论上已经修复了这类 bug，欢迎下载试用，如果有问题欢迎随时反馈，这个 issue 我先关闭哈。
