### ISSUE TITLE
使用快捷键后换行问题 BUG

### ISSUE THREAD

**Issue by Dan-Sylvain** [ivarptr/yu-writer.site#242]
重现: 按下 command+B(其他该类型快捷键也行), 随意输入(这里我输入一个字母a), 然后回车, 光标跳到"a**"的后面(能做到这里我很高兴), 然后再次按回车想要换行, 结果没有任何反应.

**Comment by hemashushu** [comment]
@Dan-Sylvain 已收到，这是自动完成模块的一个BUG，就是如果在行尾它判断错了，过几天释出个小修正版，目前解决方法是用 Shift+Enter 忽略自动完成。

**Comment by hemashushu** [comment]
@Dan-Sylvain 0.5.1 已经修复，现已提供下载，谢谢反馈！
