### ISSUE TITLE
请问什么时候出windows版本呀？要不作者弄个收费QQ群或者别的什么的群吧？

### ISSUE THREAD

**Issue by ddkk3000** [ivarptr/yu-writer.site#243]
。。。怎么感觉win又被抛弃了

**Comment by Ancientwood** [comment]
作者有 *胶片随便听听* 的 [Telegram](https://t.me/casualvinyl) 听转录黑胶的  _<i>(死</i>_  群

**Comment by ddkk3000** [comment]
暗号多少

**Comment by ddkk3000** [comment]
![_20180604111147](https://user-images.githubusercontent.com/10786234/40896531-17032716-67e8-11e8-93a6-9453cd8b16c3.png)
是这个厉害东西吗？你们怎么会有暗号的。

**Comment by hemashushu** [comment]
@ddkk3000 哈哈哈，因为最近时间很紧张，一次过发两个平台怕太多bug就应付不过来，不过目前还好，没法发现太大的bug，过几天修复一下之后就开始打包Win版，月底前能放出

**Comment by ddkk3000** [comment]
月底你的mac都出0.60了吧??

你这是在推销mac
________________________________

**Comment by hemashushu** [comment]
我是用 linux 的呀，没有安利 linux 已经很良心了😂😂😂

（利用闲时时间写软件没想象那么轻松，我还有正事要做呀

**Comment by ddkk3000** [comment]
原来你自己。。。用的也没发布呀。。。

________________________________

发件人： Hippo Spark<mailto:notifications@github.com>
发送时间： 2018-06-05 14:07
收件人： ivarptr/yu-writer.site<mailto:yu-writer.site@noreply.github.com>
抄送： ddkk3000<mailto:lixiaozhe@live.com>; Mention<mailto:mention@noreply.github.com>
主题： Re: [ivarptr/yu-writer.site] 请问什么时候出windows版本呀？要不作者弄个收费QQ群或者别的什么的群吧？ (#243)
我是用 linux 的呀，没有安利 linux 已经很良心了????????????

（利用闲时时间写软件没想象那么轻松，我还有正事要做呀

**Comment by ddkk3000** [comment]
眨眼出到0.5.1了。。还没有win啊

**Comment by hemashushu** [comment]
@ddkk3000 有关开发进度的问题欢迎关注我的推特 [@ivarptr](https://twitter.com/ivarptr)  全部都在那里说了

**Comment by ddkk3000** [comment]
好吧，感谢

________________________________

发件人： Hippo Spark<mailto:notifications@github.com>
发送时间： 2018-06-12 15:12
收件人： ivarptr/yu-writer.site<mailto:yu-writer.site@noreply.github.com>
抄送： ddkk3000<mailto:lixiaozhe@live.com>; Mention<mailto:mention@noreply.github.com>
主题： Re: [ivarptr/yu-writer.site] 请问什么时候出windows版本呀？要不作者弄个收费QQ群或者别的什么的群吧？ (#243)

@ddkk3000<https://github.com/ddkk3000> 有关开发进度的问题欢迎关注我的推特 @ivarptr<https://twitter.com/ivarptr> 全部都在那里说了

**Comment by ddkk3000** [comment]
其实我想知道作者为何把以前碉堡了的主页介绍给删除了，这样我都不好跟人介绍yu writer了。

________________________________

发件人： lixiaozhe@live.com<mailto:lixiaozhe@live.com>
发送时间： 2018-06-12 15:14
收件人： ivarptr/yu-writer.site<mailto:reply@reply.github.com>
主题： Re: Re: [ivarptr/yu-writer.site] 请问什么时候出windows版本呀？要不作者弄个收费QQ群或者别的什么的群吧？ (#243)
好吧，感谢

________________________________

发件人： Hippo Spark<mailto:notifications@github.com>
发送时间： 2018-06-12 15:12
收件人： ivarptr/yu-writer.site<mailto:yu-writer.site@noreply.github.com>
抄送： ddkk3000<mailto:lixiaozhe@live.com>; Mention<mailto:mention@noreply.github.com>
主题： Re: [ivarptr/yu-writer.site] 请问什么时候出windows版本呀？要不作者弄个收费QQ群或者别的什么的群吧？ (#243)

@ddkk3000<https://github.com/ddkk3000> 有关开发进度的问题欢迎关注我的推特 @ivarptr<https://twitter.com/ivarptr> 全部都在那里说了
