### ISSUE TITLE
关于编辑功能的建议

### ISSUE THREAD

**Issue by vyan13** [ivarptr/yu-writer.site#244]
既然markdown语法中以空行来代替换段，而一般人平常使用中按下enter也就是想要换段，所以能否设定成，或者说给出选择，允许读者设定，enter键直接跳到下下行？
当然，现在的这种也还是需要的，但这种enter不换段的设定在文本编辑中应该是比较少的吧，或许可以使用户在需要到这种功能时手动退一行，或者通过更改相关设定来实现。

windows

**Comment by hemashushu** [comment]
@vuyzan 明白，就是说如果正在录入普通的段落文字的话，遇到用户按 `Enter` 键，就自动插多一行空行是吗？
不过单换行不加空行也是有作用的，实质上它是输出 <br> 标签，相当于一个段落内的换行（即换行但不新建段落），而空一行则是输出<p> 表示段落。因为 markdown 跟 html 有很紧密的关系，其实还不太好修改这种默认行为。不过留有设置让用户自行设置是可以考虑。

**Comment by hemashushu** [comment]
现在 0.5.3 倒是加上了 `Ctrl+Enter` or `Command+Enter` 无论光标是否在行的末尾，都能跳到下一行的功能。
