### ISSUE TITLE
Beautify Document 功能会打乱 YAML header

### ISSUE THREAD

**Issue by AlexZHENGH** [ivarptr/yu-writer.site#247]
如果有使用 YAML header（比如添加 note），使用 Beautify Document 会打乱结构。

以下为例子：

使用前：

<img width="713" alt="screen shot 2018-06-05 at 11 37 06 am" src="https://user-images.githubusercontent.com/7163285/40971327-2c18ff2c-68b5-11e8-98e8-3ed1fd5e4774.png">

使用后：

<img width="700" alt="screen shot 2018-06-05 at 11 37 18 am" src="https://user-images.githubusercontent.com/7163285/40971335-3384437a-68b5-11e8-9c01-c0f1979518ba.png">

**Comment by hemashushu** [comment]
@AlexZHENGH 收到，谢谢反馈！

**Comment by hemashushu** [comment]
@AlexZHENGH 0.5.1 已修复。
