### ISSUE TITLE
pro 版本 [[TOC]] 功能失效

### ISSUE THREAD

**Issue by yanweijia** [ivarptr/yu-writer.site#248]
**pro 版本无法使用 TOC 功能**

如下图:

![image](https://user-images.githubusercontent.com/8547395/41017485-9b477a9a-6987-11e8-9909-01ea9df208fb.png)

**Comment by hemashushu** [comment]
@yanweijia 为了统一自定义标签，非（common mark）标准的现在都用 `指令` 来代替了，其中目录使用 `@toc` 指令，即单独一行写上 `@toc` 即可，比如

```
@toc
```
不过要注意上下各需留一行空行，另外可以通过指令参数或者 Front Matter 来指定目录的层级，比如

```
---
toc level: 2-3
---
```

或者 

```
@toc(level: 2-3)
```
（上面这种还没完成暂时用不了）

来指定只产生第2到第3级的标题（默认是 1-3），本来把这些准备写进 manual 的，由于时间关系还没写完 😄

**Comment by yanweijia** [comment]
@ivarptr 好的👌
