### ISSUE TITLE
两点小建议，烦请查看

### ISSUE THREAD

**Issue by AIHIIH** [ivarptr/yu-writer.site#249]
建议1：
建议增加选中文字后，输入Markdown语言标记符时，可直接在选中文字两侧添加对应标识符的功能。

例如，当用户输入“今天上海好热啊”之后，希望加粗强调一下“上海”。这时可以通过：
a 选中“上海”两个字；
b 输入加粗符号“ ** ”；
c 自动将“上海”改为“ ** 上海 ** ”，而非现在用“ ** ”替换了“上海”两字，导致句子变为“今天 ** 好热啊”

这种行为比较符合一般用户在word中的使用习惯（选中内容，指定操作，给出预期反馈）。也可在设置中加入该功能的开关。

建议2：
建议在使用引导文档中增加一篇针对Markdown语法介绍的文档，方便对Markdown还不太熟练的用户能够在遗忘语法时进行查找。

**Comment by hemashushu** [comment]
1. 当前是支持先选中文字然后用快捷键 cmd+b 让它套上双星号。至于通过输入两个星号这种方式我考虑一下。
2. 目前还在书写中，以后会放入 manual 库里头。
谢谢你的意见！

**Comment by vyan13** [comment]
这样的话，岂不就是经典的快捷键方式了，既然如此，不如直接用快捷键好了。
说到底，markdown语言本身还是有缺陷的，当你在写一篇文的时候的确是刷刷刷只管往下好了，但修改的时候可能就不太方便了，比如ctrl+3，二键即可设定三级标题，但#的话就要###空格，要按四下，在这时效率就不行了。
所以，能否支持markdown和经典的快捷键两套系统，二者毕竟各有优点。
楼主所说的似乎也仍有缺点，比如真的想插进去两个星号的话，就不太妙了。
快捷键和markdown语言是两种思路，强行混合可能会带来混乱吧。比如你加粗可以了，那其他呢，斜体之类的，是否也要依据同样的思路再二次设定一遍，似乎增加了学习成本？

**Comment by vyan13** [comment]
大佬，能否加一个校对功能，发现一些简单的语法错误？@ivarptr

**Comment by hemashushu** [comment]
@vuyzan 因为我自己书写 md 很长时间，大致总结出个小经验想分享一下，当然可能每个人的习惯不同，所以可暂作听听：

提高 md 写作效率，

1. 行文过程直接使用 md 符号；
2. 修改过程使用快捷键。

我解释一下：

## 1
在行文过程中，比如要写几个粗体或者 inline code，直接敲两个星号，或者直接敲反引号即可。虽然使用 Cmd+B 或者 Cmd+Alt+C 也可以让编辑器自动插入 4 个星号或者两个反引号，但有时这样会打乱思路。最流畅的就是一气呵成直接输入 md 符号，当然熟悉了快捷键也是很流畅的，毕竟少输入很多字符，加上 yu writer 支持在格式文本里直接按 Enter 就跳出格式区域，所以实质上这两种方式相差无几。

当然有些操作因为编辑器的自动完成辅助，根本不需要输入符号，比如把普通段落变成标题，直接 `Alt+Enter`即可。

## 2
在修改过程，如果是要修改行内格式，比如粗体，如果是忘记加粗，那么必定是要先选中文字，然后再：
* 按 Shift+8，即星号（楼主提到的方式）
* 使用快捷键 Cmd+B
在我看来这两种方式并没有什么太大区别，按数字8虽然符号行文过程的习惯，但有更高的出错几率（可能是个人问题，我按数字一行有时会按错键），而且有时作者就是想明确输入星号呢？

如果是取消加粗，那么快捷键就方便多了，只需把光标移动到加粗文字的中间任何位置，再按 Cmd+B就取消了。比起逐个星号删除快很多。

同理，普通段落变成标题，只需把光标放到这样的任意位置，直接 `Cmd+1,2,3,4` 即可，连选中都不需要。或者使用 `Tab` 和 `Shift+Tab` 来增加或减少级别。 

所以我的经验是，适当使用快捷键是有必要的，快捷键跟直接符号输入可以相辅相成。

---

当然楼主提到的方式我也思考过，也的确有道理的地方，比如同样都是 * 号既可直接录入，也可以当作某种“快捷键”来修改既有的文字。我想大概在完成正式版后，会增加插件模块，到时可以把各种个性化的功能做成插件，或者有开发者来扩充，这样就可以满足各种个性化要求了。

**Comment by hemashushu** [comment]
@vuyzan 
哪？
> 大佬，能否加一个校对功能，发现一些简单的语法错误？

**Comment by hemashushu** [comment]
@AIHIIH 新版本 0.5.3 已释出，已经加上使用 `*`, `_`, `+` 等符号直接给选定文字设置相应格式的功能，因为我发现这个功能跟正常的编辑没什么冲突，于是默认是打开的，可以在设置里关闭。欢迎下载试用，再次谢谢你的建议，如有问题欢迎随时问，这个 issue 我先关闭哈。
