### ISSUE TITLE
请问有计划开源吗？

### ISSUE THREAD

**Issue by mickmetalholic** [ivarptr/yu-writer.site#253]

**Comment by hemashushu** [comment]
@mickmetalholic 现在还没有开源的计划，因为这个项目的代码量还是挺大的，目前一个人有时（生活）事情忙起来还可以慢悠慢悠地在半夜时填坑，而多人的话要组织、沟通和协同需要很多精力，等以后大致完成或定型之后可能会有部分（组件）开源或者有服务端之后会开源服务端，总之现在还没有头绪。
