### ISSUE TITLE
全选会高亮 UI 元素内的文本标签

### ISSUE THREAD

**Issue by AlexZHENGH** [ivarptr/yu-writer.site#255]
当 focus 的元素不在编辑器以内的（比如点击 Quick Access Bar 或者 instant view），按 Command + A 会全选界面的所有文本标签。

![image](https://user-images.githubusercontent.com/7163285/41191131-d3467484-6be2-11e8-9b14-623fbd212a66.png)

不影响使用哈，就是感觉有点不原生（因为其他部分做的很精致了，几乎看不出是 Electron 了）。

谢谢！

**Comment by hemashushu** [comment]
@AlexZHENGH 哈哈，这点我也很纠结，Electron 是有可以设置元素为不可选的 css 属性值，但设置之后又会产生 bug：点击并拖动这些元素时，会导致编辑框的文字被选中。因为后者影响更大，所以干脆先暂时不理它了。

**Comment by AlexZHENGH** [comment]
好哒，谢谢！

我刚看到 Electron 的一个 [issue](https://github.com/electron/electron/issues/2538)，里面除了直接设置 `user-select: none;` 外好像还有讨论在不是 `input` 或 `textarea` 的情况下把 select 关掉的 css 设置，不知道能不能解决选中编辑框文字的问题。

我不懂 Electron 哈，我感觉有可能是这个意思，供你参考。

**Comment by hemashushu** [comment]
@AlexZHENGH 是的，不设置 `-webkit-user-select: none;` 就会让用户有机会选中 UI 上的文字，但设置了这个属性之后则会导致编辑框内的文本被错误选中的BUG。
不过我现在解决了，通过捕捉非可选区域的 mousedown 事件并把它取消掉，这样就防止用户选中文字了 ✌️

**Comment by AlexZHENGH** [comment]
💡好办法！

**Comment by hemashushu** [comment]
@AlexZHENGH 新版本 0.5.3 已释出，已经解决了这个问题，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
