### ISSUE TITLE
第三方博客管理

### ISSUE THREAD

**Issue by lzm-cn** [ivarptr/yu-writer.site#258]
作者你好，是否有考虑把YuWriter加入博客管理的功能？类似于Windows Live Writer，能够直接管理博客园、CSDN等第三方博客的账号，在本地编辑后直接发布到第三方博客~

**Comment by hemashushu** [comment]
@lzm-cn 最开始时是准备加入这个功能的，然后中途发现里边的工作量非常大，特别是要考虑到双向同步以及跟本地文档库结合等，所以把这个功能先排在后面，如果在完成正式版还有精力会考虑加上（但正式版还是很遥远的事情啊😅)

**Comment by lzm-cn** [comment]
辛苦了！！非常感谢作者贡献这么好用的软件。界面非常漂亮，是用electron开发的吗？

**Comment by hemashushu** [comment]
@lzm-cn 是的，是基于 electron 写的。新版本 0.5.3 已释出，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
