### ISSUE TITLE
Document List的小问题

### ISSUE THREAD

**Issue by ypl6** [ivarptr/yu-writer.site#259]
作者你好！

Document List里，纯文字标题显示正常：
![folder](https://user-images.githubusercontent.com/24860299/41272228-d74748ea-6e46-11e8-98f8-fe69b26ebebd.jpg)

包含emoji的资料夹标题则会出现错位。
预设的白色主题下比较明显，其他三个主题下看不太出来。
![folder_emoji](https://user-images.githubusercontent.com/24860299/41272231-d978696e-6e46-11e8-96e3-1012f335c998.jpg)

不影响使用，不过还是有点困扰。烦请考虑下修复，谢谢！

另，请问未来有上架MAS的打算吗？正式版推出中文介面后，会考虑支持繁体中文吗？

**Comment by hemashushu** [comment]
@panlyp 很细致哈哈哈，谢谢反馈！下次发布的版本会修复它。大概到正式版（即大部分功能做完后）会尝试上架MAS，但因为要做的模块实在太多，所以还是很遥远的事情 😅。下个版本会加入 i18n，繁体中文当然支持了。

**Comment by ypl6** [comment]
新版本更精致了，用得很开心哈哈哈哈，现在更期待正式版本了。感谢作者！

这次还是同样的问题。

任务列表的完成度会把长标题压下去，只剩一行：
<img width="197" alt="" src="https://user-images.githubusercontent.com/24860299/42773882-a46f0f52-8962-11e8-9e3a-6193eefa6f36.png">

没有任务列表，或是左栏足够宽时显示正常：
<img width="199" alt="" src="https://user-images.githubusercontent.com/24860299/42773951-e23234ea-8962-11e8-8994-fc5238d32726.png">

<img width="360" alt="" src="https://user-images.githubusercontent.com/24860299/42773962-e9b8f528-8962-11e8-9ce1-245c447d4b64.png">

另外，英文标题换行时的断字问题（如下图，a-met）有办法解决吗？像是加入hyphen或者按单词换行。
<img width="216" alt="" src="https://user-images.githubusercontent.com/24860299/42774228-ca7eb89a-8963-11e8-9f44-29c27d6ffc5f.png">

**Comment by ypl6** [comment]
按创建时间排序的功能有时候会失效：

下图四个文件的创建日期是在front matter里改的，年份分别为2017-2018-2015-2016。
选正序、倒序都不能正确排序。

<img width="57" alt="" src="https://user-images.githubusercontent.com/24860299/42775637-7199fd58-8967-11e8-82f5-a94af4d7dda2.png">

**Comment by hemashushu** [comment]
@panlyp 好的，我检查一下，感谢反馈！
