### ISSUE TITLE
为什么作者把原来的首页介绍删除了啊？我觉得以前那个很厉害的。现在这个我都没法跟人吹了

### ISSUE THREAD

**Issue by ddkk3000** [ivarptr/yu-writer.site#261]
还是恢复原来那个吧，现在这个太简洁了。

**Comment by hemashushu** [comment]
因为旧的介绍界面跟新版本的完全不同，然后，新版本的介绍页面还没空写，于是就变成现在这个状态了😅

**Comment by ddkk3000** [comment]
有这么大不同吗～～～原来要做的功能都不做了？

话说win版快来了吧

╭( ′• o •′ )╭☞ lixiaozhe.com

________________________________

**Comment by ddkk3000** [comment]
还真完全不一样了。。。原来的功能都不做了，我还以为会跟pandoc结合自动输出doc呢。
![qq 20180605195211](https://user-images.githubusercontent.com/10786234/42665267-7ed60884-8671-11e8-9814-afcdb384f923.jpg)

**Comment by hemashushu** [comment]
@ddkk3000 没有吧，我记得没砍功能啊，只是加了个树形列表，换了件蓝紫色 T 恤，其他都还在呢。pandoc 输出 doc 的效果不怎么好（虽然全世界都是用它来 md 转 doc），这个模块我准备自己重新写一个，先从简单的格式支持开始，总之尽量轻巧&保持格式

**Comment by ddkk3000** [comment]
新版一打开，多了一条边栏，看起来超复杂的。??

pandoc转换doc不好，但支持论文格式的参考文献转换呀。

q( ′* o *′ )q? lixiaozhe.com

________________________________
