### ISSUE TITLE
command+右方向粘贴失败

### ISSUE THREAD

**Issue by MasonPanHB** [ivarptr/yu-writer.site#263]
mac 0.5.1 版本，场景如下

1. 先任意选中一段文本，复制到剪贴板
2. 再使用方向键，让鼠标上下移动到要粘贴的一行
3. 使用 command + 右方向 快捷键挪动光标到本行最右侧
4. command + V，此时按理说应该在最右侧续写粘贴文本，实际情况却是粘贴到了光标在 command + 右方向 挪动前的位置

本问题可重现。

**Comment by hemashushu** [comment]
@MasonPanHB 收到，原来只要是按住 Cmd 键不放，第 2 个以上的操作都会有位置错乱的BUG，目前已修复，待 0.5.2 时发布。非常感谢反馈！

**Comment by hemashushu** [comment]
@MasonPanHB 新版本 0.5.3 已释出，已经修复了这个问题，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
