### ISSUE TITLE
什么出win版 还在用0.44呢

### ISSUE THREAD

**Issue by suiang** [ivarptr/yu-writer.site#265]

**Comment by hemashushu** [comment]
@suiang 大概在月底，现在还有些许UI方面的问题正在解决ing

**Comment by vyan13** [comment]
@ivarptr ，大佬，请问复制网页内容自动把图片下到本地什么时候能有？

**Comment by hemashushu** [comment]
@vuyzan 可能要到 0.7 版，其实实现不难，不过现在要优先处理出 win 版还有跳票一年多的 linux 版 😂

**Comment by hemashushu** [comment]
@suiang 新版本 0.5.3 已释出，mac 和 win 平台皆有，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
