### ISSUE TITLE
order list 换行输入无法插入下级list

### ISSUE THREAD

**Issue by zsychn** [ivarptr/yu-writer.site#266]
现在无法输入下面的list
![image](https://user-images.githubusercontent.com/23525693/41700561-4ab0dcd6-755b-11e8-83fe-4747b17f22b7.png)

每次使用tab想插入下级的list都会变成这样
![image](https://user-images.githubusercontent.com/23525693/41700579-621da5de-755b-11e8-9e28-c18172bf7d03.png)

不知道是怎么回事

**Comment by hemashushu** [comment]
@zsychn 不是很清楚问题，比如在 "1. 订“ 字后面（假设后面没有别的文字）回车，它应该会自动产生 "2. "，这个时候如果想让它右缩进（表示下级 list），的确是可以按 `Tab` 让它右缩进，我这里测试过应该是没问题的，你是指它的序号应该改为 "1. " ？

另外：其实 Markdown 都是纯文本，当遇到 ”自动补完“ 功能失效时，有时可能是程序的 bug 引起，这时可以手动移动光标回去直接修改即可，因为都是纯文本，可随意修改。

**Comment by zsychn** [comment]
是的，我是希望它改为1.，因为是子列表了嘛，它应该是一个新的list，你的这个开始可以自动变成1. 后来不知道为什么就不行了，我试了好多次都会延续父列表继续编号

**Comment by zsychn** [comment]
不过按照你的办法问题已经解决了，哈哈哈，非常感谢，已购买，发现这是目前我觉得最好用的一个markdown了

**Comment by hemashushu** [comment]
@zsychn 嗯嗯，有序子列表的序号问题的确是个bug，下个版本修复，谢谢反馈！
