### ISSUE TITLE
两个 $ 符号被识别为行内代码块

### ISSUE THREAD

**Issue by chhpt** [ivarptr/yu-writer.site#267]
<img width="409" alt="2018-06-21 15 43 22" src="https://user-images.githubusercontent.com/19288423/41704817-debdc9da-7569-11e8-9beb-8d14a75279d1.png">

如图

**Comment by hemashushu** [comment]
@chhpt 因为 Yu Writer 默认启用了解析 `$` 和 `$$` 符号为数学公式，根据它们的语法是会渲染成这样，如果不想让它解析为数学公式，可以在设置里禁用程序渲染数学公式，或者在文档的 Front Matter 里加入一个选项 `enable equation: false` 禁止当前文档不解析数学公式，加完这个头的文档看起来如下：

```markdown
---
enable equation: false
---
# Document title
...
```

又或者在 `$` 符号前加一个 `\` 转义字符，比如这样：
`this.\$border, this.\$emit, this.\$invoke`

PS 1 我发现编辑框一个 bug，在添加了转义字符后它仍解析为数学公式，下个版本修正，谢谢反馈。
PS 2 下个版本可能会更改程序的默认值，改为默认不解析单独的一个 `$` 符号的数学公式，因为单独 `$` 符号太容易误解了。

**Comment by chhpt** [comment]
@ivarptr 似乎添加 `enable equation: false` 不起作用，而且似乎设置里面不能禁用相关选项。

**Comment by hemashushu** [comment]
@chhpt 禁用的选项在 0.5.1 里面还没做完所以没有显示，估计下个版本就会显示出来并可让用户选择。目前的版本对 `enable equation: false` 这个选项会在 “即时预览” 以及 “预览” 里起作用（即不渲染数学公式）但编辑框有个 bug，所以加上去它还是会认为是数学公式，大概下个版本会修正。

**Comment by hemashushu** [comment]
@chhpt 新版本 0.5.3 已释出，已经修复了这个问题，修复方法包括：
* 默认不允许单美元符号表示行内数学公式，用户可设置
* 在设置里增加了详细的启用/禁用部分 markdown 语法的功能，而且设置禁用之后，无论是即时预览、预览，还是编辑框，都一同生效。

欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
