### ISSUE TITLE
Header style error

### ISSUE THREAD

**Issue by MasonPanHB** [ivarptr/yu-writer.site#270]
如图这么一个示例的文档，为什么会提示我：

Header style
This rule is triggered when different header styles (atx, setext, and 'closed'
atx) are used in the same document:

这么简单的格式和内容到底问题在哪……我开始怀疑人生了。

文章整个内容如下：

```
标题
==

# 业务背景

店铺

# 需求概述

本文档描述
```

<img width="260" alt="2018-06-26 22 33 57" src="https://user-images.githubusercontent.com/6447075/41919505-3cbd53c2-7991-11e8-917c-bbf01c463deb.png">

**Comment by hemashushu** [comment]
@MasonPanHB 哈哈哈，这个是 markdown 的语法检测提示，它约定了一系列良好书写格式的 “规范”，因为并不是 “规则” 所以实际上并不影响输出。
回到问题，这个提示是说同一个文档里混合使用了两种风格的标题，即 `==` 和 `#`，规范建议最好只使用一种风格，比如：

```markdown
标题
==

业务背景
----------

店铺

需求概述
----------
```

或者这样：

```markdown
# 标题

## 业务背景

店铺

## 需求概述
```

**Comment by hemashushu** [comment]
@MasonPanHB 最新版 0.5.3 已经加入可以配置语法提示的具体规则，或者干脆在设置里把语法检测关闭，详细可参阅随软件附带的使用手册。这个 issue 我先关闭哈，如有问题欢迎随时问。ps
