### ISSUE TITLE
关于win端的Library与Outline切换

### ISSUE THREAD

**Issue by ghost** [ivarptr/yu-writer.site#271]
二者切换时会卡住，虽然还能写作但不能切换文件，需要进行一下Search才能恢复正常，希望优化下

**Comment by hemashushu** [comment]
@yurjane 好的，因为在 0.5 版彻底重写了这个模块，等到 0.5 版出来时（大概 7 月初）希望再帮忙测试一下

**Comment by ghost** [comment]
@ivarptr 问个问题，文件排序是按什么排的，如果按首字母排会排出 J、S、B、F、B、J 的情况，让我迷惑，能否出个排序功能 :scream:

**Comment by hemashushu** [comment]
@yurjane 嗯，0.5 版已加入完整的排序功能，可以通过简单鼠标点击来切换名称、时间等排序或者倒序，也支持自定义复杂的排序表达式，下周见。

**Comment by danwangwangdan** [comment]
@ivarptr 期待Win新版

**Comment by ghost** [comment]
一天看三回，我也是绝了 :joy:

**Comment by dongyaosen** [comment]
windows端的新版本是否快发布了?

**Comment by danwangwangdan** [comment]
又来了 莫非是要等到这周五 --

**Comment by hemashushu** [comment]
只剩下测试，乐观是周四，悲观就。。。see #274

**Comment by hemashushu** [comment]
@yurjane @danwangwangdan @dongyaosen 新版本 0.5.3 已释出，这个 issue 我先关闭哈，如有问题欢迎随时问。
