### ISSUE TITLE
每次ctrl+s保存都会新创建一个文件夹包是啥情况？

### ISSUE THREAD

**Issue by zhangchuanjia123** [ivarptr/yu-writer.site#272]
已经绑定了博客文件夹，每次ctrl+s保存都会在 _posts文件夹自己创建一个跟md文本名一样的文件夹，刷新博客后会多出一些乱码是啥情况呢？这样每次都要手动去删除文件包是有点麻烦。
![image](https://user-images.githubusercontent.com/18108847/42069000-c08ab81a-7b81-11e8-90a8-efad223c4025.png)

**Comment by hemashushu** [comment]
@zhangchuanjia123 这个文件是文档的编辑历史记录，类似 git 的 commit log，正常情况下文件是每 60 秒自动保存一次（假如内容发生改变的话），而 `ctrl+s` 是为手动保存党保留的隐藏的强行保存按钮，所以自动冒出 commit 文件的源头不是 `ctrl+s` 而是 yu writer 的历史记录功能。

按理说如果是通过 yu writer 把博客文件夹引用进来的会自动把历史记录文件放在另外一个地方，有两个方法解决:

1. 在 yu wrtier 里删除这个博客文件夹（删除的只是一个链接，可放心删除，或者删除前先复制备份一次博客），然后再用 yu writer 的 `new library` 向导添加博客项目文件夹进来。

2. 你可以检查一下博客项目根文件夹底下的 `yulib.config` 文件，确保里面有这样的一行：

```json
"isolateResource": true,
```

如果没有这行则添加上去再重新运行 yu writer 即可，如果没有这个文件就手动创建，文件完整内容如下。

```json
{
	"isolateResource": true
}
```

**Comment by zhangchuanjia123** [comment]
好的，受教谢啦

**Comment by hemashushu** [comment]
@zhangchuanjia123 新版本 0.5.3 已释出，修复了_posts 原先列举文档不完整（部分文档列不出）的 bug，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
