### ISSUE TITLE
我就知道……

### ISSUE THREAD

**Issue by vyan13** [ivarptr/yu-writer.site#274]
最终还是到了七月……

**Comment by ccyx1997** [comment]
像我没两天看一遍有没有更新win版本也是没谁了吧

**Comment by RonaldinhoL** [comment]
不跳票是不可能的，这辈子都不可能不跳票的。

**Comment by RonaldinhoL** [comment]
@ccyx1997 我也是，基本上每天都在用，然后写之前先check update一下 😂

**Comment by vyan13** [comment]
哈哈哈，怨念都不小😂，现在的wondows版本功能还是有稍稍的简陋，希望下一个版本就能作为主力编辑器使用。

**Comment by qw4096** [comment]
一天看一次岂不是没救了

**Comment by niyalishanda** [comment]
同一天一看

**Comment by hemashushu** [comment]
@all 哈哈哈，我也想快快出，但就差一点儿，这个周末应该能完成，我夜观一下星象，7月9~14都是黄道吉日，那几天妥妥的会发布。😁😁

**Comment by whzecomjm** [comment]
蛤蛤蛤 这么多同道中人

**Comment by zhyt0520** [comment]
哈哈，很是期待

**Comment by zxjack** [comment]
加油，我也等着呢

**Comment by bravelee** [comment]
@ivarptr 「7月9~14都是黄道吉日」，不，一定是7月15号凌晨发布，哈哈

**Comment by hemashushu** [comment]
已经连续婉推了几个联合国峰会啦，现在 win 版的状态是：

✅ 多语言模块完成，支持（不完全）中文界面了
✅ 32 位和 64 位打包完成
✅ 纯绿色便携运行模式完成
✅ 最低 win7 支持完成
❎ 逐项功能测试……未完成

估计后天可以下载了

![default](https://user-images.githubusercontent.com/394223/42486269-af25805a-842d-11e8-9c20-828717ea882c.JPG)

**Comment by qw4096** [comment]
感谢大佬

**Comment by ghost** [comment]
大佬加油

**Comment by vyan13** [comment]
加新的配色了吗，大佬

**Comment by ccyx1997** [comment]
我在等linux版本的，不知道什么时候能出，win至少还有旧版可以用，linux上只能用typora，大佬加油。

**Comment by hemashushu** [comment]
@vuyzan win 版的默认主题，win 版用户可以自己设置标题区域的颜色（0.5.3 会在设置窗口里加上）

**Comment by hemashushu** [comment]
@ccyx1997 linux 版基本上已经完成，除了少量 UI 元素需要稍微调整之外，本来想这个月底打包出来的，现在看来要到下月初了。

**Comment by ddkk3000** [comment]
坏了，从预览图发现软件功能与之前在主页上的宣传几乎完全不一样了，是另外一个软件了。尴尬了尴尬了

**Comment by vyan13** [comment]
完了，明天要去外地出差，看来是没法第一时间体验新版本了……啊啊啊啊啊啊啊啊啊

**Comment by ddkk3000** [comment]
好了，我代表作者向你公布好消息: 明天不发新版。??


于 2018年7月11日 12:56，vuyzan <notifications@github.com>写道：


完了，明天要去外地出差，看来是没法第一时间体验新版本了……啊啊啊啊啊啊啊啊啊

―

**Comment by hemashushu** [comment]
好了好了，0.5.2 for Windows 更新放出了 https://ivarptr.github.io/yu-writer.site/

**Comment by RonaldinhoL** [comment]
下载体验……

**Comment by qw4096** [comment]
哈哈，大佬辛苦了

**Comment by hemashushu** [comment]
好了好了，新版本 0.5.3 也释出了， win 和 mac 平台皆有，linux 平台这个月底或者下月中应该能出，这个 issue 我先关闭哈，如有问题欢迎随时问。
