### ISSUE TITLE
【建议】在插入图片窗口能直接从粘贴板获取图片

### ISSUE THREAD

**Issue by buynowdev** [ivarptr/yu-writer.site#276]
很多时候图片是以截图复制等形式，图片会保存在粘贴板，如果能直接在插入窗口识别到粘贴板的图片并能点击插入，同时自动将图片存储在本地，那么在图片插入上体验将更愉悦。

       产品真的很好用，特别中意，谢谢！

**Comment by hemashushu** [comment]
@zhaoyuening  谢谢建议和鼓励，这个功能迟些时候会补上
