### ISSUE TITLE
默认是多实例而不是多文档的吗？

### ISSUE THREAD

**Issue by RonaldinhoL** [ivarptr/yu-writer.site#278]
0.52 从文件夹打开了好几个文档，然后就弹出了好几个窗口。

**Comment by hemashushu** [comment]
我找了一下，本来设置里有个选项让选择是否总在新窗口中打开外部文档的，但好像在更新过程中被我注释掉了 😂下个版本我把它加上，或者你试试手动编辑应用程序的配置文件 `app.json` （位于 `c:\\Users\\$USER\\AppData\\Roaming\\Yu Writer\\config`），加上如下一行：

```json
"alwaysNewWindowWhenOpeningExternally": false,
```
试试有没效果，我晚上也测试一下。谢谢反馈

**Comment by RonaldinhoL** [comment]
加上可以了😂
