### ISSUE TITLE
win端bug：不能通过拖拽标题栏改变窗口大小了

### ISSUE THREAD

**Issue by Boycottangent** [ivarptr/yu-writer.site#279]
win10的64版本，最大化的时候想拖拽标题栏取消最大化，失败了，一直保持最大化
一个不怎么起眼的bug就是了...

**Comment by hjings** [comment]
好像只能点右上角的最大化按钮，不能拖拽标题栏。拖拽标题栏后，虽然窗口暂时不是最大化状态，但跟最大化没有区别，而且下面显示字符数的状态栏会被遮掉一半。

**Comment by hemashushu** [comment]
@Boycottangent @hjings 新版本 0.5.3 已释出，已经修复了这个问题，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
