### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by ShuaiDa** [ivarptr/yu-writer.site#28]
![image](https://user-images.githubusercontent.com/24203675/29602367-76506d16-8812-11e7-8840-9d3d0a8fa4b0.png)

**Comment by hemashushu** [comment]
@ShuaiDa 请问是在什么情况（或条件）下会出现这个错误呢？希望能具体描述一下，谢谢～

**Comment by hemashushu** [comment]
@ShuaiDa 你好，不知道这个问题是否持续存在，错误信息应该是由保存文件时写入历史记录发生错误导致的，目前软件已更新至 0.5.3，这个模块也修复过很多 bug，可以试试新版本是否已解决这个问题，如果有新问题欢迎随时反馈，这个 issue 我先关闭哈。
