### ISSUE TITLE
多行公式渲染不换行

### ISSUE THREAD

**Issue by RonaldinhoL** [ivarptr/yu-writer.site#280]
发现一个bug，0.52版的所有公式渲染都不换行了，都渲染在一行上面，比如下面这个公式
$$\begin{align}
J(\theta) &= \ln L(y|x;\theta) \\
&= \sum_{j=1}^m \ln \left [ y^{(j)} h_\theta(x^{(j)}) + （1- y^{(j)}）(1 - h_\theta(x^{(j)})) \right ] \\
\end{align}$$

然后发现在设置里勾选 “启用单美元符号的行内公式” 以后渲染就会换行。
这里是不是有bug，按说这个选项不应该影响多行公式的。

**Comment by hemashushu** [comment]
@RonaldinhoL 是的，是一个 bug，原因是 markdown 解析器把公式文本先解析了一次，再传递给 mathjax 解析器，现已经修复，效果如下图。下次更新应该没问题了。谢谢反馈!

![default](https://user-images.githubusercontent.com/394223/42659004-7ab1eed4-8659-11e8-81e8-5e1e7db07194.PNG)

ps1 勾选单美元符号那个选项完全是意外的副作用，哈哈哈
ps2 换行好像要用两个反斜杠了 `\\`

**Comment by RonaldinhoL** [comment]
对，我的文本是两个斜杠的，复制上来变成一个了，没注意。
另外，现在语法着色必须要
$$
\begin{align}
J(\theta) &= \ln L(y|x;\theta) \\
&= \sum_{j=1}^m \ln \left [ y^{(j)} h_\theta(x^{(j)}) + （1- y^{(j)}）(1 - h_\theta(x^{(j)})) \right ] \\
\end{align}
$$
这样子写了，就是两个$$单独作为一行，我记得之前没有这个要求的，这是markdown的标准格式写法吗？😂

**Comment by hemashushu** [comment]
单独作为一行 不是 md 要求的，mathjax 也没这方面的要求，但这样写就很方便阅读的时候知道这是 block 类型的东西，比如
```fancycode
...
```
还有
---
frontmatter: xxx
---
等
所以我就在编辑器的高亮里稍微限制一下，哈哈

**Comment by hemashushu** [comment]
@RonaldinhoL 新版本 0.5.3 已释出，已经修复了这个问题，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
