### ISSUE TITLE
一份授权可以给几台设备使用？

### ISSUE THREAD

**Issue by MKDJOJO** [ivarptr/yu-writer.site#281]
一份授权可以给几台设备使用？便携版呢？

**Comment by hemashushu** [comment]
@MKDJOJO 现在授权是跟机器走，即，一机一授权
便携版也是跟机器，就是说如果我把 U 盘插到有授权的机器它就会自动成为注册版（如果是别人的机器，则还需把它的授权 key 文件复制到 U 盘），插到未授权机器又变成未注册版。

**Comment by zdz316** [comment]
@ivarptr 对于有多台电脑的 好不方面哦。

**Comment by ZhaoTiexiong** [comment]
是啊，现在的情况是公司一台Mac笔记本，家里一个笔记本，一个台式机，那我就需要买三个授权了吗？  
能不能基于邮箱地址，做一个单emai账号最多几个授权的策略，这样更符合目前大家的一个实际需求，要不然买一个软件重复花钱，用户会比较有意见的。  
望采纳...

**Comment by longzekai** [comment]
这个确实不太友好，现在个人基本都不止一台设备。

**Comment by hemashushu** [comment]
到正式版之后会加入在线激活验证模块，同时还有应用市场（比如 mac app store，不过因为沙盘机制，有部分功能需要阉割）的版本，这些版本都允许一份授权给多台机器使用。
因为目前我能用在开发的时间和精力很有限（PS 从 0.1 版走到 0.5 花了两年），而且这个模块还需要做服务端，还要到在线支付商申请接口等一系列工作，估计也没法很快就实现，这段时间暂时只好用一个很古老原始的本地验证激活凑合着，希望大家理解。
起初也考虑到一人多机器的问题，所以在第二份授权是打了 6 折希望能减少购买多份授权的开销，如果有一机多系统或者近期需要升级更换机器或者其他特殊情况，可以联系我可以免去额外的花费。

**Comment by hemashushu** [comment]
@MKDJOJO @zdz316 @ZhaoTiexiong @longzekai 

更新一下
详细请见：https://github.com/ivarptr/yu-writer.site/issues/318#issuecomment-416025606
上面链接的主要内容这里也摘录一下：以后会有在线注册模块，完成后现已注册的用户会自动无缝升级为在线版。另外就是现在第二份授权由6折降为3.5折，这样会对多台设备的用户来说人性化一些。

另外最新版本 0.5.3 已释出，欢迎下载试用。
因为已有相同的 issue，这个issue我先关闭哈。
