### ISSUE TITLE
授权迁移的问题以及一些软件未来功能的请求

### ISSUE THREAD

**Issue by lincolnguang** [ivarptr/yu-writer.site#283]
## 授权迁移
在阅读注册界面的文字的时候，我注意到：
「转账成功后，请把转账记录的 “转账单号” （支付宝里称为 “订单号”）最后 8 位数字以及 上面的机器码发送到作者的 Email」
也就是说授权是和电脑唯一绑定的，假如我需要重装系统亦或是这台电脑再也不需要使用 Yu Writer，即如果我需要迁移授权/反激活我应该怎么做？

另外我希望作者能通过邮箱+序列号/激活文件的形式在线激活

### 导出
导出时候，希望增加如下功能：
1. html 导出时希望能够附加css文件以美化页面
2. 希望增加额外的导出格式支持
 - ePub
 - .icml (inCopy 交换文档）
 - .xhtml

### 文档
1. 希望增加文档的分割功能，方便将单个文档拆分成多个文档
2. 希望增加对于整个库的打包备份
3. 希望在智能列表筛选标签的功能，而不是单单筛选颜色

**Comment by ghost** [comment]
邮箱+序列号 这可能需要到验证用服务器，估计作者老哥也不太可能会搞吧。
使用邮箱登入一次后离线使用就不需要再次验证了，除非需要保持联网（没服务器，不现实）。
对于最大授权设备数量是需要服务器统计的。。。
老哥，考虑下steam，虽然是个游戏平台，但可以发布软件，这样就不用担心换电脑，重装系统之后的授权问题了，反正我是不会把自己的steam的账号交出去的，可是就怕破解，估计也不会有人破解小众软件（好吧，还是会存在可能性的）。。。

**Comment by hemashushu** [comment]
@lincolnguang 谢谢你的建议！导出和文档功能基本上都是在我的 TODO list 之上（除了 icml 格式）哈哈。

至于授权，目前是临时凑合用着，因为是单纯的单机本地验证，没有联网所以没法做到反激活/撤销授权。当软件大部分功能做完后我想可能会上架到各个平台的应用市场，又或者通过第三方平台销售，到时就可以实现较灵活的授权了。
