### ISSUE TITLE
Win x64版本编辑过程中异常丢失文本内容

### ISSUE THREAD

**Issue by hjings** [ivarptr/yu-writer.site#284]
Windows x64版本。举个例子，假如有一行的内容是“abcd”，首先将“abc”选中，然后将光标移动到“a”前面点击，使得选中的状态取消。这时候按下Enter键，会发现这一行前面新增了一行，同时这一行的内容变成了“d”。
感觉好像选中的状态并没有真正被取消一样。

**Comment by hemashushu** [comment]
@hjings 谢谢反馈，我找到原因了，重现方法是：只要是用鼠标点击选定的文字，它都没有真正撤销选定。如果点击后的操作是单纯录入文字还不会出错，但如果是诸如回车、Tab、Del、Back Space、粘贴 之类的操作全部都错了。目前已修正，下次更新时请帮忙再测试一下。谢谢！

**Comment by hemashushu** [comment]
@hjings 新版本 0.5.3 已释出，已经修复了这个问题，如有问题欢迎随时问，这个 issue 我先关闭哈。
