### ISSUE TITLE
请教0.52win版的便携模式，是否 bootstrap.config 文件还需要其他设置？

### ISSUE THREAD

**Issue by houxiren** [ivarptr/yu-writer.site#285]
1，现在的 Yu Writer Resources 和 Yu Writer Libraries 这两个目录是设定在 Yu Writer.EXE 程序的上级目录，这样不方便，能否自定义成与 Yu Writer.EXE 在同一个目录中的User Date目录？可以的话如果设置？

{
"portableMode": true,
"portableResourceDirectory": "Yu Writer Resources",
"portableLibraryDirectory": "Yu Writer Libraries"
}

2，运行后还是会生成以下目录，是否这个目录也可以在 bootstrap.config 中定义路径。
C:\Users\Administrator\AppData\Roaming\Yu Writer

辛苦开发者了，祝好。

**Comment by hemashushu** [comment]
@houxiren 
可以的，配置文件内容的第 3，4 行可以填写相对路径，比如假设 Yu Writer 程序的文件夹名字为 `Yu Writer`，则可以这样配置：

```json
{
"portableMode": true,
"portableResourceDirectory": "Yu Writer\\Yu Writer Resources",
"portableLibraryDirectory": "Yu Writer\\Yu Writer Libraries"
}
```

注：在 JSON 文件中两个反斜杠表示斜杠字符，当然也可以写一个正斜杠。

相对路径甚至是父目录，或者是子目录中的子目录。比如：

```json
{
"portableMode": true,
"portableResourceDirectory": "Yu Writer/User Data/Resource",
"portableLibraryDirectory": "Yu Writer/User Data/Library"
}
```

至于 `C:\Users\Administrator\AppData\Roaming\Yu Writer` 这个目录我也注意到了，即使程序运行在便携模式，但它还是会创建，因为 Yu Writer 构建在 Electron 基础之上，而这个目录正是 Electron 自己创建的，里面大致是它自己运行的缓存之类的数据。可惜的是我好像没法让它不创建或者创建在别的地方 😂

**Comment by houxiren** [comment]
@ivarptr 谢谢您的回复。之前您说便携版要到0.6或0.7版才有，现在更早地推出，真是欢喜之至。感谢您开发分享好软件。祝好。

另，注册版与未注册版的区别是哪些呢？

**Comment by hemashushu** [comment]
@houxiren 主要区别在于注册后有更多个性化的功能，另外还有以后推出的高级功能也仅对注册版开放。

**Comment by hemashushu** [comment]
@houxiren 新版本 0.5.3 已释出，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
