### ISSUE TITLE
windows版文字渲染的问题

### ISSUE THREAD

**Issue by motta** [ivarptr/yu-writer.site#286]
请问有办法快速关闭direct-write，让mactype正常渲染吗？

谢谢。

**Comment by hemashushu** [comment]
@motta 我不太了解 mactype，请问 Google Chrome 能关闭 directwrite 吗? 因为 Yu Writer 的底层框架是 Electron，而 Electron 正是 Chromium（Google Chrome 核心&开源部分），假如 Chrome 能关闭请提供一些参考资料给我，我测试一下，谢谢反馈
