### ISSUE TITLE
希望预览窗口加一个横向的滚动条

### ISSUE THREAD

**Issue by RonaldinhoL** [ivarptr/yu-writer.site#287]
公式横向太长了后面看不到😂

**Comment by hemashushu** [comment]
@RonaldinhoL OK，是忘记加了。目前代码块是考虑到这种情况，当区块太宽时，区块会自动出现横向滚动条

**Comment by hemashushu** [comment]
@RonaldinhoL 新版本 0.5.3 已释出，已经在超宽公式、超宽代码块增加了横向滚动条，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
