### ISSUE TITLE
Mac版本关闭软件后弹出报错框

### ISSUE THREAD

**Issue by sydowma** [ivarptr/yu-writer.site#290]
复现：
输入文字后直接点击左上角关闭，弹出报错框。

![image](https://user-images.githubusercontent.com/3363787/42719737-7dc24052-874d-11e8-9652-e327ff9afc4f.png)

macOS 10.13.5 
Yu Writer 0.5.2

**Comment by hemashushu** [comment]
@magaofei 你好，我试了好几种退出情况都没法重现，请问是说先打开任意一个文档，然后随便录入一些文字，再点击窗口左上角交通灯的红色按钮关闭吗？

**Comment by sydowma** [comment]
是的。我在公司电脑也没有成功复现，不知道为什么，家里电脑会这样。。。

**Comment by hemashushu** [comment]
@magaofei 新版本 0.5.3 已释出，因为修复的地方非常多，我也不太记得有没把这个bug也解决了，欢迎下载试用看看问题是否存在，如有问题欢迎随时问，这个 issue 我先关闭哈。
