### ISSUE TITLE
windows 64位打开报错

### ISSUE THREAD

**Issue by lewis1ee** [ivarptr/yu-writer.site#291]
![error](https://user-images.githubusercontent.com/12009842/42790945-31e2e948-89a0-11e8-8745-aa125c7d16f1.png)
第一次打开可以正常使用，关机后再打开就报这个错。

**Comment by lewis1ee** [comment]
在后台栏里可以打开正常使用

**Comment by lewis1ee** [comment]
注册那里的机械码没了

**Comment by hemashushu** [comment]
@Roper 我也试过一次，重启电脑后又自己好了，我还在查找一下什么原因导致的， 谢谢反馈

**Comment by lewis1ee** [comment]
我这边重启后还是这样，注册那里的唯一机器码没有显示，有别的方法注册吗，我试过重新下载一次，把原来的删除，还是这个问题。

**Comment by hemashushu** [comment]
因为截图的里的错误提示信息显示为乱码所以我也不太清楚具体原因，怀疑是系统的 wmic 服务（Windows Management Instrumentation）被停止了，试试重新打开这个服务，方法如下截图。

![wmi](https://user-images.githubusercontent.com/394223/43316472-0e59d520-91cc-11e8-98f9-3ae413a177bb.PNG)

参考资料：
https://docs.microsoft.com/en-us/windows/desktop/wmisdk/starting-and-stopping-the-wmi-service

**Comment by lewis1ee** [comment]
我这里这个服务没有被停止，然后我重启了试了一下也不行。

**Comment by hemashushu** [comment]
@Roper 或者试试在命令提示符（即 cmd）里运行 `wmic CsProduct` 看看它有无错误提示，如果有的话请把错误提示（估计是中文，在命令提示符里应该能正常显示）贴出来。

如果仍然没法正常运行的话，大概过两周我会发布个小版本更新，把该注册模块的异常捕捉起来，这样一来即使注册模块失败也不影响程序的启动和运行。

**Comment by lewis1ee** [comment]
@ivarptr 不知道为啥突然就好了...

**Comment by hemashushu** [comment]
@lewis1ee 新版本 0.5.3 已释出，已经修复了这个问题，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
