### ISSUE TITLE
原来的预览功能去哪了

### ISSUE THREAD

**Issue by wangmingquan** [ivarptr/yu-writer.site#292]
原来的预览功能去哪了！！！！本来想着说话一百块钱支持一下的，但是最常用的预览功能没有了！！
另外，html代码功能还是没有实现！！！有那么难吗

**Comment by hemashushu** [comment]
@wangmingquan 预览在 “查看” 里，如果你想找某一项功能，可以点击一下菜单，一般的功能都会在菜单里有对应的菜单项。

另外，“预览” 在工具栏上也有对应的按钮：
![default](https://user-images.githubusercontent.com/394223/42801938-df5840e0-89d3-11e8-96b2-502b394c5e6d.PNG)

html 代码功能是指在渲染里解析 HTML 标签吗?

**Comment by tielemao** [comment]
我想实际上问的不是预览功能，而是阅读模式吧。我也是觉得最重要的阅读模式没了很不习惯，不过初略试了一下查看中的预览，也算是另一种阅读模式了吧。只是发现0.44版本中[[toc]]的语法在0.52中没有了，试了[toc]也没有效果呢。

**Comment by hemashushu** [comment]
@tielemao  哦，这里的“预览”其实就是0.4.4的阅读模式，因为我觉得叫阅读模式并不准确所以改名了，而真正的阅读模式我已经有了轮廓但还没写完所以就看到现在工具栏上一个带星号的按钮，估计0.6版会完成。

toc的语法改成 @toc 在菜单里点击插入再点击目录就会自动插入 @toc 字符串。因为 我准备用一种统一的格式来扩充markdown标准，即 @ + 名词 + meta，这种格式也是 commonmark 里有讨论但还没定型的语法，而 [[toc]] 因为跟这种标准相差太远所以就放弃了

**Comment by wangmingquan** [comment]
html 代码功能是指在渲染里解析 HTML 标签吗
----------
对头，就是渲染html标签。比如，在表格里换行

**Comment by hemashushu** [comment]
嗯，这个会在0.5.4实现，因为0.5实际上是从某个issue就开始做，于是后面的issue和request都挂起来了，0.5.3补完0.5新引进的bug之后就开始清issue

王明全 <notifications@github.com> 于 2018年7月18日周三 下午1:18写道：

**Comment by hemashushu** [comment]
@wangmingquan 新版本 0.5.3 已释出，已经增加了HTML解析功能（可以在设置或者在文档的 front matter 里打开），欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
