### ISSUE TITLE
每次双击打开一个 md 文件都会打开一个全新的 Yu writer 软件

### ISSUE THREAD

**Issue by 777Arch** [ivarptr/yu-writer.site#295]
windows 7 下使用 0.5.2 版本，每次双击 md 文件都会在一个全新的 Yu writer 软件中打开。怎么设置为全部在已有软件中的新标签页中打开呢？
Mac 版本下还没有使用，不知道是否有同样的问题。

**Comment by 777Arch** [comment]
已确认，Mac 下有同样的问题。

**Comment by hemashushu** [comment]
@Mlearn 
你好，这个是 0.5.2 的一个 bug，原本在软件设置里有个选项可选择是否在新窗口打开的，下个小版本会重新加上。目前要解决的话需要手动更改配置文件 app.json，这个文件的位置：

* Windows: C:\Users\YOUR_NAME\AppData\Roaming\Yu Writer\config
* macOS: /Users/YOUR_NAME/Library/Application Support/Yu Writer/config

打开 app.json，在第二行加上如下一行保存在打开 yu writer 即可

```json
{
  "alwaysNewWindowWhenOpenDocumentExternally": false,
  ...
}
```

**Comment by hemashushu** [comment]
@Mlearn 新版本 0.5.3 已释出，已经修复了这个问题，现在可以在软件的设置里更改从外部打开文档的行为了。欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
