### ISSUE TITLE
Windows 下通知栏图标显示的问题

### ISSUE THREAD

**Issue by 777Arch** [ivarptr/yu-writer.site#297]
Windows 7 使用的 0.5.2 版本,
可否考虑不在系统的通知栏显示软件图标呢？因为一般来说，那里用不着什么需要常驻的功能吧？打开软件之后出现一个图标会占地方，也觉得别扭。如下图所示：
![snipaste_2018-07-18_15-01-53](https://user-images.githubusercontent.com/7379015/42865282-c484ca5e-8a9b-11e8-8617-04c03b2ba514.png)

**Comment by hemashushu** [comment]
@Mlearn 在设置里去掉 “启用托盘图标” 的勾勾即可。

**Comment by hemashushu** [comment]
@Mlearn 新版本 0.5.3 除了在设置里原来的去掉托盘图标选项，还新增了去除全局快捷键的选项，如有问题欢迎随时问，这个 issue 我先关闭哈。
