### ISSUE TITLE
没有自定义模版功能？

### ISSUE THREAD

**Issue by ljw4010** [ivarptr/yu-writer.site#301]
比如我写hugo，标题title字段等，创建时间等，我想使用模版自动加载，不知道是不是不支持

**Comment by hemashushu** [comment]
@ljw4010 会支持， 但目前只实现了一部分，比如在普通类型库里新建文档显示的是一般性的文档模板，而在 static blog 类型的库里新建文档显示的是 blog 类型的文档模板，但还没实现根据项目（比如 hugo 或者 hexo 等）的配置来加载模板或者加载用户自定义模板。估计要再到 0.7 版本会完善该模块。

**Comment by ljw4010** [comment]
好的，很期待！
