### ISSUE TITLE
在未打开yu的情况下，双击一个markdown文件，无法正常打开

### ISSUE THREAD

**Issue by wangmingquan** [ivarptr/yu-writer.site#302]
**Platform/操作系统类型**
macOS

**OS version/操作系统版本**
macOS 10.13.6

**Application version/应用程序的版本号**
0.5.2

**Describe the bug/错误描述**
在未打开yu的情况下，双击一个markdown文件，要不然就是打开之前打开过的文件,要不然就是空白的页面，每次的都再双击markdown文件，才能正常打开

**Comment by hemashushu** [comment]
已知释，谢谢反馈!

**Comment by hemashushu** [comment]
@wangmingquan 新版本 0.5.3 已释出，已经修复了这个问题，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
