### ISSUE TITLE
拖动窗口标题栏取消最大化失败

### ISSUE THREAD

**Issue by 777Arch** [ivarptr/yu-writer.site#303]
Windows 7 中，
在软件界面已经最大化的情况下，鼠标拖动标题栏取消最大化时界面会闪烁，同时无法达到取消最大化的目的，同时，最大化时右边中间显示的层叠窗口指示图标变为了单窗口图标。如下所示：
![image](https://user-images.githubusercontent.com/7379015/43063827-9f6a3b44-8e8f-11e8-8b27-ea0eac93966c.png)

经过测试，双击标题栏、点击最大化图标都可以正常最大化、非最大化窗口。

**Comment by hemashushu** [comment]
是的，使用拖动标题栏方式 `取消最大化窗口` 代码有 bug，谢谢反馈! 
p.s. same as #279

**Comment by hemashushu** [comment]
@Mlearn 新版本 0.5.3 已经修复了这个问题，这个 issue 我先关闭哈，如有问题欢迎随时问。
