### ISSUE TITLE
文档列表栏会自己弹出

### ISSUE THREAD

**Issue by 777Arch** [ivarptr/yu-writer.site#304]
Windows 7/ Mac
在隐藏文档库和文档列表栏的情况下，在编辑栏中编辑，鼠标划选文字的时候，有时候（偶发，没有确定发生条件）会把文档列表栏给拖出来。。。

**Comment by hemashushu** [comment]
嗯，这个应该是触控板手势（在编辑区空白地方左划或者右划）引起的 “显示/隐藏 文档库” 和 “显示/隐藏 文档列表” 操作，我检查一下是不是有 bug 在里面，谢谢反馈！

**Comment by hjings** [comment]
![image](https://user-images.githubusercontent.com/41150957/43358213-758eb27a-92c0-11e8-9796-9828ef789a0b.png)

将鼠标从左到右移动到这个位置的时候，光标会变成拖动的形状，点一下或拖动则会把文件列表拖出来，而且此时还是处于distraction-free mode

**Comment by hemashushu** [comment]
@Mlearn @hjings 新版本 0.5.3 已经修复了这个问题，这个 issue 我先关闭哈，如有问题欢迎随时问。
