### ISSUE TITLE
文本选择与回车时的一个小Bug

### ISSUE THREAD

**Issue by ghost** [ivarptr/yu-writer.site#309]
**Platform/操作系统类型**
Windows

**OS version/操作系统版本**
Windows 10 1709, 1803, ...

**Application version/应用程序的版本号**
0.5.2

**Describe the bug/错误描述**
选中一段文本（好像无论多少），并点击这段选中的文本的某一端，并回车，这段文本会被回车覆盖掉

**Screenshots/截图**
选中
![n tl bgcl vlpicq6rc](https://user-images.githubusercontent.com/34027391/43471016-97310f8c-951c-11e8-82ef-8e9855804802.png)
点击一端
![diq 6 jrk0 tp n nu _a](https://user-images.githubusercontent.com/34027391/43471025-9a567350-951c-11e8-8e18-2692eb460539.png)
回车
![_ ml ozfjlz5n n q8j_a8t](https://user-images.githubusercontent.com/34027391/43471030-9be7018a-951c-11e8-8e62-e7d4aaed3b9d.png)

____

**还有一个问题**
当软件最大化时，没办法向四个方向上拖动（使它占据一半的屏幕时），拖动时会闪一下并保持最大化

____
**提个建议**
输出的pdf带书签（可能不切实际），不然每次更新文件输出的pdf都要自己手动设置书签，放到kindle上看笔记没书签简直要死

**Comment by ghost** [comment]
一个挺影响操作的BUG就是文档库和文档列表是隐藏了，但通过拖动右侧调节宽窄的功能还在最上层，一不小心拖动到了这两个隐藏的拖动条，文档库或文档列表就会弹出来，但显示的是隐藏了。
操作就是把文档库和文档列表都隐藏，鼠标从左向右横向滑动，鼠标划到与文档库和文档列表各自宽窄相同的位置时就会变成可拖动的样子

**Comment by hemashushu** [comment]
收到，除了书签功能，其他 bug 都会在下次小版本更新是修复，谢谢反馈！

**Comment by ghost** [comment]
删除键也会出现跟回车键类似的效果，符号键好像暂未出现这类问题

**Comment by hemashushu** [comment]
是的，backspace/delete/tab/enter 等键因为共用同一个自动完成模块，所以它们都有这个问题，而普通字符用的是另外一个模块处理上下文感知的，所以就避免了。0.5.3 已经修复，过几天发布。谢谢补充反馈！

**Comment by ghost** [comment]
文件导出好像有问题，我以A5格式导出，得到的是A4的pdf

**Comment by hemashushu** [comment]
已找到 bug，下个小版本会修复，感谢反馈！

**Comment by ghost** [comment]
有序列表：
每当我写完写完一行会车时，序号并非出现在下一行开头，而是该行末尾
按ctrl+z键可以让它回到下一行
问题应该是一次按键连续进行了两次操作：第一次，换行建立序号；第二次，换行被删除，序号回到上一行
ctrl+z键撤销了第二次操作
___
一次按键连续进行了两次操作好像还出现在其他地方，想不起来了

**Comment by hemashushu** [comment]
好的，我检查一下，谢谢反馈！

李啸昆 <notifications@github.com> 于 2018年8月13日周一 上午11:34写道：

**Comment by hemashushu** [comment]
@yurjane 新版本 0.5.3 已释出，已经修复了如下问题：
1. 回车覆盖
2. 最大化后无法拖动恢复大小
3. 隐藏列表仍能被拖动
4. 文件导出的纸张大小错误
5. 有序列表新项目出现在行为

欢迎下载试用，如有问题欢迎随时问。至于 pdf 书签这个功能会在以后某个大版本加上，那么这个 issue 我先关闭哈。
