### ISSUE TITLE
跳转某包含大写字母的标签，预览页点击不会跳转。

### ISSUE THREAD

**Issue by a1thwn** [ivarptr/yu-writer.site#310]
**Platform/操作系统类型**
 Windows 和macOS

**OS version/操作系统版本**
Windows 10 
macOS 10.13.6

**Application version/应用程序的版本号**
0.5.2

**Describe the bug/错误描述**
    添加链接到当前文档某标签时，如果要跳转到的标签为“#附录A”（即中文+大写字母格式），对应命令：[详见附录A](#附录A)，点击链接没反应，如果把标签换成是“##附录1”（即中文或中文+数字格式），对应命令：[详见附录1](#附录1)，则没有问题，能跳转到对应位置。
    我试了其它的组合唯独包含大写字母的就不能跳转。

**Comment by hemashushu** [comment]
@althwn 是的，文档的名称、章节的名称，会经过 slugify 转化成简化的 URL，比如大写会转成小写，符号（比如 %，* 等符号）会被转成 `-` 号，具体的转换规则请参阅 《使用手册/Manual》的 B01 当中的 1.2.2。
如果不太熟悉 slugify 规则，可以使用工具栏的 "链接" 按钮帮助生成正确的链接。
谢谢反馈！

**Comment by hemashushu** [comment]
@althwn 新版本 0.5.3 已释出，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
