### ISSUE TITLE
流程图是不是不支持？

### ISSUE THREAD

**Issue by ghost** [ivarptr/yu-writer.site#312]
**Platform/操作系统类型**
macOS? Windows? or Linux?

**OS version/操作系统版本**
macOS 10.13, 10.14, ...
Windows 10 1709, 1803, ...
Ubuntu 16.04, 18.04 ...

**Application version/应用程序的版本号**
x.y.z

**Describe the bug/错误描述**

**To Reproduce/如何重现该错误 （如果错误描述能说明清楚则忽略并删除该小节）**

1. xxx
2. yyy
3. zzz

**Screenshots/截图（如果截图能帮助描述问题的话则提供，不需要的则忽略并删除该小节）**

**Comment by ddkk3000** [comment]
MD官方协议包括流程图吗？不包括吧，这个需要Hack

**Comment by ghost** [comment]
作者说要到0.7版本了

**Comment by hemashushu** [comment]
以后会支持，虽然有现成的组件，不过有很多地方需要修改才能适配到 yu，特别是流程图的外观样式，需要重新做一套皮肤，所以需要较多的时间才能完成。0.6 版要把现有未完成的功能补完，所以流程图只能放在 0.7 版以后了。
