### ISSUE TITLE
有其他的绑定Licensing机制，不要让便携（绿色）版变得蹩手蹩脚么？

### ISSUE THREAD

**Issue by ddkk3000** [ivarptr/yu-writer.site#313]
否则还是0.4.4好用啊，囧

**Comment by hemashushu** [comment]
绿色版？是指未注册激活的版本吗？现在的 0.5 版未注册时除了不能换皮肤之外，实际上没有限制什么功能。

**Comment by ddkk3000** [comment]
??我最喜欢你的“夜晚模式”了，拷到u盘里都不能给人吹了，因为“没注册”。要不你买断性的卖皮肤吧？功能0.4.4就够我用，够我吹了，??

q( ′* o *′ )q? lixiaozhe.com

________________________________

**Comment by hemashushu** [comment]
哦，明白，是说便携版对吧，因为现在的注册机制是上个世纪的那种非联网的纯单机本地激活机制，所以注册码跟机器绑定在一起了，简单来说就是注册了机器，而不是注册了软件副本。

这种机制对于便携版来说，缺点是在某台机器上注册了再拿到另一台机器上使用就变成“未注册”状态了，但也有一个比较隐晦的“优点”，就是如果某一个人在目标机器上注册过了，则所有（拿着便携版）来到这台机器上使用的都变成 “已注册” 了。哈哈。

**Comment by ddkk3000** [comment]
要达到这个优点，需要yu writer像windows一般普及啊??

q( ′* o *′ )q? lixiaozhe.com

________________________________

**Comment by neroxps** [comment]
@ivarptr 要不尝试走 Microsoft store？

**Comment by hemashushu** [comment]
会的，到正式版时会有 store 版

MarkDownPhotos <notifications@github.com> 于 2018年8月13日周一 上午10:44写道：

**Comment by ddkk3000** [comment]
你不要搞store版本了～uwp版本，天啊，那不得好几年。

q( ′* o *′ )q? lixiaozhe.com

________________________________

**Comment by ghost** [comment]
store版本=uwp版本？？可以看看Evernote，store版本=官网下载的，没差。
不过Microsoft store的速度不敢恭维。
steam会比较好，但完美的SteamCN？？怕怕

**Comment by ddkk3000** [comment]
??没用过那个软件，也没在那里面买过软件。

难道微软提供激活技术吗？


________________________________

**Comment by ghost** [comment]
![y9ty 4 6c_ v 8j7 ss7k 6](https://user-images.githubusercontent.com/34027391/44243727-43268680-a203-11e8-871a-316dde6ffaa9.png)
我是看不出差别
微软提供激活技术？？不知，也没买过
steam提供激活技术（主要都是买断制），还有完整的生态包括社区，反馈，创意工坊（玩家上传的第三方插件，如果作者老哥有条件的话可以考虑下第三方插件的接口），MAC、Linux、Windows全平台包含
可完美和steam搞了个SteamCN，作者老哥可以先观望观望

**Comment by ddkk3000** [comment]
我不用印象笔记。话说你都用印象笔记这种重量软件了，你干嘛还用yu writer？

________________________________
╭( ′• o •′ )╭☞ lixiaozhe.com

发件人： 李啸昆<mailto:notifications@github.com>
发送时间： 2018-08-17 10:08
收件人： ivarptr/yu-writer.site<mailto:yu-writer.site@noreply.github.com>
抄送： ddkk3000<mailto:lixiaozhe@live.com>; Author<mailto:author@noreply.github.com>
主题： Re: [ivarptr/yu-writer.site] 不能卖贵一点，或者想出其他的绑定Licensing机制，不要让绿色版变得蹩手蹩脚么？ (#313)

[y9ty 4 6c_ v 8j7 ss7k 6]<https://user-images.githubusercontent.com/34027391/44243727-43268680-a203-11e8-871a-316dde6ffaa9.png>
我是看不出差别
微软提供激活技术？？不知，也没买过
steam提供激活技术（主要都是买断制），还有完整的生态包括社区，反馈，创意工坊（玩家上传的第三方插件，如果作者老哥有条件的话可以考虑下第三方插件的接口），MAC、Linux、Windows全平台包含
可完美和steam搞了个SteamCN，作者老哥可以先观望观望

**Comment by ghost** [comment]
额(⊙o⊙)…
以前用Evernote，但Markdown更适合程序员（大雾），纯手敲
我还用过OneNote，可文件库因为同步炸了几回，放弃了
Evernote是因为不好本地化（我还是更喜欢买断制）
毕竟以后冲着Surface去，我就不太需要移动端的同步化
输出的PDF我可以直接放到Kindle上看
Evernote现在只是我用来记录一些突发奇想的工具

**Comment by ddkk3000** [comment]
“易码”推荐给你
我不觉得surface可用。看你自己了。

________________________________
╭( ′• o •′ )╭☞ lixiaozhe.com

发件人： 李啸昆<mailto:notifications@github.com>
发送时间： 2018-08-17 10:36
收件人： ivarptr/yu-writer.site<mailto:yu-writer.site@noreply.github.com>
抄送： ddkk3000<mailto:lixiaozhe@live.com>; Author<mailto:author@noreply.github.com>
主题： Re: [ivarptr/yu-writer.site] 不能卖贵一点，或者想出其他的绑定Licensing机制，不要让绿色版变得蹩手蹩脚么？ (#313)

额(⊙o⊙)…
以前用Evernote，但Markdown更适合程序员（大雾），纯手敲
我还用过OneNote，可文件库因为同步炸了几回，放弃了
Evernote是因为不好本地化（我还是更喜欢买断制）
毕竟以后冲着Surface去，我就不太需要移动端的同步化
输出的PDF我可以直接放到Kindle上看
Evernote现在只是我用来记录一些突发奇想的工具

**Comment by hemashushu** [comment]
license 问题统一到 https://github.com/ivarptr/yu-writer.site/issues/318 ，当前这个 issue 我先关闭哈。
