### ISSUE TITLE
兄弟，什么时候出linux版本呀

### ISSUE THREAD

**Issue by anoxia** [ivarptr/yu-writer.site#316]
**Platform/操作系统类型**
Linux

啥时候出linux版本咧？

**Comment by hemashushu** [comment]
@Anoxia 很抱歉，7 月中到现在一直很忙很忙，Yu Writer 的开发进度非常缓慢，现在连紧急修复 bug 的 0.5.3 版都还在积压着 😂，linux 分支的开发进度也同样积压着。（摊手）

**Comment by anoxia** [comment]
哦，等你，加油，加油，加油。
