### ISSUE TITLE
Yu Writer 太赞了，加油！

### ISSUE THREAD

**Issue by chixiang** [ivarptr/yu-writer.site#32]
在家用 Mac，好用的 Markdown 编辑器一大堆；到了办公室只能用 Windows，苦苦寻觅了好久也没有一款用着舒服的 Markdown 编辑器，一款都没有。
直到偶尔发现了 Yu Writer，刚刚启动软件看到界面，就是他了！非常漂亮，希望能够继续加油。
另外再提一点建议，最近因为工作需要一直在用马克飞象画图，Yu Writer 能否也支持 flow 和 sequence 图？用 Markdown 画流程图和时序图真的是很方便。
不胜感激！我会一直支持 Yu Write 的。

**Comment by hemashushu** [comment]
@chixiang 谢谢你的鼓励！流程图、时序图等可能会在 0.7.x 版本加上。

**Comment by chixiang** [comment]
非常感谢！

**Comment by heytxz** [comment]
Please close the issue 😃

**Comment by Dang-h** [comment]
# 简直完美！！   

**找的我好苦！支持！！！_YU Writer_完美的解决了我想要的！**

**Comment by lisi2016** [comment]
我现在发现的行内公式不能正常使用。

**Comment by hemashushu** [comment]
@lisi2016 是指无法渲染吗？因为单美元符号很容易被误解，所以 0.5.3 默认没有打开解析它的选项，可以用 mathjax 推荐的 \\(...\\) 来代替，比如 \\(E=mc^2\\)，如果还是比较喜欢用单美元符号，也可以在设置里勾选上它。
