### ISSUE TITLE
win64版本错误

### ISSUE THREAD

**Issue by Olld47** [ivarptr/yu-writer.site#320]
**Platform/操作系统类型**
Windows

**OS version/操作系统版本**

Windows 10 1709

**Application version/应用程序的版本号**
0.5.2

**Describe the bug/错误描述**
从上个版本升级后，出现了这个问题，重启电脑也也不行
![snipaste_2018-08-17_23-09-28](https://user-images.githubusercontent.com/22239747/44273825-1dd16100-a273-11e8-968d-6cb386bdaffc.png)

**Comment by hemashushu** [comment]
@Olld47 根据提示应该是有某些配置文件损坏了，可以尝试手动删除配置文件，位置：

`C:\Users\YOUR_NAME\AppData\Roaming\Yu Writer\config`
以及
`C:\Users\YOUR_NAME\AppData\Roaming\Yu Writer`

找到里面以 JSON 结尾的文件，删除之（注意如果是已注册，保留好 licensexxx.json 这个授权文件）再重启程序即可。

下个版本（即 0.5.3）会修复这种因配置文件错误而导致程序启动不了的问题。
抱歉回复晚了，谢谢反馈！

**Comment by hemashushu** [comment]
@Olld47 新版本 0.5.3 已释出，已经修复了这个问题，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
