### ISSUE TITLE
文件夹名字过长，在文档栏被遮挡

### ISSUE THREAD

**Issue by vyan13** [ivarptr/yu-writer.site#323]
![1](https://user-images.githubusercontent.com/32487910/44374167-88a6c480-a51f-11e8-967b-c38dc118609e.png)

**Comment by hemashushu** [comment]
收到，谢谢反馈！

**Comment by hemashushu** [comment]
@vuyzan 新版本 0.5.3 已经修复了这个问题，这个 issue 我先关闭哈，如有问题欢迎随时问。
