### ISSUE TITLE
一点自己的爱好

### ISSUE THREAD

**Issue by guomuye** [ivarptr/yu-writer.site#33]
感谢作者提供的编辑器，theme风格非常good。对于library那一栏还是不太习惯。=。=主要是之前一直用atom和vs喜欢那种项目展开式的风格。请问下是否支持切换左侧llibrary显示风格

**Comment by hemashushu** [comment]
@guomuye 下一版会把 library 单独出来形成一个侧栏，同时还会有 Favorite 收藏高频的文件夹，但完全的树形暂时还不会加上，到时再看看能否满足需求，谢谢你的意见。

**Comment by hemashushu** [comment]
@guomuye 版本 0.5 已经加上树形列表，欢迎下载试用，如果有问题欢迎随时反馈，这个 issue 我先关闭咯。
