### ISSUE TITLE
不支持这个格式的链接显示：<url>

### ISSUE THREAD

**Issue by nmcoo** [ivarptr/yu-writer.site#332]
**Platform/操作系统类型**
Windows

**OS version/操作系统版本**
Windows 7

**Application version/应用程序的版本号**
0.5.3

**Describe the bug/错误描述**
不支持这个格式的链接显示：<https://ivarptr.github.io/yu-writer.site>

**To Reproduce/如何重现该错误 （如果错误描述能说明清楚则忽略并删除该小节）**

**Screenshots/截图（如果截图能帮助描述问题的话则提供，不需要的则忽略并删除该小节）**
![](http://ww1.sinaimg.cn/large/9b84e6acgy1fup8zuvg46j20vo08bb29.jpg)

**Comment by hemashushu** [comment]
请问是在程序设置里启用了 HTML 解析功能吗？
如果启用了 HTML 标签，大于号 和 小于号 需要写成 &gt; &lt;
建议在有需要的文档才打开 html 解析，或者为特定的库打开 html 解析（这个设置会在以后添加，目前只能手动添加）

**Comment by nmcoo** [comment]
OK了，确实是开了「解析 HTML 标签」，谢谢！
