### ISSUE TITLE
spotlight里没有列出这个程序

### ISSUE THREAD

**Issue by felixim** [ivarptr/yu-writer.site#353]
**Platform/操作系统类型**
macOS

**OS version/操作系统版本**
macOS 10.12

**Application version/应用程序的版本号**
0.5.3

**Describe the bug/错误描述**
spotlight里没有列出这个程序
<img width="281" alt="2018-09-08 20 44 21" src="https://user-images.githubusercontent.com/30134705/45254266-16036900-b3a8-11e8-88ac-d001ee685513.png">

**To Reproduce/如何重现该错误 （如果错误描述能说明清楚则忽略并删除该小节）**

**Screenshots/截图（如果截图能帮助描述问题的话则提供，不需要的则忽略并删除该小节）**

**Comment by hemashushu** [comment]
@felixim 可能是 spotlight 的索引有点异常，试试重建 spotlight 索引。有图形界面操作方法，也有命令行方法参考：

https://www.makeuseof.com/tag/cant-find-mac-apps-spotlight-fix/
https://support.apple.com/en-us/HT201716

<img width="732" alt="screen shot 2018-09-10 at 10 11 27 am" src="https://user-images.githubusercontent.com/394223/45272855-42230500-b4e2-11e8-996e-1f4250716354.png">

**Comment by felixim** [comment]
修复成功, 多谢~
