### ISSUE TITLE
编辑页面插入代码后高亮的异常

### ISSUE THREAD

**Issue by kaleai** [ivarptr/yu-writer.site#361]
**Platform/操作系统类型**
Windows

**Application version/应用程序的版本号**
最新

代码加三个点后，下文的高亮会乱掉：

![image](https://user-images.githubusercontent.com/9552155/45604309-93dd0980-ba65-11e8-9f01-5d71e5cdc6fc.png)

**Comment by kaleai** [comment]
## 配置（库版本1.+）

### 1. 在build.gradle中配置QQ的key  

```java
defaultConfig {
    applicationId "xxx.xxx.xxx" // 你的app包名
    
     // tencent+你的AppId
    manifestPlaceholders = ["tencentAuthId": "tencent123456"]
}
```

### 2. 在使用功能前配置常量

 ```java
SlConfig config = new SlConfig.Builder()
            .debug(false)
            .appName("Your App Name")
            .picTempFile(null) // 缓存缩略图的目录，如无特殊要求可以是null
            .qq(qq_app_id, qq_scope)
            .weiBo(weibo_app_key, weibo_redirect_url, weibo_scope)
            .weiXin(weixin_app_id, weixin_secret)
            .build();

ShareLoginSDK.init(this, config);
```

**Comment by hemashushu** [comment]
@tianzhijiexian 可能是因为某一行的 '```' 符号前面多了一个空格，删除它即可。我把上面的源码复制到 yu writer 后删除第 18 行前面的空格后显示正常了，如下图：

<img width="1378" alt="screen shot 2018-09-18 at 5 24 53 am" src="https://user-images.githubusercontent.com/394223/45651223-562ebe00-bb03-11e8-8459-937f6ee32618.png">

**Comment by kaleai** [comment]
可以使用了，谢谢你。

如果可以的话，可以考虑下对前后的空格做个容错哈，有时候复制粘贴的时候就可能会加上了，当然这只是一个建议了。

**Comment by hemashushu** [comment]
@tianzhijiexian 输出渲染部分已经做了容错，即导出 HTML/PDF、预览、即时预览这三个地方已经容错，但编辑区因为是语法问题所以保留严格的语法检查会比较好，复制源如果是 HTML，粘贴时 &lt;pre&gt; 应该能正确地转成 \```...\``` 代码块，如果是前面多了一个空格，不知道复制源是否 markdown/txt 格式？
