### ISSUE TITLE
编辑hexo文章时极为卡顿

### ISSUE THREAD

**Issue by flyhero** [ivarptr/yu-writer.site#364]
**Platform/操作系统类型**
macOS

**OS version/操作系统版本**
macOS 10.13.1 

**Application version/应用程序的版本号**
0.5.3

**Describe the bug/错误描述**
无明显错误，但是极为卡顿

**To Reproduce/如何重现该错误 （如果错误描述能说明清楚则忽略并删除该小节）**

16G内存，其他应用并不卡顿
在自带的文章中编辑，很流畅，但当加载hexo里的文章时卡，编辑时更卡。有些文章卡，有些却不。

**Comment by hemashushu** [comment]
@flyhero 你好，可能是跟 #363 一样的问题，详细请点击前面这个链接，谢谢反馈！
