### ISSUE TITLE
复制代码后粘贴格式错乱

### ISSUE THREAD

**Issue by kaleai** [ivarptr/yu-writer.site#369]
**Platform/操作系统类型**
windows

**OS version/操作系统版本**
windows最新

**Application version/应用程序的版本号**
beta

**Describe the bug/错误描述**

粘贴代码和md文档中的文字后复制到yu中会出现缩进格式错乱的情况，毕现。

**To Reproduce/如何重现该错误 （如果错误描述能说明清楚则忽略并删除该小节）**

复制的文本如下：

        // 初始该库的基础常量
        ShareLoginLib.init(this, getString(R.string.app_name), null, BuildConfig.DEBUG);

        // 初始化第三方平台的信息
        ShareLoginLib.initPlatforms(
                MapBuilder.of(
                        QQPlatform.KEY_APP_ID, qq_app_id,
                        QQPlatform.KEY_SCOPE, qq_scope,

                        WeiBoPlatform.KEY_APP_KEY, weibo_app_key,
                        WeiBoPlatform.KEY_SCOPE, weibo_scope,
                        WeiBoPlatform.KEY_REDIRECT_URL, weibo_redirect_url,

                        WeiXinPlatform.KEY_APP_ID, weixin_app_id,
                        WeiXinPlatform.KEY_SECRET, weixin_secret
                ),
                Arrays.asList(
                        QQPlatform.class,
                        WeiBoPlatform.class,
                        WeiXinPlatform.class)
        );
---

**粘贴后的效果：**

编辑区域的效果：

![image](https://user-images.githubusercontent.com/9552155/45912498-09c1e600-be55-11e8-90e3-56e6f15be7e2.png)

预览区域的效果：

![image](https://user-images.githubusercontent.com/9552155/45912508-4d1c5480-be55-11e8-93e0-ee26709468be.png)

**Comment by hemashushu** [comment]
@tianzhijiexian 请问是从 idea 复制过来的代码吗？可以试试粘贴时使用“粘贴为纯文本”，具体原因见 #366

**Comment by kaleai** [comment]
“粘贴为纯文本”后显示正常，谢谢您的回复。
