### ISSUE TITLE
笔记移动功能缺失

### ISSUE THREAD

**Issue by alphaAI-stack** [ivarptr/yu-writer.site#377]
mac版本

我在libraries下建立了a，b两个目录
现在在a目录写了一个文章，话说如何移动弄到b目录，貌似没有这个功能

**Comment by alva-lin** [comment]
win版本在文件系统中找到对应目录，手动移动过去，然后重启下程序就可以了。

没试过mac版本，不过你可以试试

**Comment by alphaAI-stack** [comment]
手动可以移动，最好是软件能支持拖动，不过我看了作者的手册看样子要支持
