### ISSUE TITLE
Bug反馈:预览模式下无法实时切换Document Style

### ISSUE THREAD

**Issue by Coooolinz** [ivarptr/yu-writer.site#38]
平台:win10
版本V0.4.4

问题描述:打开文档默认的「Welcome」文档，read mode，选择切换主题，无法实时切换。
关闭read mode后再打开，主题切换为之前操作但没成功的主题。

问题出现概率:打开默认的Welcome，其他文档好像没问题

**Comment by hemashushu** [comment]
@Coooolinz 这里说的主题是指“style“吗？如果是的话那是因为随程序附带的那几个帮助文档（包括 Welcome）是只读的，所以没法编辑，自然也没得切换 style 了。可能目前程序的提示做得不太好，谢谢你的反馈！

**Comment by Coooolinz** [comment]
那看来这个问题的过程应该描述为:

只读文档->Read Mode->Document Style当前为Default；预览样式是Default->点击Candy，选中状态无变化、预览样式无变化->关闭Read Mode->再打开Read Mode->Document Style当前改为Candy，预览样式也是Candy

**Comment by hemashushu** [comment]
@Coooolinz 哈哈，原来有这样的BUG，下次更新修正。谢谢细致的描述！

**Comment by Coooolinz** [comment]
哈哈，不客气~
这个软件的功能思路及架构个人感觉可以媲美Ulysses，希望加油完善！

**Comment by hemashushu** [comment]
@Coooolinz 新版本 0.5 已释出，欢迎下载试用，有问题欢迎随时问，这个 issue 我先关闭哈。
