### ISSUE TITLE
可以申请成为开发人员吗？

### ISSUE THREAD

**Issue by hitzhangjie** [ivarptr/yu-writer.site#394]
可以申请成为开发人员吗？现在的issues比较多，自己本人也对打造一款“贴心”、“方便”的markdown编辑器很感兴趣，之前简单了解过electron、markText的实现，对markdown语法、渲染的大致工作原理也了解。

**Comment by hemashushu** [comment]
@hitzhangjie 嗯嗯，目前 yu writer 每个小版本改动都很大，所以暂时还没有开源计划，不过很感谢你的关注！
