### ISSUE TITLE
一输入中文就闪退

### ISSUE THREAD

**Issue by ghost** [ivarptr/yu-writer.site#40]
很闹心的一个 bug ，输入法是系统自带的拼音输入法。
```
Process:               Yu Writer [4304]
Path:                  /Applications/Yu Writer.app/Contents/MacOS/Yu Writer
Identifier:            com.github.yu-writer
Version:               0.4.4 (0.4.4)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Yu Writer [4304]
User ID:               501

Date/Time:             2017-08-29 08:43:45.449 +0800
OS Version:            Mac OS X 10.12.6 (16G29)
Report Version:        12
Anonymous UUID:        78F4803D-E693-5DD7-3824-04D6AAFF34C1


Time Awake Since Boot: 4900 seconds

System Integrity Protection: disabled

Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Trace/BPT trap: 5
Termination Reason:    Namespace SIGNAL, Code 0x5
Terminating Process:   exc handler [0]

```

**Comment by hemashushu** [comment]
@yuzenan888 是的，现在这个bug我还没法解决，一旦文档的中文超过4096个字，使用macos自带的拼音输入法就有可能会崩溃，目前的变通方法是先使用第三输入法（比如鼠须管），或者等待上游（google chromium）修复，又或者到正式版之后我尝试用另外的方法实现编辑框。谢谢反馈！

**Comment by ghost** [comment]
谢谢回复，请问这软件跟Google Chromium有啥关系呢？

**Comment by hemashushu** [comment]
@yuzenan888 因为这软件是构建在 Electron （Github Atom Electron）之上，而 Electron 则是构建在 Google Chromium 之上，所以 Chromium 的 bug 也被延续下来了。

验证：在 Google Chrome/Chromium 浏览网页时，在有文本框的地方先粘贴 4k 多中文字，这时如果用 mac 自带输入法再输入一个中文字，也会崩溃闪退。

**Comment by ghost** [comment]
谢谢解答。刚才用 Google Chrome 果然有这个问题。话说如果谷歌不修复这个问题的话您就只能放弃 Chromium 了么？

**Comment by hemashushu** [comment]
不会，其实还是有变通的方法，比如自己画编辑框，将用户输入的内容拦截下来再显示在自己画的编辑框里，只是工作量相当大。

2017年9月4日 13:22，"Zenan Yu" <notifications@github.com>写道：

**Comment by ghost** [comment]
好的！您开发的这款 Markdown 编辑器挺不错的，既免费功能又全！如果能够尽快解决掉这个 bug 再加个中文那就完美了！非常感谢您的回复。

**Comment by gaojijun** [comment]
遇到了同样的问题，果断换输入法

**Comment by hemashushu** [comment]
@yuzenan888 @gaojijun 新版本 0.5 已释出，欢迎下载试用，输入中文闪退这个 bug 应该是彻底解决了，如有问题欢迎随时问，这个 issue 我先关闭哈。

**Comment by ghost** [comment]
谢谢，等了整整一年！
