### ISSUE TITLE
不知道左侧的目录是否有树状显示

### ISSUE THREAD

**Issue by sikenali** [ivarptr/yu-writer.site#41]
一直在linux下使用这个 https://www.typora.io/ 希望可以帮助到你。

后续linux出来后，可以上架深度商店，以后会有打赏功能

http://appstore.deepin.org/

**Comment by sikenali** [comment]
可以顺便新增一个英文页面站点，提供捐助，我这边可以安利歪果仁，望采纳。

**Comment by zhenghualiang** [comment]
+1
如果可以象Atom那样使用快捷键Ctrl+/实现隐藏与调用，然后通过方向键实现选择，就可棒了！
期待！！！

**Comment by hemashushu** [comment]
@jingle0927 @zhenghualiang 非常感谢！！现在我也在纠结中要不要添加一个树型侧栏   😁

**Comment by sikenali** [comment]
主要是我是md重度使用者，还是希望有树型结构显示的 @ivarptr

**Comment by hemashushu** [comment]
@jingle0927 @zhenghualiang 新版本 0.5 已释出，已加上树形列表，欢迎下载试用，因为开发 0.5 版 linux 版跳票了一年，现在在收尾中，大概九月底或者十月初完成。如有问题欢迎随时问，这个 issue 我先关闭哈。
