### ISSUE TITLE
Vim mode can't be used

### ISSUE THREAD

**Issue by erickguan** [ivarptr/yu-writer.site#418]
**Platform/操作系统类型**
macOS

**OS version/操作系统版本**
macOS 10.14.1 (18B75)

**Application version/应用程序的版本号**
0.5.3

**Describe the bug/错误描述**
Vim mode can't be enabled in settings.

**To Reproduce/如何重现该错误 （如果错误描述能说明清楚则忽略并删除该小节）**

1. Go to settings/professionals
2. Select VIM mode. It can't be enabled.

**Comment by hemashushu** [comment]
@fantasticfears All features marked with asterisks (*) are still under development and will be completed in a future release. Thank you for your feedback

**Comment by erickguan** [comment]
👍
