### ISSUE TITLE
厉害了！图片导出功能什么时候可以出来啊？

### ISSUE THREAD

**Issue by JayShna** [ivarptr/yu-writer.site#42]
我之前一直在Bear和Ulysses中间犹豫不决，Bear的确非常简洁非常美，而且有优雅的图片导出功能，但是功能上面没有Ulysses强大，所以我每次都是Bear写一些碎片性的文字，Ulysses写大型文字。但是如果稍长的文字需要导出给别人的话，我就需要先用Ulysses编辑，然后粘贴到Bear再导出图片。
所以当我看到Yu Writer这一款软件，我非常的高兴，这几乎融合了我对Bear和Ulysses的所有念想，而且还有很多独创的功能，如果收费的话我也会第一时间买下来。
希望图片导出功能可以早一些做出来，支持你。

**Comment by hemashushu** [comment]
@JayShna 感谢支持！导出图片等功能会在 0.6.x 版完成（即下下次minor版本更新）

**Comment by hemashushu** [comment]
@JayShna 新版本 0.5 已释出，加入了导出图片功能，但目前还没全部完成（仅可导出第一页），也欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
