### ISSUE TITLE
流畅性有一些问题

### ISSUE THREAD

**Issue by RexkentZheng** [ivarptr/yu-writer.site#424]
**Platform/操作系统类型**
macOS

**OS version/操作系统版本**
macOS 10.14.1 (18B75)

**Application version/应用程序的版本号**
0.5.3

**Describe the bug/错误描述**
当前只有一个文档库，文档库中有五篇文章，平均每篇文章15K字，然后使用起来十分卡顿，浏览没有问题，打字的话需要等待，较长的时间的等待字才能出来，删除的话也是一样，体验有点差

**Others/题外话**
知道作者开发软件很辛苦，我本身也是一名研发，但是这卡顿的问题实在很影响使用。笔记本性能没啥问题，使用别的软件都没有任何输入卡顿的现象，感觉很诡异，希望作者可以解决下这个问题，谢谢

**Comment by hemashushu** [comment]
@RexkentZheng 好的，基本功能写完后会着重优化一下运行速度，谢谢你的反馈！ 

see also #422
