### ISSUE TITLE
软件重启后无法识别Jekyll文件夹

### ISSUE THREAD

**Issue by Nickszy** [ivarptr/yu-writer.site#425]
在文档库中加入含有index.html 的文件夹后，能够识别出是博客，但软件重启后无法识别，会在_post中加入.resource的文件夹。

**Comment by hemashushu** [comment]
请问是通过 “链接到静态博客” 来添加的博客文件夹的吗？参考这个 #423 ，期待你的进一步反馈。

**Comment by Nickszy** [comment]
已按“链接到静态博客”操作，文档库能成功识别，且与`_posts`同目录产生`yulib.resource`文件夹。但本地运行`Jekyll serve`后`_site`文件夹中依旧会产生`xxxx.resource-commit.json`的文件。

**Comment by hemashushu** [comment]
@Nickszy 明白，我稍后会检查一下，感谢反馈！
