### ISSUE TITLE
改进和提供高亮

### ISSUE THREAD

**Issue by 1158114251** [ivarptr/yu-writer.site#434]
首先感谢我们的开发者做出如此漂亮的工具，相比与市面上的其他工具包括国外的，这款国产工具毫不逊色。
我在使用前几个版本的时候喜欢其中一款有标注文字高亮的皮肤，但是发现最新版本里面没有了，高亮是固定的黄色。希望可以把文字颜色提供出来，还有就是一些文字样式能不能单独配置。可能说的不明白，我截图：

![image](https://user-images.githubusercontent.com/13937473/49621601-2952be80-fa01-11e8-8121-28cd5417d8bc.png)
![image](https://user-images.githubusercontent.com/13937473/49621685-8cdcec00-fa01-11e8-9e0e-ffdbc3b0ad91.png)

因为单纯的黑白文字，给人的阅读感不强，所以。。。
最后：预祝这款非常人性化的工具大卖！！！！

**Comment by hemashushu** [comment]
@1158114251 哦，截图这个是之前一个叫做 `candy` 的文档样式（用在 “预览” 窗口），后来这个样式没有维护所以新版本去除了。0.8版之后会提供多一些渲染样式，谢谢反馈！
