### ISSUE TITLE
Yu Writer支持Video、Audio标签吗

### ISSUE THREAD

**Issue by tardistao** [ivarptr/yu-writer.site#446]
因为特殊情况，需要在文档中添加音频，发现在Yu Writer 添加不上，用MWeb3 试了一下可以添加。
请问Yu Writer 支持Video，Audio标签吗？

**Comment by ivarptr** [comment]
@tardisyao 可以在设置里启用 html 标签支持，或者单独在文档的 front matter 里声明启用 html 标签，然后通过 <audio> 标签插入 mp3，详细的参考《使用手册》的 “B08 HTML” 一章。

**Comment by hemashushu** [comment]
@tardistao 可以在设置里启用 html 标签支持，或者单独在文档的 front matter 里声明启用 html 标签，然后通过 <audio> 标签插入 mp3，详细的可以参考《使用手册》的 “B08 HTML” 一章。
