### ISSUE TITLE
感觉MarkDown语法支持不完整：比如不支持使用反斜杠添加星号（*）

### ISSUE THREAD

**Issue by QuentinHsu** [ivarptr/yu-writer.site#452]
**Platform/操作系统类型**
Windows

**OS version/操作系统版本**
Windows 10 1809

**Application version/应用程序的版本号**
0.5.3

**Describe the bug/错误描述**
不支持使用反斜杠添加普通符号
若是支持的话，是能添加以下符号的
\   反斜线
`   反引号
\*   星号
_   底线
{}  花括号
[]  方括号
()  括弧
\#   井字号
\+   加号
\-   减号
.   英文句点
!   惊叹号

**Screenshots/截图（如果截图能帮助描述问题的话则提供，不需要的则忽略并删除该小节）**
![image](https://user-images.githubusercontent.com/21162238/50677336-3e3c6500-1034-11e9-8d9a-598130a474cf.png)

**Comment by hemashushu** [comment]
@QuentinHsu 收到，目前编辑器的语法解析有很多错误，谢谢反馈。

ps “即时查看” 和 “预览” 是能正常解析。
