### ISSUE TITLE
如何将我的Library目录配置到其他路径

### ISSUE THREAD

**Issue by Andark** [ivarptr/yu-writer.site#453]
您好，我想把我的Library目录配置到其他路径，比如：OneDrive在我本地的一个路径下：D:\Home\OneDrive。这样，我写的所有内容都可以同步到OneDrive中了。日后我切换电脑，或者电脑重装系统，我的文档都不会丢。

**Comment by vyan13** [comment]
现在微软网盘好像可以直接同步本地 文档 文件夹下的文件吧。

**Comment by Andark** [comment]
不好意思，我之前没有注意，在Libraries功能里面本身就有“链接外部目录”的功能。谢谢啦。
