### ISSUE TITLE
win10无法使用

### ISSUE THREAD

**Issue by QimengSun** [ivarptr/yu-writer.site#47]
![image](https://user-images.githubusercontent.com/22323520/29968176-02aec154-8f4d-11e7-9aec-4ce714a2bb57.png)

**Comment by hemashushu** [comment]
@QimengSun 试试把可执行文件拖进命令提示符窗口，在命令模式下启动它，然后把错误信息贴出来。谢谢

**Comment by QimengSun** [comment]
![image](https://user-images.githubusercontent.com/22323520/29974294-0264d392-8f65-11e7-8a67-ff3719d1a742.png)
`
C:\Users\sqm>"D:\yu-writer-beta-0.4.4-windows\Yu Writer\Yu Writer.exe"

C:\Users\sqm>
info: execDirectory: D:\yu-writer-beta-0.4.4-windows\Yu Writer
info: workDirectory (the Electron "resources" dir): D:\yu-writer-beta-0.4.4-windows\Yu Writer\resources
info: appDirectory: D:\yu-writer-beta-0.4.4-windows\Yu Writer\resources\app.asarinfo: appResourcesPath: D:\yu-writer-beta-0.4.4-windows\Yu Writer\resources\app.asar\src\resources                                                              info: appScriptPath: D:\yu-writer-beta-0.4.4-windows\Yu Writer\resources\app.asar\src\script                                                                    info: defaultConfigPath: D:\yu-writer-beta-0.4.4-windows\Yu Writer\resources\app.asar\src\resources\config                                                      { exec: 'D:\\yu-writer-beta-0.4.4-windows\\Yu Writer',
  workdir: 'D:\\yu-writer-beta-0.4.4-windows\\Yu Writer\\resources',              app: 'D:\\yu-writer-beta-0.4.4-windows\\Yu Writer\\resources\\app.asar',
  resource: 'D:\\yu-writer-beta-0.4.4-windows\\Yu Writer\\resources\\app.asar\\src\\resources',                                                                   script: 'D:\\yu-writer-beta-0.4.4-windows\\Yu Writer\\resources\\app.asar\\src\\script',                                                                        data: 'C:\\Users\\sqm\\AppData\\Roaming\\Yu Writer',
  config: 'C:\\Users\\sqm\\AppData\\Roaming\\Yu Writer\\config',                  cache: 'C:\\Users\\sqm\\AppData\\Local\\Yu Writer',
  library: 'C:\\Users\\sqm\\Documents\\Yu Writer Libraries' }                   info: process argv ["D:\\yu-writer-beta-0.4.4-windows\\Yu Writer\\Yu Writer.exe"]
info: app ready
info: integrity check result: true
info: create main window without specified startup file items
`

**Comment by hemashushu** [comment]
谢谢！我稍后调试一下

**Comment by hemashushu** [comment]
@QimengSun 新版本 0.5 已释出，理论上应该解决了这个问题，如果不行的话请试试增加启动参数 `--disable-gpu`
加上参数之后如下：
`"C:\Program Files\Yu Writer\Yu Writer.exe" --disable-gpu`
或者看截图。
欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。

![disable-gpu](https://user-images.githubusercontent.com/394223/44931705-32464b00-ad95-11e8-8b60-e49cd746fa60.JPG)
