### ISSUE TITLE
Yu Writer 0.6 预告

### ISSUE THREAD

**Issue by hemashushu** [ivarptr/yu-writer.site#472]
Yu Writer 0.6 预告，猪年开始我会陆续把新版本坑逐个填上，这版是一个接近正式版的版本，添加了若干个能显著提高码字效率的特性，界面也稍微调整一下，有全新的图像管理窗口和公式编辑窗口，全文搜索功能会补上，同时会发布 Linux 的 x86/64/ARM 版，后面我会每完成一个模块就追加一帖，希望大家喜欢😘

第一个截图显示的是 0.6 版将会支持编辑器窗口切分，类似大部分文本编辑器，可横向切也可竖向切，切分数量不限（如果你的显示器足够宽的话）每个分组还支持多个标签页。
Yu Writer 支持多个窗口、多个切分组、多个标签页同时编辑同一个文档，任意一个编辑框的操作实时同步，方便编辑超复杂的文档。

![0p6](https://user-images.githubusercontent.com/394223/52931642-0f7e1200-3388-11e9-9919-22419274078a.jpg)

**Comment by vyan13** [comment]
感谢作者的辛勤劳动！

**Comment by xkloveme** [comment]
加油⛽️，啥时候出个优惠码

**Comment by hemashushu** [comment]
No. 2：编辑框元素自动切换排序方向

当程序窗口比较窄，编辑框的大纲栏和即时预览栏会自动切换为竖向排列（默认是横向排列），这个新特性同时也是为了切分窗口服务，因为切分窗口后编辑框会变得比较窄，如下截图（这个例子可能比较极端，嗯嗯）

![2](https://user-images.githubusercontent.com/394223/53219118-aa812f80-3699-11e9-890e-b3e0735790aa.jpg)

**Comment by bizchina** [comment]
赶紧出新版啊 我好整个vip啊

**Comment by alphaAI-stack** [comment]
支持啊

**Comment by Coelancanth** [comment]
一个月过去了...........

**Comment by amtath** [comment]
支持呀。我主要是关心能否支持ctrl+v贴图

**Comment by bizchina** [comment]
小哥哥，你倒是发个新版啊？我准备着钱钱付VIP呢

**Comment by hemashushu** [comment]
@amtath 支持的

**Comment by hemashushu** [comment]
@bizchina 0.6版步子迈得比较大，还在奋力填坑中😭

**Comment by ylooq** [comment]
迫不及待

**Comment by lygoing** [comment]
我的心在等待，一直在等待.....

**Comment by lygoing** [comment]
@ivarptr 大佬，请问一下新版本支持粘贴图片自动将图片上传到配置的图床了吗？比如七牛或者其他的。。。

**Comment by hemashushu** [comment]
@lygoing 下一版（0.6）已经加上相关的操作界面和操作流程，不过内部代码可能要再过一个小版本才会完成，谢谢你的意见。

**Comment by lygoing** [comment]
@ivarptr 谢谢谢谢，既然如此再好不过。哈哈

**Comment by miss85246** [comment]
@ivarptr 希望在0.6的新版本中,能够在html代码标签中扩充 center   html标签,在0.5.3的版本中,可以看到 center标签被高亮显示了,但是貌似出现了渲染失败的情况,暂不清楚到底是那种情况

**Comment by miss85246** [comment]
@vuyzan 另外,希望在新的版本中支持Markdown语法 > 来进行引用,在大部分国内博客类网站中都支持> 引用语法,希望能够尽快支持 .另外,希望能够直接出隐藏文档列表的选项,并在该选项中自动同时隐藏文档库,强迫症表示要重复的两次去隐藏文档列表和文档库真的很繁琐.  而且隐藏之后希望能够自动将预览窗体大小改变等份分布, 每次隐藏完成后要自己手动拖动,很烦.

**Comment by hemashushu** [comment]
@misss85246 `<center>` 是 HTML4 时开始废弃的标签 (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/center) ，建议使用 `style="text-align"` （添加至 `<div>` 或者 `<p>`）代替。

0.6 版会有一键改变窗口布局的功能，也就是把几种布局的组合打包，通过一个（工具栏）按钮或者快捷键来切换，敬请期待。

**Comment by Wilson-G** [comment]
刚下下来试了下,感觉作者贼厉害啊,这是一个完全不同于我之前用过的任何笔记软件的一个app,居然还有vim模式! 如果能在一个app里面形成闭环的工作流,包括资料收集\todo管理\生产力输出等等就太棒了,感觉作者是有这样的野心的.

我也用过很多不错笔记的APP,比如
Agenda
   -这个APP的排版配色很体现细节和用心,特色是为笔记加了一个时间线的维度
Notion
   - 特色是Block和丰富的笔记形式, 这让文字可以非常的自由不受约束

总之我觉得如果能让用户很快上手, 形成一个好的工作流闭环,应该是能很好留存死忠用户吧. 我觉着yu writer可以借鉴一下Block的思路还有agenda的排版配色细节

**Comment by zhjiarong** [comment]
0.6版估计发布还有3个月吧

**Comment by hemashushu** [comment]
@Wilson-G 我自己是希望能够在一个地方完成资料的收集、整理以及书写文章，甚至包括向他人讲解（幻灯片）、书写计划（包括长期计划 到 立马要做、做完就删除的琐碎修订）、简单的屏幕截图和可编辑的标注等，因为这些都是日常高频率的操作，当然这只是我的愿望啦，能做完顺手的编辑功能已经很困难了，噗

**Comment by Wilson-G** [comment]
@ivarptr 对啊,这就是你在搭建一个自己的工作流嘛,很多的东西都可以在一个平台上完成,挺好的~ 我说的那些可以当做一些改进的灵感和思路呀,加油~

**Comment by houxiren** [comment]
Ctrl + V 功能已完成了吗？最近有大量收集工作，可否先放出有 Ctrl + V 功能的版本呢？感谢感谢！

**Comment by hemashushu** [comment]
@houxiren 很抱歉因为这个功能跟“附件”这整个模块关联，也就是需要整个版本升级才能使用，所以只能等0.6版出来了。

**Comment by Karonzhjr** [comment]
啥时候出0.6版本呢，期待哦

**Comment by zhjiarong** [comment]
@ivarptr 啥时候出0.6版本呢？

**Comment by serialq7ic4** [comment]
翘首以盼，另外请问0.5版本的预览有快捷键么？0.4是ctrl+r

**Comment by hemashushu** [comment]
@Karonzhjr 需要再久一点，最近进展缓慢 TAT

**Comment by hemashushu** [comment]
@chenq7an 可以点窗口右上角的主菜单按钮（三条横线的那个按钮），然后在主菜单上看到所有功能的快捷键。
0.5.x 的预览快捷键是 `Ctrl+Shift+R`

**Comment by KaiyoungYu** [comment]
持幣等待。先加watch，hiahia

**Comment by amtath** [comment]
是不是来关注下，非官方爱好者QQ群 213151779

**Comment by amtath** [comment]
时不时来关注下进度，非官方爱好者QQ群 213151779

**Comment by harrisliupsn** [comment]
@ivarptr 要是 YW 能独立完成一个完整的工作流程就太好了，我记得作者的想法是帮助写作，那么 Mac 上有一个能够将长文拆分成小模块的写作工具，叫 Scrivener，没搞错的话 Win 上有个类似的软件而且是开源的。
然后催一下 0.6，谢谢作者的努力（我注册了哦～～）

**Comment by vikiway** [comment]
关注进度ing

**Comment by iQuick** [comment]
关注进度ing
这版会有有在线注册不，希望能一次注册在能多个机器跑，穷~工资底！

**Comment by Zhaoqiu-hfut** [comment]
催催催:smile:，另外导出pdf能不能调整边距，而且我发现导出的pdf再用Adobe DC编辑，所有的小写`l`都不见了。 @ivarptr

**Comment by vyan13** [comment]
新版本请务必加上复制网络文章将图片下载到本地的功能……净网大潮浩浩汤汤，太可怕了

**Comment by Giftia** [comment]
催催催，加油💪

**Comment by sjzy137** [comment]
我是付费用户，这个账号也是为了这个软件刚注册的。希望能加快进度，毕竟我付费后换电脑了……

**Comment by hemashushu** [comment]
@sjzy137 你好，如果更换电脑导致机器码改变可以把新的机器码（email）发送给我，我会重新生成一个注册码。

**Comment by vae-0118** [comment]
希望能在写markdown源文件时，加入图片预览功能。一般的语法语义都很容看懂，唯独图片这个，如果不加预览，看上去确实麻烦。
非常感谢。

**Comment by vikiway** [comment]
加油，按捺不住来催进度，当前版本不能全局搜索太无奈了，希望可以支持直接粘贴图片

**Comment by hemashushu** [comment]
好了好了，先制作一些预告视频，一边制作一边填坑，这个帖子的后续请挪步到 https://github.com/ivarptr/yu-writer.site/issues/549

**Comment by Zhaoqiu-hfut** [comment]
哈哈，刚想回复

**Comment by Cipuzp** [comment]
期待

**Comment by skysinger** [comment]
啥时候发布0.6版本啊？等不及了
