### ISSUE TITLE
文档编写界面代码块（``` javascript）渲染错误，和预览界面不一致

### ISSUE THREAD

**Issue by xsyww** [ivarptr/yu-writer.site#475]
**Platform/操作系统类型**
windows

**OS version/操作系统版本**
Windows 10 1809

**Application version/应用程序的版本号**
0.5.3

**Describe the bug/错误描述**
文档编辑界面一旦使用 ``` 包围的代码块，相邻的两个代码块在编辑界面渲染是错误的。但是在预览界面正常。

**To Reproduce/如何重现该错误 （如果错误描述能说明清楚则忽略并删除该小节）**
直接输入以下内容就可以看到

``` javascript
    if (true) {
        var count = 3;
        // do something...
    }

    assert(count == 3, "count仍然可用");
```

### 判断一个object是不是个函数

``` javascript
    function isFunction(fn) {
        return Object.prototype.toString.call(fn) == "[Object Function]";
    }
```
**Screenshots/截图（如果截图能帮助描述问题的话则提供，不需要的则忽略并删除该小节）**

![image](https://user-images.githubusercontent.com/9280700/53137376-7fc1a900-35bd-11e9-8983-54d32bb5712b.png)

**Comment by hemashushu** [comment]
@xsyww 可能是因为第二个 \`\`\`javascript 的字母 j 前面多了一个空格，编辑框因为要语法加亮以及兼顾性能等问题所以对语法判断比较严（比如对是否有空格比较敏感），预览栏则能模糊处理大部分的写法，所以就出现了左右渲染结果不一致的情况，建议统一在 \`\`\` 后面不留空格，谢谢你的反馈！

**Comment by xsyww** [comment]
你说得对！去掉空格就可以了。谢谢！
