### ISSUE TITLE
对Mathpix的支持

### ISSUE THREAD

**Issue by iPixelOldC** [ivarptr/yu-writer.site#479]
话说大佬有没有支持Mathpix OCR的想法？就是这个https://mathpix.com/，看上去API也不很贵，要不就作为Pro用户的增值服务？比如先免费多少次，然后以后付费买。不过这个公式OCR，我暂时没什么需求....所以只是提提(*｀▽´*)

**Comment by hemashushu** [comment]
@iPixelOldC 下一个版本（0.6）我会弄一个新的公式编辑器，将会比目前纯手动输入的编辑框方便很多。至于 ocr 是很方便，但暂时先不做了，以后是可以考虑嵌入第三方的api，谢谢你提供的资料和建议！
