### ISSUE TITLE
导入Hexo后,_posts里只显示一个md

### ISSUE THREAD

**Issue by CmcnPro** [ivarptr/yu-writer.site#49]
OS: win10 15063.540  
导入本地hexo后,进入_posts文件夹里只显示一个md文件  
![snipaste_20170905_131935.jpg](https://ooo.0o0.ooo/2017/09/05/59ae341ad64f9.jpg)

**Comment by fanquqi** [comment]
跟我的问题一样  显示不全

**Comment by hemashushu** [comment]
@CmcnPro @fanquqi 谢谢反馈！我稍后排查一下。

**Comment by hemashushu** [comment]
@CmcnPro @fanquqi 新版本 0.5.3 已释出，已经解决了这个问题（是由于文档的 front matter 存在空值字段引起的），欢迎下载试用看看问题是否依旧，如有问题欢迎随时问，这个 issue 我先关闭哈。
