### ISSUE TITLE
能否关闭版本控制功能

### ISSUE THREAD

**Issue by qgaye** [ivarptr/yu-writer.site#491]
用于使用git管理Note的版本 所以不希望存在.resource文件夹

不知道现存版本中是否可以关闭此功能

**Comment by hemashushu** [comment]
@qgaye 目前版本还没有可以关闭历史记录的选项（主要是因为自动保存依赖这个特性才能回滚），不过可以更改库的配置文件让 .resource 文件夹挪到其他地方，比较简单的是添加 `isolateResource: true` 这样的一项，这样所有的 .resource 文件夹会被集中到库的根目录的一个名为 "yulib.resource" 文件夹之内。不过因为 0.6 版会对配置项的名称有些许改动，同时会增加图形的设置界面，所以建议稍微等一下等下一版出来时再修改。

目前的暂时解决方法是在库的根目录里创建一个 Git 的忽略文件列表文件 `.gitignore`，里面添加一行 `*.resource` 即可，具体方法可以参考这里：https://git-scm.com/docs/gitignore

**Comment by qgaye** [comment]
@ivarptr 👍 
`.gitignore`确实是很好的解决了我的需求，但还是希望在未来版本能加上关闭历史记录的选项，毕竟应该也有人（我猜的）和我一样想把它当作一个纯粹的markdown编辑器的  😄
