### ISSUE TITLE
latex行内右对齐

### ISSUE THREAD

**Issue by Zhaoqiu-hfut** [ivarptr/yu-writer.site#498]
latex 可以行内对齐吗

**Comment by hemashushu** [comment]
可以在公式块里面先加上 `\begin{align}` 和 `\end{align}`
然后使用 `&` 符号对齐，使用 `\\` 符号换行，示例：

```
$$
\begin{align}
y &= x + x + x & line1\\
  &= 2x +x & line2\\
  &= 3x & line3
\end{align}
$$
```
渲染结果：
<img width="737" alt="Screen Shot 2019-04-02 at 3 33 46 PM" src="https://user-images.githubusercontent.com/394223/55384317-f9ee3180-555c-11e9-80b0-017595b39737.png">
