### ISSUE TITLE
Why desktop tool?

### ISSUE THREAD

**Issue by immartian** [ivarptr/yu-writer.site#5]
All the functions in this tool seems can be done with a web application, why bother to ask user to download a software?

**Comment by hemashushu** [comment]
嗯，因为两者各有优缺点

**Comment by immartian** [comment]
can we commission you to do something?

**Comment by hemashushu** [comment]
@immartian 如果是想添加或者改进功能，可以先提出来，然后我会在后续发布的版本中完善它。如果是想私人定制一些功能，可能我暂时没有时间实现了，因为现在还有很多工作要做，抱歉。

**Comment by immartian** [comment]
What I meant is to hire you to develop another program.

**Comment by hemashushu** [comment]
@immartian 哈！我理解错了不好意思，现在我可能时间不够写其他项目，或者你把详细情况发到我邮箱吧 hippospark at gmail.com

**Comment by chenleigang** [comment]
为什么桌面工具？？？不懂题主哦
