### ISSUE TITLE
如何扩展代码块的类型

### ISSUE THREAD

**Issue by tardistao** [ivarptr/yu-writer.site#500]
**Platform/操作系统类型**
macOS

**OS version/操作系统版本**
macOS 10.14

**Application version/应用程序的版本号**
0.5.3

**Describe the bug/错误描述**
1. 最近学习Kotlin 语言，添加代码块时候，代码类型中没有这个选项，如何添加其他类型；
2. 添加代码块中内容乱码，大于号、引号没有被识别，如何转义处理；

**Comment by hemashushu** [comment]
@tardistao 可以试试手动输入语言名称，比如：

    ```kotlin
    content here...
    ```

第二个问题可能是因为“启用了HTML标签”功能引起的BUG，下个版本会修复，谢谢反馈
