### ISSUE TITLE
引用不起作用 Windows 版

### ISSUE THREAD

**Issue by houxiren** [ivarptr/yu-writer.site#501]
**Platform/操作系统类型**
Windows

**OS version/操作系统版本**
Windows 7
Windows 10  1803,1809 ...

**Application version/应用程序的版本号**
0.5.3

**Describe the bug/错误描述**
引用不起作用

**To Reproduce/如何重现该错误 （如果错误描述能说明清楚则忽略并删除该小节）**
以下截图中，左边是编辑窗口，右边的实时预览窗口。

**Screenshots/截图（如果截图能帮助描述问题的话则提供，不需要的则忽略并删除该小节）**

![image](https://user-images.githubusercontent.com/35322335/55455981-54989380-5618-11e9-902f-f5208e9d3194.png)

**Comment by hemashushu** [comment]
@houxiren 检查一下是否在设置里 “启用了HTML标签” 功能，这个功能目前有 bug，会误伤大于号小于号等符号

**Comment by houxiren** [comment]
不启用”HTML标签” 功能，就可以看到引用了。感谢。
