### ISSUE TITLE
全角空格

### ISSUE THREAD

**Issue by Zhaoqiu-hfut** [ivarptr/yu-writer.site#507]
不支持全角空格吗？

**Comment by hemashushu** [comment]
@Zhaoqiu-hfut 可以的话请具体描述一下问题，谢谢你的反馈

**Comment by Zhaoqiu-hfut** [comment]
就是段前空格的方法之一，使用全角空格就可识别了。但是这里没识别

**Comment by hemashushu** [comment]
@Zhaoqiu-hfut 嗯，因为 markdown 最终是解析成 html，所以有些在 html 里的特性在 markdown 里也存在，比如 1 个或多个空格只会显示为 1 个空格，1 行或多行空行也只会显示 1 行空行。如果是想在生成文档时每个段落空两格，可以通过更改 html 的样式来实现（而无需手动添加全角空格）。

**Comment by Zhaoqiu-hfut** [comment]
好的，谢谢。
