### ISSUE TITLE
选中顶层文件夹不显示子文件包含内容

### ISSUE THREAD

**Issue by tardistao** [ivarptr/yu-writer.site#508]
**Platform/操作系统类型**
macOS

**OS version/操作系统版本**
macOS  10.14

**Application version/应用程序的版本号**
0.5.3

[问题详情](http://zht.fwy.plus/%E9%97%AE%E9%A2%98.png)

同 #293

**Comment by hemashushu** [comment]
@tardistao 0.6 加入了透视文档列表（即显示本层及子一层共两层的文档）敬请期待哦😁

**Comment by tardistao** [comment]
期待，希望早日用到，强迫症很难受
