### ISSUE TITLE
下划线

### ISSUE THREAD

**Issue by Zhaoqiu-hfut** [ivarptr/yu-writer.site#509]
**Platform/操作系统类型**
Windows

![image](https://user-images.githubusercontent.com/28784286/55786767-78ac1700-5ae7-11e9-9100-1ab40ee25054.png)

**Comment by Zhaoqiu-hfut** [comment]
左边是不是有问题？

**Comment by hemashushu** [comment]
@Zhaoqiu-hfut 是的，目前编辑框的转义符号还没处理，大概会在 0. 6或者 0.7 版会把转义字符连同几个 bug 一起修复。

PS 另外编辑框的语法解析跟右侧的预览不完全一致，右侧的是遵循 commonmark 标准的渲染结果，而左侧的编辑框因为还要考虑录入响应速度问题，在语法解析上简化了很多，所以有些情况就被忽略掉了。

**Comment by Zhaoqiu-hfut** [comment]
好的，谢谢。
