### ISSUE TITLE
能否提供原生x64的编译版本？

### ISSUE THREAD

**Issue by ivysrono** [ivarptr/yu-writer.site#51]
我有个100M+的md文档要编辑，反复跳转，很容易内存不够崩溃，提供原生x64大概会好点吧……

**Comment by hemashushu** [comment]
@ivysrono 目前还没做到优化这一步，估计还不能编辑这么大的文档 😅 正式版后会提供 64 位版

**Comment by hemashushu** [comment]
@ivysrono 新版本 0.5.3 已释出，已提供 32 和 64 位两个版本，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
