### ISSUE TITLE
导出图片显示不全，导出 Html 乱码

### ISSUE THREAD

**Issue by tardistao** [ivarptr/yu-writer.site#510]
**Platform/操作系统类型**
macOS

**OS version/操作系统版本**
macOS 10.14

**Application version/应用程序的版本号**
0.5.3

**Describe the bug/错误描述**
1. 以图片形式导出所有内容，图片内容显示不全，导出图片选项还有错别字
2. 导出 html 格式乱码

[图片内容导出不全选项错别字](http://zht.fwy.plus/%E5%9B%BE%E7%89%87%E5%AF%BC%E5%87%BA%E4%B8%8D%E5%85%A8.png)

[导出 html 格式内容乱码](http://zht.fwy.plus/%E5%AF%BC%E5%87%BA%E5%86%85%E5%AE%B9%E4%B9%B1%E7%A0%81.png)

**Comment by tardistao** [comment]
导出乱码问题：
只发现 safari 有问题，Chrome 没问题
safari 版本：12.0 (14606.1.36.1.9)
Chrome 版本：73.0.3683.86（正式版本） （64 位）

**Comment by hemashushu** [comment]
@tardistao 收到，我稍后会检查一下。

**Comment by tardistao** [comment]
@ivarptr 修改 safari 的编码方式为 UTF - 8 没有乱码了，显示正常；使用 Safari 默认的编码方式会乱码

**Comment by hemashushu** [comment]
@tardistao 谢谢补充，检查一下是否导出时选中了 “Wordpress 帖子” 的 HTML 类型？这种类型只会导出一个片段（用于复制粘贴到 Wordpress 的文章编辑框，不适用于直接浏览器打开），而如果选择了导出 “Standard 标准” 类型，则会导出完整的 HTML，它会包含 `<meta charset="UTF-8">` 这样的告知浏览器编码格式的头部信息，这样用浏览器打开就不会有乱码。

**Comment by tardistao** [comment]
@ivarptr  嗯嗯，是选中了“Wordpress 帖子”，选择“标准” 导出没有乱码，感谢🙏
