### ISSUE TITLE
不知道什么问题 Cannot read property 'webContents' of null

### ISSUE THREAD

**Issue by Zhaoqiu-hfut** [ivarptr/yu-writer.site#514]
**Platform/操作系统类型**
Windows
![image](https://user-images.githubusercontent.com/28784286/55955881-27418a80-5c95-11e9-8d27-b6bb0dc16dff.png)

**Comment by Zhaoqiu-hfut** [comment]
现在都打不开了

**Comment by Zhaoqiu-hfut** [comment]
我的下星期的报告 😢

**Comment by Zhaoqiu-hfut** [comment]
重启再解压打开了。

**Comment by hemashushu** [comment]
@Zhaoqiu-hfut 抱歉回复晚了，这个错误收到很多例报告，但我一直没有重现出来所以还没确认是什么问题，错误的信息是说程序要发送一个消息到一个窗口，但目标窗口不见了。

猜测是程序还没完全退出（下次可以打开任务管理器看看是否还有 Yu Writer 字眼的进程），另外一个可能性是电脑休眠又再次醒来之后，有些窗口没有被系统回收了，总之可以试试在任务管理器里彻底把所有 Yu Writer 字眼的进程都杀掉，看能否复活。

**Comment by Zhaoqiu-hfut** [comment]
我好像是进行了大量粘贴之后出现的问题，可能和这无关。
