### ISSUE TITLE
优化引言标签

### ISSUE THREAD

**Issue by tardistao** [ivarptr/yu-writer.site#518]
**Platform/操作系统类型**
macOS

**OS version/操作系统版本**
macOS 10.14

**Application version/应用程序的版本号**
0.5.3

**Describe the bug/错误描述**
使用引言标签预览/导出文章内容 不明显，望改进

编辑中显示
[编辑中](http://zht.fwy.plus/%E5%BC%95%E8%A8%801.png)

预览中显示
[预览中](http://zht.fwy.plus/%E5%BC%95%E8%A8%802.png)

期望结果
[期望](http://zht.fwy.plus/%E5%BC%95%E8%A8%803.png)

**Comment by hemashushu** [comment]
@tardistao 你好，这个应该是 0.5.3 “启用 HTML 标签” 功能之后的 bug，它把 `>, <, &` 等符号都转义了，下个版本会修复

**Comment by idleGG** [comment]
刚想单独提交一个 issue 来说这事，好在写标题的时候看见了这条。同样 Windows 下 0.5.3 版本开启 html 解析后，引言标签无法进行解析和渲染了（编辑的时候仍然有特效）。
