### ISSUE TITLE
不支持 task list

### ISSUE THREAD

**Issue by wantanmee** [ivarptr/yu-writer.site#52]
希望加上对 task list 的支持
如
- [x] Mercury
- [ ] Venus

**Comment by hemashushu** [comment]
@wantanmee 谢谢你的意见

**Comment by elppac** [comment]
\+ 1

**Comment by hemashushu** [comment]
@wantanmee @elppac 新版本 0.5.3 已释出，已经支持 task list（在软件的菜单里称为任务列表），欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
