### ISSUE TITLE
在运行时随机会提示JavaScript错误

### ISSUE THREAD

**Issue by qgaye** [ivarptr/yu-writer.site#522]
**Platform/操作系统类型**
macOS & Windows

**OS version/操作系统版本**
macOS 10.14, ...
Windows 10 1803

**Application version/应用程序的版本号**
0.5.3

**Describe the bug/错误描述**
在win平台下打开软件提示JavaScript错误
在mac平台下复制时弹出JavaScript错误提示

**To Reproduce/如何重现该错误 （如果错误描述能说明清楚则忽略并删除该小节）**

玄学。。。

**Screenshots/截图（如果截图能帮助描述问题的话则提供，不需要的则忽略并删除该小节）**

![Jietu20190423-125222](https://user-images.githubusercontent.com/33546916/56555338-34c90f80-65c7-11e9-96d3-e1292f4f5343.png)

**Comment by hemashushu** [comment]
@qgaye 你好，这个错误提示是指目标窗口被关闭了，初步判断是因为程序因为某些原因部分窗口被（系统）关闭了，又或者程序因为一些未知的程序错误没有完全（彻底）退出，请尝试把程序彻底关闭再打开。下一版本会使用新的机制来管理窗口，希望能解决这个问题。
