### ISSUE TITLE
产品功能建议

### ISSUE THREAD

**Issue by GJXAIOU** [ivarptr/yu-writer.site#523]
1.强烈建议图片可以通过剪贴板直接黏贴；
2.强烈建议图片可以提供云端工具储存，分享笔记对方可以看到图片，不然只能分享PDF；
3.预览窗口能不能完全关闭，专注于做笔记；
4.强烈建议最左边缩进到边缘希望有提示；
5.直接将中文的···更换为```,因为不要插入代码，总是会切到中文；
6.笔记整体移动到别的文件夹；

作者辛苦啦，从有道云转来使用过程中想法较多，哈哈哈哈

**Comment by hemashushu** [comment]
咦～ 我之前好像回复过这个 issue，然后刚才再刷发现回复空空如也，可能是上次回复时太快关闭页面还没提交成功。

1、2、6 会在下个版本加上，5 也会在往后的版本加上，包括其他中文输入状态时输入的全角符号自动转换为 markdown 符号。4 会考虑用别的方法让光标和边界显示得更清楚。3 功能已实现，点击菜单的 “查看” 然后就可以找到 “显示/隐藏 预览”，或者使用上面显示的快捷键。感谢你的意见！

**Comment by GJXAIOU** [comment]
嗯呐，期待ing
