### ISSUE TITLE
data disappear in Yu Writer 0.5.3

### ISSUE THREAD

**Issue by erickguan** [ivarptr/yu-writer.site#525]
**Platform/操作系统类型**
macOS

**OS version/操作系统版本**
macOS 10.14.4

**Application version/应用程序的版本号**
0.5.3

**Describe the bug/错误描述**
All my data in Yu Writer disappear. What happens to the data stored?

**To Reproduce/如何重现该错误 （如果错误描述能说明清楚则忽略并删除该小节）**

1. open the program

**Screenshots/截图（如果截图能帮助描述问题的话则提供，不需要的则忽略并删除该小节）**
![image](https://user-images.githubusercontent.com/297343/56975164-839b1a00-6b70-11e9-8ad4-fd23599b3523.png)

**Comment by hemashushu** [comment]
@fantasticfears 你好，Yu Writer 没有自己的数据库，文档库及文档数据都建立在本地文件夹及文件基础至上，比如 inbox 以及 default 文档库实际上列出的是 `~/Documents/Yu Writer Libraries/Inbox` 和 `~/Documents/Yu Writer Libraries/Default` 文件夹里面的文件，请检查一下这两个文件夹的文件是否被移动到其他地方了。

**Comment by erickguan** [comment]
我从 Time Machine 里抓出了备份。我猜测原因是因为 iCloud 同步中断后，文件就被吞了。然后新启动的 Yu Writer 重新建立了文档库。
