### ISSUE TITLE
PDF导出排版出错

### ISSUE THREAD

**Issue by Zhaoqiu-hfut** [ivarptr/yu-writer.site#528]
**win10**

![image](https://user-images.githubusercontent.com/28784286/57631172-8fa3c480-75d1-11e9-9f1c-21e767ef9338.png)

**Comment by hemashushu** [comment]
收到，中间那条是分页隔离条吗？大致是因为公式区块被当成图片被简单粗暴地切分了，以后版本会加入页面非文本元素是否被分页切割的判断，谢谢反馈。

**Comment by Zhaoqiu-hfut** [comment]
> 收到，中间那条是分页隔离条吗？大致是因为公式区块被当成图片被简单粗暴地切分了，以后版本会加入页面非文本元素是否被分页切割的判断，谢谢反馈。

对，导出的PDF的分页隔离条。
