### ISSUE TITLE
新功能建议

### ISSUE THREAD

**Issue by Zhaoqiu-hfut** [ivarptr/yu-writer.site#529]
以后是不是可以通过复制网页上的带格式的文本到软件里直接按原网页渲染。

**Comment by hemashushu** [comment]
@Zhaoqiu-hfut 现在复制网页的内容粘贴到编辑器时会自动转换为 markdown 文本，基本的 html 标签都能转换，毕竟 markdown 本质就是轻量级的 html 原始文本，但完全一样效果是不可能了，因为 markdown 只能表现有限数量的 html 标签，再有就是网页有自己的一套样式，而 markdown 的文本没法定义样式，只能使用编辑软件的主题或者导出时所选择的样式表。

**Comment by Zhaoqiu-hfut** [comment]
是，我后来发现了，谢谢！
