### ISSUE TITLE
能否添加html标签

### ISSUE THREAD

**Issue by dornenkrone** [ivarptr/yu-writer.site#53]
之前使用markdown语法拓展部分 用来写论文草稿很棒   如果可以的话能否添加一下html标签的功能呢

万分感谢

PS：这个软件真的是我碰到最优秀的markdown编辑器了   操作界面友好。支持tex公式渲染 而且还有实时预览   真的比市面上的很多编辑器好太多了   十分感谢开发者

**Comment by hemashushu** [comment]
@dornenkrone 以后会在library上加上选项是否允许 html，谢谢反馈和鼓励！

**Comment by hemashushu** [comment]
@dornenkrone 新版本 0.5.3 已释出，已经加上解析 html 标签的选项，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
