### ISSUE TITLE
请问预览的Default选项是什么风格的呢？

### ISSUE THREAD

**Issue by Dakai** [ivarptr/yu-writer.site#538]
没有Linux版本，只好用别的编辑器写文档，可是输出都没有Yu Writer好看，想问一下缺省的预览是用什么风格（Flavor）的？谢谢

**Comment by hemashushu** [comment]
@Dakai 语法解析是 Commom Mark + GFM，样式表是自己调的，css 的话在应用程序里面有（mac 版可以直接打开查看，win 版需要解压里面的 app.asar 这个压缩包）

**Comment by Dakai** [comment]
好的，感谢！
