### ISSUE TITLE
建议出个0.5.4的修复版本

### ISSUE THREAD

**Issue by hetianfei** [ivarptr/yu-writer.site#539]
我本身也是付费的用户，用了yu-writer也比较久了
考虑到作者可能比较忙，能否出个0.5.4的修复版本哈
就把哪些能快速解决的缺陷解决一下
@ivarptr

**Comment by hemashushu** [comment]
@hetianfei 真是很抱歉，很久之前我也想出个 0.5.4，后来因为别的事情停了好一段时间没有写代码，再后来已经不知不觉把整个程序拆散了（因为 0.6 版的架构有变），中间层代码也重构了一遍（一些比如 HTML 标签渲染的 bug 也是在这里解决），所以也没法把后来的代码套在 0.5.3 上，现在只能再等等 0.6 了 😭😭

**Comment by hetianfei** [comment]
期待0.6，加油哈~
