### ISSUE TITLE
转换粘贴内容为Markdown时出现问题

### ISSUE THREAD

**Issue by xfrose** [ivarptr/yu-writer.site#55]
粘贴内容中，在段落起始位置的句子，如果句末符号是。或：时，转换后不能显示原来的效果。
比如，原文为html，星号内为加粗效果：
**第一，aaaa。**blablabla……
**第二，bbbb。**blablabla……

转换后就会和上面一样，加粗的效果丢失，要手动在**和blablabla之间插入空格才行。
这似乎是markdown本身的设置？如果是的话，请问能否让软件自动添加空格？
谢谢！

**Comment by hemashushu** [comment]
是我的语法加亮部分的bug，谢谢反馈
