### ISSUE TITLE
[功能建议] 一些未来可能需要做的功能

### ISSUE THREAD

**Issue by StringKe** [ivarptr/yu-writer.site#550]
### 01 图床
这个还是比较重要的。我看了6.0如果说6.0发布了 图床可能也是需求比较大的功能点了
(七牛，upyun，oss，自定义接口)

### 02 同步
我看到现在版本可以链接一个文档库为 hexo等程序，那么对应的hexo同步命令( hexo g -d )也可以做出一个功能入口
(wordpress,等等其他,维护一个自有的同步方式[这样可以对接更多的开发者自主开发程序])

**Comment by hemashushu** [comment]
好的，谢谢建议！

**Comment by xmory** [comment]
希望链接可以支持插入非本目录的文档

**Comment by hemashushu** [comment]
@xmory 这个有，谢谢建议！
