### ISSUE TITLE
方程只在读模式下渲染，在预览中不渲染

### ISSUE THREAD

**Issue by wbgt** [ivarptr/yu-writer.site#56]
我用的是 OSX 系统。

非常好的应用，如果能进一步完善，我准备从 Atom+MPE 迁移过来。

**Comment by hemashushu** [comment]
因为渲染方程式比较耗CPU，所以默认是不渲染的，但可以在 settings 里勾选让它渲染

**Comment by hemashushu** [comment]
@wbgt 新版本 0.5.3 已释出，已经改进了渲染方程式的速度，所以默认现在是渲染方程的，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
