### ISSUE TITLE
0.5.3 版本无法创建新文件以及无法显示文档库中的文件

### ISSUE THREAD

**Issue by hirat** [ivarptr/yu-writer.site#567]
看之前的描述是不限制个人使用，但是现在无法创建文档，无法加载文档库中的文件了，请问如何解决？
是需要付费了吗？

**Comment by hemashushu** [comment]
@hirat 估计是碰到了 0.5.3 版的一个 bug 了，这个 bug 会导致文档库列表显示不出来，详细方法见 https://github.com/ivarptr/yu-writer.site/issues/463 以及 https://github.com/ivarptr/yu-writer.site/issues/373

**Comment by hirat** [comment]
> @hirat 估计是碰到了 0.5.3 版的一个 bug 了，这个 bug 会导致文档库列表显示不出来，详细方法见 #463 以及 #373

谢谢，按照上面提到的方法，解决了！
