### ISSUE TITLE
自动化排版上的 Bug

### ISSUE THREAD

**Issue by kmahyyg** [ivarptr/yu-writer.site#573]
**Platform/操作系统类型**
Windows

**OS version/操作系统版本**

Windows 8.1

**Application version/应用程序的版本号**
0.5.3

**Describe the bug/错误描述**

- 预览界面切换 Theme 会导致不恰当的 `style` front matter 的插入

![image](https://user-images.githubusercontent.com/16604643/67458907-e83fb900-f669-11e9-9939-4377fed5c64e.png)

Reproduce：在查看预览界面快速的切换 theme

- 有序列表下存在多余的新的空行时按下回车，没有正确插入下一个序号到下一行，而是插入到了当前行。

![image](https://user-images.githubusercontent.com/16604643/67459032-30f77200-f66a-11e9-854a-04f0f094f1cf.png)

此时按下回车会出现 `2.` 紧跟在 `test` 之后的情况，**不稳定复现**。

![image](https://user-images.githubusercontent.com/16604643/67459113-5f754d00-f66a-11e9-9e3d-47477270d86b.png)

**Comment by hemashushu** [comment]
@kmahyyg 谢谢反馈！

**Comment by kmahyyg** [comment]
Enhancement Request: 例如：对于 markdown 加粗语法的自动补全，常规情况下用户输入 `**` 会被自动补齐成 `**xx**` ，但是如果用户此时输入的是 `****`，能不能像 typora 那样覆盖补齐的 asterisk 而不是 变成 `******`

**Comment by hemashushu** [comment]
@kmahyyg 这个提议非常好，已经加入开发列表，谢谢建议！

**Comment by kmahyyg** [comment]
Silent for too long... Close for clearing un-done issues.
