### ISSUE TITLE
行内公式显示错误

### ISSUE THREAD

**Issue by AngelPone** [ivarptr/yu-writer.site#580]
**Platform/操作系统类型**
macOS

**OS version/操作系统版本**
macOS 10.14

**Application version/应用程序的版本号**
0.5.3

**Describe the bug/错误描述**

行内公式显示错误

**To Reproduce/如何重现该错误 （如果错误描述能说明清楚则忽略并删除该小节）**

输入行内公式即可

**Screenshots/截图（如果截图能帮助描述问题的话则提供，不需要的则忽略并删除该小节）**

![image](https://user-images.githubusercontent.com/32930283/71464322-f211a400-27f3-11ea-873d-3102780fc78f.png)
![image](https://user-images.githubusercontent.com/32930283/71464337-fb9b0c00-27f3-11ea-87c5-ed2630d4efb7.png)

**Comment by hemashushu** [comment]
收到，是语法解析部分的一个 bug，谢谢反馈！
