### ISSUE TITLE
文字計算

### ISSUE THREAD

**Issue by moonten** [ivarptr/yu-writer.site#59]
意外情況下試用yu-writer，發現是非常好用的寫作工具，感謝開發者的努力！

除了大家已經建議的中文、輸出word、輸出evernote功能，
另外，文字計算希望能加入包含標點符號的計算方式（最好直接呈現在編輯區下方），這樣會更符合寫作與碼字作者們控制文章字數的需求。

最後，希望yu-writer愈來愈好，加油！

**Comment by Coooolinz** [comment]
非常赞同，字数统计是协作软件非常重要的功能！

**Comment by vyan13** [comment]
滋磁这个，以及，除了请求添加某个界面的字符数，是否可以统计某本书或者某个集合的字符数呢🙃

**Comment by hemashushu** [comment]
0.5 版将会在编辑状态下加上字数统计，谢谢各位的意见

**Comment by hemashushu** [comment]
@moonten @Coooolinz 新版本 0.5.3 已释出，已经加入字数统计功能，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
