### ISSUE TITLE
斜体语法可否改进&斜体不显示bug

### ISSUE THREAD

**Issue by hooke007** [ivarptr/yu-writer.site#592]
**Platform/操作系统类型**
win10 1909

**Application version/应用程序的版本号**
0.5.3 x64

**Describe the bug/错误描述**
1 斜体的这个语法挺容易和我在文本中写文件路径冲突的，作者可以考虑把`_斜体_`换成`__斜体__`

2 然后在导出和预览中斜体没法实现，编辑框却可以....

**Screenshots/截图（如果截图能帮助描述问题的话则提供，不需要的则忽略并删除该小节）**
<a href="https://sm.ms/image/G8usmiefx9jaLcl" target="_blank"><img src="https://i.loli.net/2020/05/06/G8usmiefx9jaLcl.jpg" /></a>

**Comment by hooke007** [comment]
追加问题：
把.py自动识别成了链接

<a href="https://sm.ms/image/2QnhAvRXxmGsHN6" target="_blank"><img src="https://i.loli.net/2020/05/06/2QnhAvRXxmGsHN6.jpg" /></a>

**Comment by hemashushu** [comment]
@hooke007 下个版本将会有选项选择粗体、斜体等格式的符号，谢谢反馈。
另外如果在正文里有表示代码、命令、文件路径等的地方，考虑使用反单引号引起来，比如：
`c:\temp> dir`
`$ find /usr/lib -name "some.so"`
被引起来的文本将会使用等宽字体原样输出。

注：上面两行的原始文本如下
```
`c:\temp> dir`
`$ find /usr/lib -name "some.so"`
```

**Comment by hooke007** [comment]
我发现一些高级语法无法实现比如最简单的 `<font color=red>xxx</font>`
是尚未开发还是我的姿势不对.......

**Comment by hemashushu** [comment]
默认没解析 HTML 标签，因为正文中的 `< > &` 符号很常见，所以对普通用户来说很容易导致非预期的结果。如果实在需要渲染 HTML 标签，可以在设置里打开这个功能

（不过这个功能现阶段有个小 bug，它会把表示引用的 `>` Markdown 符号以及代码块中 `< > & ` 符号也都解析成 HTML 了）

**Comment by hooke007** [comment]
这个功能我打开了，还是没有区别

**Comment by hemashushu** [comment]
@hooke007 哦哦，不好意思刚才我没看仔细。如果是特指 `<font>` 这个标签不起作用的话，那是因为这个标签属于标准里不再推荐的标签 https://developer.mozilla.org/en-US/docs/Web/HTML/Element/font
yu 也就不再解析这个标签了，可以考虑用 `<span style="color:red, .......">` 代替。

另外为了防止在文档里被嵌入恶意代码， yu 有一个长长的 HTML 标签白名单，只有在白名单里面的标签及属性才被解析，详细列表请见随软件附带的《手册》里面的说明。

**Comment by hooke007** [comment]
MD没有统一的规范真的好麻烦~~~
话说一年过去了进度还是7/20吗 cry~~~

**Comment by rj-yuting** [comment]
求更新。。。

**Comment by rj-yuting** [comment]
麻烦看下邮箱，迫不及待想试下全部功能。。

**Comment by hooke007** [comment]
> 麻烦看下邮箱，迫不及待想试下全部功能。。

你是走错地了吗....

**Comment by rj-yuting** [comment]
@ivarptr 麻烦看下邮箱  @hooke007 -.- 哈哈...借楼表达下心情。
