### ISSUE TITLE
启动时界面未能正常显示(界面位置初始化到屏幕外了)

### ISSUE THREAD

**Issue by RipplePiam** [ivarptr/yu-writer.site#606]
**Platform/操作系统类型**
 Windows 10 x64 1909

**Application version/应用程序的版本号**
v0.5.3

**Describe the bug/错误描述**
启动软件后软件显示到屏幕外面去了，九头牛拉都拉不回来。。。

**Screenshots/截图**
![FSC0283](https://user-images.githubusercontent.com/45916506/93661202-8873ad00-fa88-11ea-857b-4b65c8665f9c.jpg)

**Comment by hemashushu** [comment]
@RipplePiam 请问是外接过屏幕吗？程序是有个 bug，就是会记住上一次程序关闭时的位置和大小，在下一次启动时忘记了判断连接的屏幕是否有更改，可以试试把程序的配置文件删除以恢复默认值，配置文件的位置：

* Windows: C:\Users\USER_NAME\AppData\Roaming\Yu Writer\config
* macOS: /Users/USER_NAME/Library/Application Support/Yu Writer/config

文件名是 app.json

**Comment by RipplePiam** [comment]
@ivarptr 对的，外接过屏幕，忘了说了。重置后问题解决了，感谢！
