### ISSUE TITLE
怎么修改默认的文件保存位置，以后是否可以发布中文版的YU Writer呢？

### ISSUE THREAD

**Issue by weizhiwen** [ivarptr/yu-writer.site#61]

**Comment by zangbob** [comment]
修改默认保存位置的方法：
https://github.com/ivarptr/yu-writer.site/issues/16

**Comment by hemashushu** [comment]
@zangbob 非常感谢帮忙解答！

**Comment by hemashushu** [comment]
@weizhiwen 新版本 0.5.3 已释出，已经加上中文界面，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
