### ISSUE TITLE
无序列表和展示

### ISSUE THREAD

**Issue by JohnnyWoong** [ivarptr/yu-writer.site#64]
无序列表好像没有作用,* - + 都显示为原来的,右侧显示有点问题,有些***能正常显示,有些则不显示,但是按read more则是正常的
另外希望能添加自动添加的功能,就类似于对无序列表和有序列表换行时能自动补上数字或者是无序符号,就像马克飞象那样,最好也来个类似马克飞象的选择框功能就更好啦 
- [ ] 已选择
- [x] 未选择

**Comment by hemashushu** [comment]
好的，估计下个版本会实现，谢谢意见！

**Comment by hemashushu** [comment]
@JohnnyWongC 新版本 0.5.3 已释出，已经加上自动补完、复选框功能，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
