### ISSUE TITLE
windows版本zoom in和zoom out的级数太少了

### ISSUE THREAD

**Issue by totalwei** [ivarptr/yu-writer.site#67]
windows版本zoom in和zoom out的级数太少了。
用于演示时，想放大一些给别人看清楚一点，但是yu-writer却放的不够大。1920*1080的屏幕。
建议增加放大级数。

**Comment by hemashushu** [comment]
@aqxin 谢谢你的意见！

**Comment by hemashushu** [comment]
@totalwei 新版本 0.5.3 已释出，已经解决了这个问题，同时还增加了演示模式，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
