### ISSUE TITLE
instant view 无法切换style

### ISSUE THREAD

**Issue by RonaldinhoL** [ivarptr/yu-writer.site#70]
貌似没找到设置instant view的渲染style呀？在read mode 里设置了style但是在instant view里面不生效，一直都是默认的样子，希望instant view 和 read mode的渲染表现一致。

另外赞一个，这简直是完美的MD编辑器！

**Comment by hemashushu** [comment]
@RonaldinhoL 谢谢你的建议。

**Comment by hemashushu** [comment]
@RonaldinhoL 最后还是保留 “即时预览” 的样式跟主题绑定这种方案，因为主题有深色，style 一般浅色背景（也有深色背景），如果不绑定会容易造成深浅色不一致问题。
另外新版本 0.5.3 已释出，0.5 这个版本改动很大，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
