### ISSUE TITLE
希望添加快捷键功能，能极大提高写作效率

### ISSUE THREAD

**Issue by ghost** [ivarptr/yu-writer.site#71]
希望添加快捷键功能，能极大提高写作效率

作者的软件非常好，但是一个人毕竟精力有限，不知道是否考虑到开源源代码，已让所有的人都可以为这款软件做出贡献。

**Comment by hemashushu** [comment]
@SickoOrange 下一个版本会加上快捷键。是的，现在空闲时间较少，所以开发速度比较慢，现在源码写得比较简陋不敢开源，哈哈哈，或者以后重构几次之后再考虑

**Comment by ghost** [comment]
@ivarptr  其实可以考虑社区的强大力量，开源的话你个人的压力会减少很多，又会有人做代码的重构工作。  个人目前有一些想法 对于这款软件，比如加入账号登录， 开通云端存储等等想法，可惜没有源代码，无法下手。但是如果自己重新再写一个编辑器，感觉也是费力不讨好，重复造轮子。 所以在此请求楼主开源

**Comment by fff89** [comment]
还是可以开源的,一直很想写个类似的软件,

**Comment by hemashushu** [comment]
@SickoOrange @fengbjhqs 新版本 0.5.3 已释出，已经加上编辑快捷键，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
