### ISSUE TITLE
希望支持html标签

### ISSUE THREAD

**Issue by neverrop** [ivarptr/yu-writer.site#77]
比如这样居中插入图片
<center>
<img src="as" style="zoom:40%" />
</center>

谢谢啦

**Comment by hemashushu** [comment]
@neverrop 收到，谢谢你的建议！

**Comment by hemashushu** [comment]
@neverrop 新版本 0.5.3 已释出，已经加上解析 html 标签的选项，软件附带的文档有详细的 html 使用说明，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
