### ISSUE TITLE
Occur a crash when I use yu-writer

### ISSUE THREAD

**Issue by doublnt** [ivarptr/yu-writer.site#79]
Hello, I am a new in yu-writer, I found a bug when I write my blogs. 
When I type `### ` Then if I type something else  it occurs crash. 
There is a gif show the crash following
![](https://ws2.sinaimg.cn/large/006tKfTcgy1fkd7uesecfg30in0j7q78.gif)

**Comment by doublnt** [comment]
10.11 Supply:
It only occurs when I use the Mac Chinese Input Method.

**Comment by hemashushu** [comment]
@doublnt Yes, this is a known bug, it will be fixed in the next version

**Comment by doublnt** [comment]
@ivarptr 👍

**Comment by hemashushu** [comment]
@doublnt 新版本 0.5.3 已释出，已经修复这个 bug，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。

**Comment by doublnt** [comment]
@ivarptr  谢谢，爱你哟。哈哈
