### ISSUE TITLE
Format 始终是灰色的，不能点击，快捷键无效

### ISSUE THREAD

**Issue by EkkoG** [ivarptr/yu-writer.site#8]
![image](https://user-images.githubusercontent.com/3138493/29446270-e0aab89a-841d-11e7-9425-278cbd8628b8.png)

**Comment by hemashushu** [comment]
@cielpy 你好，是这样的，这些标有星星的功能是还没完成的，目前整个自动完成模块（负责解析format一系列命令）还没完成，所以就整个format功能都暂时禁用了，估计要在0.6.x 版才完成。

**Comment by EkkoG** [comment]
好的，谢谢回复，软件很漂亮，但是功能还有些欠缺

**Comment by hemashushu** [comment]
@cielpy 谢谢鼓励，现在正努力填码中 😅

**Comment by lxj198786** [comment]
同求快捷键功能
好人一生平安

**Comment by hemashushu** [comment]
@cielpy @lxj198786 0.5 版已经完成，欢迎下载试用，如果有问题欢迎随时反馈，这个 issue 我先关闭咯。
