### ISSUE TITLE
数学公式渲染不正确

### ISSUE THREAD

**Issue by DavichiHug** [ivarptr/yu-writer.site#80]
The mathematical formula is incorrect, but the export is correct and hopefully   
![snipaste_2017-10-10_16-37-40](https://user-images.githubusercontent.com/23614846/31377147-addf9224-add9-11e7-9cd3-c5db7edf5556.png)

**Comment by hemashushu** [comment]
@DavichiHug Mathematical Formula instant rendering is disabled by default because of performance issues, but it can be activated in the Settings.

**Comment by DavichiHug** [comment]
over！（Solved）

**Comment by hemashushu** [comment]
@DavichiHug 新版本 0.5.3 已释出，已经改进了数学公式渲染速度，所以现在默认是打开渲染公式功能了，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
