### ISSUE TITLE
左侧Libraries的目录可否改为单击进入

### ISSUE THREAD

**Issue by liuxsdev** [ivarptr/yu-writer.site#81]
左侧Libraries的目录可否改为单击进入
目录太多的话双击很麻烦
![snipaste_20171011_103319](https://user-images.githubusercontent.com/11004456/31419698-c45b52d6-ae6f-11e7-9987-87d36012e49f.png)

**Comment by hemashushu** [comment]
@smilevent 下个版本会改为单击，谢谢反馈

**Comment by ghost** [comment]
@ivarptr  我觉得最好在设置里面可以让用户自己设置是否是单击或者双击，

**Comment by liuxsdev** [comment]
右边那个三角形可单击，整个框框单击双击都能打开目录如何
