### ISSUE TITLE
偶发性bug: 阅读界面无法切换文档风格

### ISSUE THREAD

**Issue by tigerga** [ivarptr/yu-writer.site#82]
复现步骤：
1、打开用户文档，进入阅读模式，切换文档风格；
2、打开帮助文件，进入阅读模式，无法切换文档风格。

**Comment by hemashushu** [comment]
@tigerga 这个应该是随软件附带的几个说明文档（只读）存在的bug，对于普通（自己创建的）文档应该没问题，下一个版本会修复这个bug，谢谢反馈！

**Comment by hemashushu** [comment]
@tigerga 新版本 0.5.3 已释出，已经解决了这个问题，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
