### ISSUE TITLE
spell check

### ISSUE THREAD

**Issue by eygnoh** [ivarptr/yu-writer.site#85]
This is a tremendous markdown app, but I hope it can incorporate spell & grammar check on the go,  thank you!

**Comment by hemashushu** [comment]
@eygnoh ok, thanks!

**Comment by hemashushu** [comment]
@eygnoh 新版本 0.5.3 已释出，已经加入了 spell check 功能，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭。
