### ISSUE TITLE
格式快捷键和菜单栏不可用

### ISSUE THREAD

**Issue by Hansi7** [ivarptr/yu-writer.site#87]
如图所示，不知道什么原因。
![image](https://user-images.githubusercontent.com/8850691/31869107-525f17f4-b7d8-11e7-9b34-e803fdf83a9c.png)

**Comment by hemashushu** [comment]
@Hansi7 这些功能还没完成所以就暂时禁用了，下个版本将会可用。

**Comment by hemashushu** [comment]
@Hansi7 新版本 0.5.3 已释出，已经完成所有快捷键，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
