### ISSUE TITLE
代码块选项有点少.能不能增加多一点

### ISSUE THREAD

**Issue by wangchangsong** [ivarptr/yu-writer.site#88]

**Comment by hemashushu** [comment]
@wangchangsong ok，插入代码窗口主要是用于美化/格式化代码，目前支持美化的语言比较有限。如果是一般性的插入代码，可以先选择 genernal，插入代码之后再手动添加语言名称。

**Comment by hemashushu** [comment]
@wangchangsong 新版本 0.5.3 已释出，已经加入常见的语言选项，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
