### ISSUE TITLE
请问md下划线功能是不是没有添加呢？

### ISSUE THREAD

**Issue by echosun1996** [ivarptr/yu-writer.site#91]
如题

**Comment by hemashushu** [comment]
@echosun1996 是的，下个版本加上。

**Comment by hemashushu** [comment]
@echosun1996 新版本 0.5.3 已释出，已经加上下划线，比如 `++我是下划线++`，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
