### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by hyprocritor** [ivarptr/yu-writer.site#95]
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: EEXIST: file already exists, mkdir 'C:\Users\chenz\OneDrive\文档\Yu Writer Libraries'

[OK]
看起来是个已存在文档catch的问题啊……
Version: 0.44 Beta
OS: WINDOWS 10 16215

**Comment by hemashushu** [comment]
@czk1997 根据提示可能是因为你的系统把 ”我的文档“ 整个移动到 OneDrive 引起的，0.4.4 版对 OneDrive 的 ”file on demand“ 有个bug，下个版本会解决。暂时的解决方法是关闭 OneDrive 的 file on demand 或者手动创建 ”Yu Writer Libraries“ 这个文件夹。

**Comment by hemashushu** [comment]
@czk1997 新版本 0.5.3 已释出，已经解决了这个问题，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
