### ISSUE TITLE
改进建议

### ISSUE THREAD

**Issue by mmcer** [ivarptr/yu-writer.site#96]
和 MarkdownPad 相比貌似不支持 ## 以及 <br /> 
请现在考虑多语言翻译问题，以后再考虑重构工作比较大。支持中文会获得更多用户。
那个图标文件是否可以删除，我在windows上删除了那个黄色的图标，发现一样可以使用。

**Comment by hemashushu** [comment]
@mmcer 应该是支持 ## 的，注意是顶行写，两个英文井号，然后加一个英文空格，再写标题内容，比如

## 我是二级标题

那个图标是可以删的。至于多语言模块，等到软件比较稳定时会加上，现在因为每个版本变化都很大，所以还没加上。

**Comment by hemashushu** [comment]
@mmcer 新版本 0.5.3 已释出，已经加入多语言模块，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
