### ISSUE TITLE
0.5版本什么时候release？很期待

### ISSUE THREAD

**Issue by chixiang** [ivarptr/yu-writer.site#98]
0.5版本什么时候release？很期待

**Comment by hemashushu** [comment]
@chixiang 0.5 版可以说是一个变化非常大（目前大部分未完成的功能都会加上）的版本，工作量比预计大很多加上空闲时间较少，所以可能还得一两个月之后才能完成，谢谢支持！

**Comment by whzecomjm** [comment]
期待

**Comment by hemashushu** [comment]
@chixiang @whzecomjm  0.5 已发布
