### ISSUE TITLE
是你的项目让我对node.js产生了兴趣

### ISSUE THREAD

**Issue by zhaohl1993** [ivarptr/yu-writer.site#99]
我还是头一次知道原来js可以制作桌面应用，很兴奋，我本来都是准备转后台的人了。现在我也准备自己开发一个markdown的项目，预期两个月写出最初版。到时候给你看啊

**Comment by hemashushu** [comment]
@zhaohl1993 哈哈，好的！

**Comment by yanweijia** [comment]
@zhaohl1993 微信官方小程序的开发工具就是用node.js写的

**Comment by hemashushu** [comment]
@zhaohl1993 hi，你的程序写完了吗？哈哈。新版本 0.5.3 已释出，欢迎下载试用，如有问题欢迎随时问，这个 issue 我先关闭哈。
